<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Dialog;

use Jovian\Bindings\Sdl3\Enums\SDLFileDialogType;
use Sdl3\SDL\Dialog\SDLDialog as ExtSDLDialog;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Dialog\SDLDialog
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLDialog
{
    /**
     * SDL_ShowFileDialogWithProperties().
     */
    public static function SDLShowFileDialogWithProperties(SDLFileDialogType|int $type, mixed $callback, int $props): void
    {
        ExtSDLDialog::SDLShowFileDialogWithProperties($type instanceof \BackedEnum ? $type->value : $type, $callback, $props);
    }

    /**
     * SDL_ShowOpenFileDialog().
     */
    public static function SDLShowOpenFileDialog(mixed $callback, int $window = 0, mixed $filters = null, mixed $default_location = null, bool $allow_many = false): void
    {
        ExtSDLDialog::SDLShowOpenFileDialog(...array_slice([$callback, $window, $filters, $default_location, $allow_many], 0, func_num_args()));
    }

    /**
     * SDL_ShowOpenFolderDialog().
     */
    public static function SDLShowOpenFolderDialog(mixed $callback, int $window = 0, mixed $default_location = null, bool $allow_many = false): void
    {
        ExtSDLDialog::SDLShowOpenFolderDialog(...array_slice([$callback, $window, $default_location, $allow_many], 0, func_num_args()));
    }

    /**
     * SDL_ShowSaveFileDialog().
     */
    public static function SDLShowSaveFileDialog(mixed $callback, int $window = 0, mixed $filters = null, mixed $default_location = null): void
    {
        ExtSDLDialog::SDLShowSaveFileDialog(...array_slice([$callback, $window, $filters, $default_location], 0, func_num_args()));
    }
}
