<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_AudioFormat, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 *
 * Members PHP cannot hold, and why:
 *  - SDL_AUDIO_S32 (alias of SDL_AUDIO_S32BE)
 */
enum SDLAudioFormat: int
{
    case UNKNOWN = 0; // SDL_AUDIO_UNKNOWN
    case U8 = 8; // SDL_AUDIO_U8
    case S8 = 32776; // SDL_AUDIO_S8
    case S16LE = 32784; // SDL_AUDIO_S16LE
    case S16BE = 36880; // SDL_AUDIO_S16BE
    case S32LE = 32800; // SDL_AUDIO_S32LE
    case S32BE = 36896; // SDL_AUDIO_S32BE
    case F32LE = 33056; // SDL_AUDIO_F32LE
    case F32BE = 37152; // SDL_AUDIO_F32BE
}
