<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_BlendMode, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 *
 * This family is a bitmask. Parameters that take it stay `int` in the
 * projection, because PHP enum cases cannot be OR'd together; pass
 * `SomeCase->value | OtherCase->value`.
 */
enum SDLBlendMode: int
{
    case NONE = 0; // SDL_BLENDMODE_NONE
    case BLEND = 1; // SDL_BLENDMODE_BLEND
    case BLEND_PREMULTIPLIED = 16; // SDL_BLENDMODE_BLEND_PREMULTIPLIED
    case ADD = 2; // SDL_BLENDMODE_ADD
    case ADD_PREMULTIPLIED = 32; // SDL_BLENDMODE_ADD_PREMULTIPLIED
    case MOD = 4; // SDL_BLENDMODE_MOD
    case MUL = 8; // SDL_BLENDMODE_MUL
    case INVALID = 2147483647; // SDL_BLENDMODE_INVALID
}
