<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_Colorspace, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 *
 * Members PHP cannot hold, and why:
 *  - SDL_COLORSPACE_RGB_DEFAULT (alias of SDL_COLORSPACE_SRGB)
 *  - SDL_COLORSPACE_YUV_DEFAULT (alias of SDL_COLORSPACE_BT601_LIMITED)
 */
enum SDLColorspace: int
{
    case UNKNOWN = 0; // SDL_COLORSPACE_UNKNOWN
    case SRGB = 301991328; // SDL_COLORSPACE_SRGB
    case SRGB_LINEAR = 301991168; // SDL_COLORSPACE_SRGB_LINEAR
    case HDR10 = 301999616; // SDL_COLORSPACE_HDR10
    case JPEG = 570426566; // SDL_COLORSPACE_JPEG
    case BT601_LIMITED = 554703046; // SDL_COLORSPACE_BT601_LIMITED
    case BT601_FULL = 571480262; // SDL_COLORSPACE_BT601_FULL
    case BT709_LIMITED = 554697761; // SDL_COLORSPACE_BT709_LIMITED
    case BT709_FULL = 571474977; // SDL_COLORSPACE_BT709_FULL
    case BT2020_LIMITED = 554706441; // SDL_COLORSPACE_BT2020_LIMITED
    case BT2020_FULL = 571483657; // SDL_COLORSPACE_BT2020_FULL
}
