<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_DisplayOrientation, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLDisplayOrientation: int
{
    case UNKNOWN = 0; // SDL_ORIENTATION_UNKNOWN
    case LANDSCAPE = 1; // SDL_ORIENTATION_LANDSCAPE
    case LANDSCAPE_FLIPPED = 2; // SDL_ORIENTATION_LANDSCAPE_FLIPPED
    case PORTRAIT = 3; // SDL_ORIENTATION_PORTRAIT
    case PORTRAIT_FLIPPED = 4; // SDL_ORIENTATION_PORTRAIT_FLIPPED
}
