<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_EventAction, mined from the SDL3 headers: ext-sdl3 0.7.0
 * exposes no class constants of its own.
 */
enum SDLEventAction: int
{
    case ADDEVENT = 0; // SDL_ADDEVENT
    case PEEKEVENT = 1; // SDL_PEEKEVENT
    case GETEVENT = 2; // SDL_GETEVENT
}
