<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_FileDialogType, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLFileDialogType: int
{
    case OPENFILE = 0; // SDL_FILEDIALOG_OPENFILE
    case SAVEFILE = 1; // SDL_FILEDIALOG_SAVEFILE
    case OPENFOLDER = 2; // SDL_FILEDIALOG_OPENFOLDER
}
