<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_FlashOperation, mined from the SDL3 headers: ext-sdl3 0.7.0
 * exposes no class constants of its own.
 */
enum SDLFlashOperation: int
{
    case CANCEL = 0; // SDL_FLASH_CANCEL
    case BRIEFLY = 1; // SDL_FLASH_BRIEFLY
    case UNTIL_FOCUSED = 2; // SDL_FLASH_UNTIL_FOCUSED
}
