<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_FlipMode, mined from the SDL3 headers: ext-sdl3 0.7.0
 * exposes no class constants of its own.
 */
enum SDLFlipMode: int
{
    case NONE = 0; // SDL_FLIP_NONE
    case HORIZONTAL = 1; // SDL_FLIP_HORIZONTAL
    case VERTICAL = 2; // SDL_FLIP_VERTICAL
    case HORIZONTAL_AND_VERTICAL = 3; // SDL_FLIP_HORIZONTAL_AND_VERTICAL
}
