<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUTextureType, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUTextureType: int
{
    case GPU_TEXTURETYPE_2D = 0; // SDL_GPU_TEXTURETYPE_2D
    case GPU_TEXTURETYPE_2D_ARRAY = 1; // SDL_GPU_TEXTURETYPE_2D_ARRAY
    case GPU_TEXTURETYPE_3D = 2; // SDL_GPU_TEXTURETYPE_3D
    case CUBE = 3; // SDL_GPU_TEXTURETYPE_CUBE
    case CUBE_ARRAY = 4; // SDL_GPU_TEXTURETYPE_CUBE_ARRAY
}
