<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUIndexElementSize, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUIndexElementSize: int
{
    case GPU_INDEXELEMENTSIZE_16BIT = 0; // SDL_GPU_INDEXELEMENTSIZE_16BIT
    case GPU_INDEXELEMENTSIZE_32BIT = 1; // SDL_GPU_INDEXELEMENTSIZE_32BIT
}
