<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUBufferUsageFlags, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 *
 * This family is a bitmask. Parameters that take it stay `int` in the
 * projection, because PHP enum cases cannot be OR'd together; pass
 * `SomeCase->value | OtherCase->value`.
 */
enum SDLGPUBufferUsageFlags: int
{
    case VERTEX = 1; // SDL_GPU_BUFFERUSAGE_VERTEX
    case INDEX = 2; // SDL_GPU_BUFFERUSAGE_INDEX
    case INDIRECT = 4; // SDL_GPU_BUFFERUSAGE_INDIRECT
    case GRAPHICS_STORAGE_READ = 8; // SDL_GPU_BUFFERUSAGE_GRAPHICS_STORAGE_READ
    case COMPUTE_STORAGE_READ = 16; // SDL_GPU_BUFFERUSAGE_COMPUTE_STORAGE_READ
    case COMPUTE_STORAGE_WRITE = 32; // SDL_GPU_BUFFERUSAGE_COMPUTE_STORAGE_WRITE
}
