<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUPresentMode, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUPresentMode: int
{
    case VSYNC = 0; // SDL_GPU_PRESENTMODE_VSYNC
    case IMMEDIATE = 1; // SDL_GPU_PRESENTMODE_IMMEDIATE
    case MAILBOX = 2; // SDL_GPU_PRESENTMODE_MAILBOX
}
