<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUSampleCount, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUSampleCount: int
{
    case GPU_SAMPLECOUNT_1 = 0; // SDL_GPU_SAMPLECOUNT_1
    case GPU_SAMPLECOUNT_2 = 1; // SDL_GPU_SAMPLECOUNT_2
    case GPU_SAMPLECOUNT_4 = 2; // SDL_GPU_SAMPLECOUNT_4
    case GPU_SAMPLECOUNT_8 = 3; // SDL_GPU_SAMPLECOUNT_8
}
