<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GamepadAxis, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGamepadAxis: int
{
    case INVALID = -1; // SDL_GAMEPAD_AXIS_INVALID
    case LEFTX = 0; // SDL_GAMEPAD_AXIS_LEFTX
    case LEFTY = 1; // SDL_GAMEPAD_AXIS_LEFTY
    case RIGHTX = 2; // SDL_GAMEPAD_AXIS_RIGHTX
    case RIGHTY = 3; // SDL_GAMEPAD_AXIS_RIGHTY
    case LEFT_TRIGGER = 4; // SDL_GAMEPAD_AXIS_LEFT_TRIGGER
    case RIGHT_TRIGGER = 5; // SDL_GAMEPAD_AXIS_RIGHT_TRIGGER
    case COUNT = 6; // SDL_GAMEPAD_AXIS_COUNT
}
