<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUFillMode, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUFillMode: int
{
    case FILL = 0; // SDL_GPU_FILLMODE_FILL
    case LINE = 1; // SDL_GPU_FILLMODE_LINE
}
