<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUTextureUsageFlags, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 *
 * This family is a bitmask. Parameters that take it stay `int` in the
 * projection, because PHP enum cases cannot be OR'd together; pass
 * `SomeCase->value | OtherCase->value`.
 */
enum SDLGPUTextureUsageFlags: int
{
    case SAMPLER = 1; // SDL_GPU_TEXTUREUSAGE_SAMPLER
    case COLOR_TARGET = 2; // SDL_GPU_TEXTUREUSAGE_COLOR_TARGET
    case DEPTH_STENCIL_TARGET = 4; // SDL_GPU_TEXTUREUSAGE_DEPTH_STENCIL_TARGET
    case GRAPHICS_STORAGE_READ = 8; // SDL_GPU_TEXTUREUSAGE_GRAPHICS_STORAGE_READ
    case COMPUTE_STORAGE_READ = 16; // SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_READ
    case COMPUTE_STORAGE_WRITE = 32; // SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_WRITE
    case COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE = 64; // SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE
}
