<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUVertexInputRate, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUVertexInputRate: int
{
    case VERTEX = 0; // SDL_GPU_VERTEXINPUTRATE_VERTEX
    case INSTANCE = 1; // SDL_GPU_VERTEXINPUTRATE_INSTANCE
}
