<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUFrontFace, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUFrontFace: int
{
    case COUNTER_CLOCKWISE = 0; // SDL_GPU_FRONTFACE_COUNTER_CLOCKWISE
    case CLOCKWISE = 1; // SDL_GPU_FRONTFACE_CLOCKWISE
}
