<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GamepadType, mined from the SDL3 headers: ext-sdl3 0.7.0
 * exposes no class constants of its own.
 */
enum SDLGamepadType: int
{
    case UNKNOWN = 0; // SDL_GAMEPAD_TYPE_UNKNOWN
    case STANDARD = 1; // SDL_GAMEPAD_TYPE_STANDARD
    case XBOX360 = 2; // SDL_GAMEPAD_TYPE_XBOX360
    case XBOXONE = 3; // SDL_GAMEPAD_TYPE_XBOXONE
    case PS3 = 4; // SDL_GAMEPAD_TYPE_PS3
    case PS4 = 5; // SDL_GAMEPAD_TYPE_PS4
    case PS5 = 6; // SDL_GAMEPAD_TYPE_PS5
    case NINTENDO_SWITCH_PRO = 7; // SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_PRO
    case NINTENDO_SWITCH_JOYCON_LEFT = 8; // SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_LEFT
    case NINTENDO_SWITCH_JOYCON_RIGHT = 9; // SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_RIGHT
    case NINTENDO_SWITCH_JOYCON_PAIR = 10; // SDL_GAMEPAD_TYPE_NINTENDO_SWITCH_JOYCON_PAIR
    case GAMECUBE = 11; // SDL_GAMEPAD_TYPE_GAMECUBE
    case COUNT = 12; // SDL_GAMEPAD_TYPE_COUNT
}
