<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUSwapchainComposition, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUSwapchainComposition: int
{
    case SDR = 0; // SDL_GPU_SWAPCHAINCOMPOSITION_SDR
    case SDR_LINEAR = 1; // SDL_GPU_SWAPCHAINCOMPOSITION_SDR_LINEAR
    case HDR_EXTENDED_LINEAR = 2; // SDL_GPU_SWAPCHAINCOMPOSITION_HDR_EXTENDED_LINEAR
    case HDR10_ST2084 = 3; // SDL_GPU_SWAPCHAINCOMPOSITION_HDR10_ST2084
}
