<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUBlendOp, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUBlendOp: int
{
    case INVALID = 0; // SDL_GPU_BLENDOP_INVALID
    case ADD = 1; // SDL_GPU_BLENDOP_ADD
    case SUBTRACT = 2; // SDL_GPU_BLENDOP_SUBTRACT
    case REVERSE_SUBTRACT = 3; // SDL_GPU_BLENDOP_REVERSE_SUBTRACT
    case MIN = 4; // SDL_GPU_BLENDOP_MIN
    case MAX = 5; // SDL_GPU_BLENDOP_MAX
}
