<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUPrimitiveType, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUPrimitiveType: int
{
    case TRIANGLELIST = 0; // SDL_GPU_PRIMITIVETYPE_TRIANGLELIST
    case TRIANGLESTRIP = 1; // SDL_GPU_PRIMITIVETYPE_TRIANGLESTRIP
    case LINELIST = 2; // SDL_GPU_PRIMITIVETYPE_LINELIST
    case LINESTRIP = 3; // SDL_GPU_PRIMITIVETYPE_LINESTRIP
    case POINTLIST = 4; // SDL_GPU_PRIMITIVETYPE_POINTLIST
}
