<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUShaderFormat, mined from the SDL3 headers: ext-sdl3 0.7.0
 * exposes no class constants of its own.
 *
 * This family is a bitmask. Parameters that take it stay `int` in the
 * projection, because PHP enum cases cannot be OR'd together; pass
 * `SomeCase->value | OtherCase->value`.
 */
enum SDLGPUShaderFormat: int
{
    case INVALID = 0; // SDL_GPU_SHADERFORMAT_INVALID
    case PRIVATE = 1; // SDL_GPU_SHADERFORMAT_PRIVATE
    case SPIRV = 2; // SDL_GPU_SHADERFORMAT_SPIRV
    case DXBC = 4; // SDL_GPU_SHADERFORMAT_DXBC
    case DXIL = 8; // SDL_GPU_SHADERFORMAT_DXIL
    case MSL = 16; // SDL_GPU_SHADERFORMAT_MSL
    case METALLIB = 32; // SDL_GPU_SHADERFORMAT_METALLIB
}
