<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUCullMode, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUCullMode: int
{
    case NONE = 0; // SDL_GPU_CULLMODE_NONE
    case FRONT = 1; // SDL_GPU_CULLMODE_FRONT
    case BACK = 2; // SDL_GPU_CULLMODE_BACK
}
