<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPULoadOp, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPULoadOp: int
{
    case LOAD = 0; // SDL_GPU_LOADOP_LOAD
    case CLEAR = 1; // SDL_GPU_LOADOP_CLEAR
    case DONT_CARE = 2; // SDL_GPU_LOADOP_DONT_CARE
}
