<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUStoreOp, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUStoreOp: int
{
    case STORE = 0; // SDL_GPU_STOREOP_STORE
    case DONT_CARE = 1; // SDL_GPU_STOREOP_DONT_CARE
    case RESOLVE = 2; // SDL_GPU_STOREOP_RESOLVE
    case RESOLVE_AND_STORE = 3; // SDL_GPU_STOREOP_RESOLVE_AND_STORE
}
