<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GPUSamplerAddressMode, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGPUSamplerAddressMode: int
{
    case REPEAT = 0; // SDL_GPU_SAMPLERADDRESSMODE_REPEAT
    case MIRRORED_REPEAT = 1; // SDL_GPU_SAMPLERADDRESSMODE_MIRRORED_REPEAT
    case CLAMP_TO_EDGE = 2; // SDL_GPU_SAMPLERADDRESSMODE_CLAMP_TO_EDGE
}
