<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_GamepadButtonLabel, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLGamepadButtonLabel: int
{
    case UNKNOWN = 0; // SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN
    case A = 1; // SDL_GAMEPAD_BUTTON_LABEL_A
    case B = 2; // SDL_GAMEPAD_BUTTON_LABEL_B
    case X = 3; // SDL_GAMEPAD_BUTTON_LABEL_X
    case Y = 4; // SDL_GAMEPAD_BUTTON_LABEL_Y
    case CROSS = 5; // SDL_GAMEPAD_BUTTON_LABEL_CROSS
    case CIRCLE = 6; // SDL_GAMEPAD_BUTTON_LABEL_CIRCLE
    case SQUARE = 7; // SDL_GAMEPAD_BUTTON_LABEL_SQUARE
    case TRIANGLE = 8; // SDL_GAMEPAD_BUTTON_LABEL_TRIANGLE
}
