<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_InitFlags, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 *
 * This family is a bitmask. Parameters that take it stay `int` in the
 * projection, because PHP enum cases cannot be OR'd together; pass
 * `SomeCase->value | OtherCase->value`.
 */
enum SDLInitFlags: int
{
    case AUDIO = 16; // SDL_INIT_AUDIO
    case VIDEO = 32; // SDL_INIT_VIDEO
    case JOYSTICK = 512; // SDL_INIT_JOYSTICK
    case HAPTIC = 4096; // SDL_INIT_HAPTIC
    case GAMEPAD = 8192; // SDL_INIT_GAMEPAD
    case EVENTS = 16384; // SDL_INIT_EVENTS
    case SENSOR = 32768; // SDL_INIT_SENSOR
    case CAMERA = 65536; // SDL_INIT_CAMERA
}
