<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_JoystickType, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLJoystickType: int
{
    case UNKNOWN = 0; // SDL_JOYSTICK_TYPE_UNKNOWN
    case GAMEPAD = 1; // SDL_JOYSTICK_TYPE_GAMEPAD
    case WHEEL = 2; // SDL_JOYSTICK_TYPE_WHEEL
    case ARCADE_STICK = 3; // SDL_JOYSTICK_TYPE_ARCADE_STICK
    case FLIGHT_STICK = 4; // SDL_JOYSTICK_TYPE_FLIGHT_STICK
    case DANCE_PAD = 5; // SDL_JOYSTICK_TYPE_DANCE_PAD
    case GUITAR = 6; // SDL_JOYSTICK_TYPE_GUITAR
    case DRUM_KIT = 7; // SDL_JOYSTICK_TYPE_DRUM_KIT
    case ARCADE_PAD = 8; // SDL_JOYSTICK_TYPE_ARCADE_PAD
    case THROTTLE = 9; // SDL_JOYSTICK_TYPE_THROTTLE
    case COUNT = 10; // SDL_JOYSTICK_TYPE_COUNT
}
