<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_JoystickConnectionState, mined from the SDL3 headers: ext-sdl3 0.7.0
 * exposes no class constants of its own.
 */
enum SDLJoystickConnectionState: int
{
    case INVALID = -1; // SDL_JOYSTICK_CONNECTION_INVALID
    case UNKNOWN = 0; // SDL_JOYSTICK_CONNECTION_UNKNOWN
    case WIRED = 1; // SDL_JOYSTICK_CONNECTION_WIRED
    case WIRELESS = 2; // SDL_JOYSTICK_CONNECTION_WIRELESS
}
