<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_Keymod, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 *
 * This family is a bitmask. Parameters that take it stay `int` in the
 * projection, because PHP enum cases cannot be OR'd together; pass
 * `SomeCase->value | OtherCase->value`.
 */
enum SDLKeymod: int
{
    case NONE = 0; // SDL_KMOD_NONE
    case LSHIFT = 1; // SDL_KMOD_LSHIFT
    case RSHIFT = 2; // SDL_KMOD_RSHIFT
    case LEVEL5 = 4; // SDL_KMOD_LEVEL5
    case LCTRL = 64; // SDL_KMOD_LCTRL
    case RCTRL = 128; // SDL_KMOD_RCTRL
    case LALT = 256; // SDL_KMOD_LALT
    case RALT = 512; // SDL_KMOD_RALT
    case LGUI = 1024; // SDL_KMOD_LGUI
    case RGUI = 2048; // SDL_KMOD_RGUI
    case NUM = 4096; // SDL_KMOD_NUM
    case CAPS = 8192; // SDL_KMOD_CAPS
    case MODE = 16384; // SDL_KMOD_MODE
    case SCROLL = 32768; // SDL_KMOD_SCROLL
    case CTRL = 192; // SDL_KMOD_CTRL
    case SHIFT = 3; // SDL_KMOD_SHIFT
    case ALT = 768; // SDL_KMOD_ALT
    case GUI = 3072; // SDL_KMOD_GUI
}
