<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_PropertyType, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLPropertyType: int
{
    case INVALID = 0; // SDL_PROPERTY_TYPE_INVALID
    case POINTER = 1; // SDL_PROPERTY_TYPE_POINTER
    case STRING = 2; // SDL_PROPERTY_TYPE_STRING
    case NUMBER = 3; // SDL_PROPERTY_TYPE_NUMBER
    case FLOAT = 4; // SDL_PROPERTY_TYPE_FLOAT
    case BOOLEAN = 5; // SDL_PROPERTY_TYPE_BOOLEAN
}
