<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_ProgressState, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLProgressState: int
{
    case INVALID = -1; // SDL_PROGRESS_STATE_INVALID
    case NONE = 0; // SDL_PROGRESS_STATE_NONE
    case INDETERMINATE = 1; // SDL_PROGRESS_STATE_INDETERMINATE
    case NORMAL = 2; // SDL_PROGRESS_STATE_NORMAL
    case PAUSED = 3; // SDL_PROGRESS_STATE_PAUSED
    case ERROR = 4; // SDL_PROGRESS_STATE_ERROR
}
