<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_RendererLogicalPresentation, mined from the SDL3 headers: ext-sdl3 0.7.0
 * exposes no class constants of its own.
 */
enum SDLRendererLogicalPresentation: int
{
    case DISABLED = 0; // SDL_LOGICAL_PRESENTATION_DISABLED
    case STRETCH = 1; // SDL_LOGICAL_PRESENTATION_STRETCH
    case LETTERBOX = 2; // SDL_LOGICAL_PRESENTATION_LETTERBOX
    case OVERSCAN = 3; // SDL_LOGICAL_PRESENTATION_OVERSCAN
    case INTEGER_SCALE = 4; // SDL_LOGICAL_PRESENTATION_INTEGER_SCALE
}
