<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_ScaleMode, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLScaleMode: int
{
    case INVALID = -1; // SDL_SCALEMODE_INVALID
    case NEAREST = 0; // SDL_SCALEMODE_NEAREST
    case LINEAR = 1; // SDL_SCALEMODE_LINEAR
    case PIXELART = 2; // SDL_SCALEMODE_PIXELART
}
