<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_SystemTheme, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLSystemTheme: int
{
    case UNKNOWN = 0; // SDL_SYSTEM_THEME_UNKNOWN
    case LIGHT = 1; // SDL_SYSTEM_THEME_LIGHT
    case DARK = 2; // SDL_SYSTEM_THEME_DARK
}
