<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_SensorType, mined from the SDL3 headers: ext-sdl3 0.7.0
 * exposes no class constants of its own.
 */
enum SDLSensorType: int
{
    case INVALID = -1; // SDL_SENSOR_INVALID
    case UNKNOWN = 0; // SDL_SENSOR_UNKNOWN
    case ACCEL = 1; // SDL_SENSOR_ACCEL
    case GYRO = 2; // SDL_SENSOR_GYRO
    case ACCEL_L = 3; // SDL_SENSOR_ACCEL_L
    case GYRO_L = 4; // SDL_SENSOR_GYRO_L
    case ACCEL_R = 5; // SDL_SENSOR_ACCEL_R
    case GYRO_R = 6; // SDL_SENSOR_GYRO_R
    case COUNT = 7; // SDL_SENSOR_COUNT
}
