<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_SystemCursor, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLSystemCursor: int
{
    case DEFAULT = 0; // SDL_SYSTEM_CURSOR_DEFAULT
    case TEXT = 1; // SDL_SYSTEM_CURSOR_TEXT
    case WAIT = 2; // SDL_SYSTEM_CURSOR_WAIT
    case CROSSHAIR = 3; // SDL_SYSTEM_CURSOR_CROSSHAIR
    case PROGRESS = 4; // SDL_SYSTEM_CURSOR_PROGRESS
    case NWSE_RESIZE = 5; // SDL_SYSTEM_CURSOR_NWSE_RESIZE
    case NESW_RESIZE = 6; // SDL_SYSTEM_CURSOR_NESW_RESIZE
    case EW_RESIZE = 7; // SDL_SYSTEM_CURSOR_EW_RESIZE
    case NS_RESIZE = 8; // SDL_SYSTEM_CURSOR_NS_RESIZE
    case MOVE = 9; // SDL_SYSTEM_CURSOR_MOVE
    case NOT_ALLOWED = 10; // SDL_SYSTEM_CURSOR_NOT_ALLOWED
    case POINTER = 11; // SDL_SYSTEM_CURSOR_POINTER
    case NW_RESIZE = 12; // SDL_SYSTEM_CURSOR_NW_RESIZE
    case N_RESIZE = 13; // SDL_SYSTEM_CURSOR_N_RESIZE
    case NE_RESIZE = 14; // SDL_SYSTEM_CURSOR_NE_RESIZE
    case E_RESIZE = 15; // SDL_SYSTEM_CURSOR_E_RESIZE
    case SE_RESIZE = 16; // SDL_SYSTEM_CURSOR_SE_RESIZE
    case S_RESIZE = 17; // SDL_SYSTEM_CURSOR_S_RESIZE
    case SW_RESIZE = 18; // SDL_SYSTEM_CURSOR_SW_RESIZE
    case W_RESIZE = 19; // SDL_SYSTEM_CURSOR_W_RESIZE
    case COUNT = 20; // SDL_SYSTEM_CURSOR_COUNT
}
