<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_Sandbox, mined from the SDL3 headers: ext-sdl3 0.7.0
 * exposes no class constants of its own.
 */
enum SDLSandbox: int
{
    case NONE = 0; // SDL_SANDBOX_NONE
    case UNKNOWN_CONTAINER = 1; // SDL_SANDBOX_UNKNOWN_CONTAINER
    case FLATPAK = 2; // SDL_SANDBOX_FLATPAK
    case SNAP = 3; // SDL_SANDBOX_SNAP
    case MACOS = 4; // SDL_SANDBOX_MACOS
}
