<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_TextureAddressMode, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 */
enum SDLTextureAddressMode: int
{
    case INVALID = -1; // SDL_TEXTURE_ADDRESS_INVALID
    case AUTO = 0; // SDL_TEXTURE_ADDRESS_AUTO
    case CLAMP = 1; // SDL_TEXTURE_ADDRESS_CLAMP
    case WRAP = 2; // SDL_TEXTURE_ADDRESS_WRAP
}
