<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_TextureAccess, mined from the SDL3 headers: ext-sdl3 0.7.0
 * exposes no class constants of its own.
 */
enum SDLTextureAccess: int
{
    case STATIC = 0; // SDL_TEXTUREACCESS_STATIC
    case STREAMING = 1; // SDL_TEXTUREACCESS_STREAMING
    case TARGET = 2; // SDL_TEXTUREACCESS_TARGET
}
