<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Enums;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * SDL_WindowFlags, mined from the SDL3 headers: ext-sdl3 0.8.0
 * exposes no class constants of its own.
 *
 * This family is a bitmask. Parameters that take it stay `int` in the
 * projection, because PHP enum cases cannot be OR'd together; pass
 * `SomeCase->value | OtherCase->value`.
 */
enum SDLWindowFlags: int
{
    case FULLSCREEN = 1; // SDL_WINDOW_FULLSCREEN
    case OPENGL = 2; // SDL_WINDOW_OPENGL
    case OCCLUDED = 4; // SDL_WINDOW_OCCLUDED
    case HIDDEN = 8; // SDL_WINDOW_HIDDEN
    case BORDERLESS = 16; // SDL_WINDOW_BORDERLESS
    case RESIZABLE = 32; // SDL_WINDOW_RESIZABLE
    case MINIMIZED = 64; // SDL_WINDOW_MINIMIZED
    case MAXIMIZED = 128; // SDL_WINDOW_MAXIMIZED
    case MOUSE_GRABBED = 256; // SDL_WINDOW_MOUSE_GRABBED
    case INPUT_FOCUS = 512; // SDL_WINDOW_INPUT_FOCUS
    case MOUSE_FOCUS = 1024; // SDL_WINDOW_MOUSE_FOCUS
    case EXTERNAL = 2048; // SDL_WINDOW_EXTERNAL
    case MODAL = 4096; // SDL_WINDOW_MODAL
    case HIGH_PIXEL_DENSITY = 8192; // SDL_WINDOW_HIGH_PIXEL_DENSITY
    case MOUSE_CAPTURE = 16384; // SDL_WINDOW_MOUSE_CAPTURE
    case MOUSE_RELATIVE_MODE = 32768; // SDL_WINDOW_MOUSE_RELATIVE_MODE
    case ALWAYS_ON_TOP = 65536; // SDL_WINDOW_ALWAYS_ON_TOP
    case UTILITY = 131072; // SDL_WINDOW_UTILITY
    case TOOLTIP = 262144; // SDL_WINDOW_TOOLTIP
    case POPUP_MENU = 524288; // SDL_WINDOW_POPUP_MENU
    case KEYBOARD_GRABBED = 1048576; // SDL_WINDOW_KEYBOARD_GRABBED
    case FILL_DOCUMENT = 2097152; // SDL_WINDOW_FILL_DOCUMENT
    case VULKAN = 268435456; // SDL_WINDOW_VULKAN
    case METAL = 536870912; // SDL_WINDOW_METAL
    case TRANSPARENT = 1073741824; // SDL_WINDOW_TRANSPARENT
    case NOT_FOCUSABLE = 2147483648; // SDL_WINDOW_NOT_FOCUSABLE
}
