<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Surface;

use Jovian\Bindings\Sdl3\Enums\SDLColorspace;
use Jovian\Bindings\Sdl3\Enums\SDLFlipMode;
use Jovian\Bindings\Sdl3\Enums\SDLPixelFormat;
use Jovian\Bindings\Sdl3\Enums\SDLScaleMode;
use Sdl3\SDL\Surface\SDLSurface as ExtSDLSurface;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Surface\SDLSurface
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLSurface
{
    /**
     * SDL_AddSurfaceAlternateImage().
     */
    public static function SDLAddSurfaceAlternateImage(int $surface, int $image): bool
    {
        return ExtSDLSurface::SDLAddSurfaceAlternateImage($surface, $image);
    }

    /**
     * SDL_BlitSurface().
     */
    public static function SDLBlitSurface(int $src, int $dst, mixed $srcrect = null, mixed $dstrect = null): bool
    {
        return ExtSDLSurface::SDLBlitSurface(...array_slice([$src, $dst, $srcrect, $dstrect], 0, func_num_args()));
    }

    /**
     * SDL_BlitSurface9Grid().
     */
    public static function SDLBlitSurface9Grid(int $src, int $dst, int $left_width, int $right_width, int $top_height, int $bottom_height, float $scale, SDLScaleMode|int $scaleMode, mixed $srcrect = null, mixed $dstrect = null): bool
    {
        return ExtSDLSurface::SDLBlitSurface9Grid(...array_slice([$src, $dst, $left_width, $right_width, $top_height, $bottom_height, $scale, $scaleMode instanceof \BackedEnum ? $scaleMode->value : $scaleMode, $srcrect, $dstrect], 0, func_num_args()));
    }

    /**
     * SDL_BlitSurfaceScaled().
     */
    public static function SDLBlitSurfaceScaled(int $src, int $dst, mixed $srcrect = null, mixed $dstrect = null, SDLScaleMode|int $scaleMode = null): bool
    {
        return ExtSDLSurface::SDLBlitSurfaceScaled(...array_slice([$src, $dst, $srcrect, $dstrect, $scaleMode instanceof \BackedEnum ? $scaleMode->value : $scaleMode], 0, func_num_args()));
    }

    /**
     * SDL_BlitSurfaceTiled().
     */
    public static function SDLBlitSurfaceTiled(int $src, int $dst, mixed $srcrect = null, mixed $dstrect = null): bool
    {
        return ExtSDLSurface::SDLBlitSurfaceTiled(...array_slice([$src, $dst, $srcrect, $dstrect], 0, func_num_args()));
    }

    /**
     * SDL_BlitSurfaceTiledWithScale().
     */
    public static function SDLBlitSurfaceTiledWithScale(int $src, int $dst, float $scale, SDLScaleMode|int $scaleMode, mixed $srcrect = null, mixed $dstrect = null): bool
    {
        return ExtSDLSurface::SDLBlitSurfaceTiledWithScale(...array_slice([$src, $dst, $scale, $scaleMode instanceof \BackedEnum ? $scaleMode->value : $scaleMode, $srcrect, $dstrect], 0, func_num_args()));
    }

    /**
     * SDL_BlitSurfaceUnchecked().
     */
    public static function SDLBlitSurfaceUnchecked(int $src, array $srcrect, int $dst, array $dstrect): bool
    {
        return ExtSDLSurface::SDLBlitSurfaceUnchecked($src, $srcrect, $dst, $dstrect);
    }

    /**
     * SDL_BlitSurfaceUncheckedScaled().
     */
    public static function SDLBlitSurfaceUncheckedScaled(int $src, array $srcrect, int $dst, array $dstrect, SDLScaleMode|int $scaleMode): bool
    {
        return ExtSDLSurface::SDLBlitSurfaceUncheckedScaled($src, $srcrect, $dst, $dstrect, $scaleMode instanceof \BackedEnum ? $scaleMode->value : $scaleMode);
    }

    /**
     * SDL_ClearSurface().
     */
    public static function SDLClearSurface(int $surface, float $r, float $g, float $b, float $a): bool
    {
        return ExtSDLSurface::SDLClearSurface($surface, $r, $g, $b, $a);
    }

    /**
     * SDL_ConvertPixels().
     */
    public static function SDLConvertPixels(int $width, int $height, SDLPixelFormat|int $src_format, string $src, int $src_pitch, SDLPixelFormat|int $dst_format, int $dst_pitch): string
    {
        return ExtSDLSurface::SDLConvertPixels($width, $height, $src_format instanceof \BackedEnum ? $src_format->value : $src_format, $src, $src_pitch, $dst_format instanceof \BackedEnum ? $dst_format->value : $dst_format, $dst_pitch);
    }

    /**
     * SDL_ConvertPixelsAndColorspace().
     */
    public static function SDLConvertPixelsAndColorspace(int $width, int $height, SDLPixelFormat|int $src_format, SDLColorspace|int $src_colorspace, int $src_properties, string $src, int $src_pitch, SDLPixelFormat|int $dst_format, SDLColorspace|int $dst_colorspace, int $dst_properties, int $dst_pitch): string
    {
        return ExtSDLSurface::SDLConvertPixelsAndColorspace($width, $height, $src_format instanceof \BackedEnum ? $src_format->value : $src_format, $src_colorspace instanceof \BackedEnum ? $src_colorspace->value : $src_colorspace, $src_properties, $src, $src_pitch, $dst_format instanceof \BackedEnum ? $dst_format->value : $dst_format, $dst_colorspace instanceof \BackedEnum ? $dst_colorspace->value : $dst_colorspace, $dst_properties, $dst_pitch);
    }

    /**
     * SDL_ConvertSurface().
     */
    public static function SDLConvertSurface(int $surface, SDLPixelFormat|int $format): array
    {
        return ExtSDLSurface::SDLConvertSurface($surface, $format instanceof \BackedEnum ? $format->value : $format);
    }

    /**
     * SDL_ConvertSurfaceAndColorspace().
     */
    public static function SDLConvertSurfaceAndColorspace(int $surface, SDLPixelFormat|int $format, mixed $palette = null, SDLColorspace|int $colorspace = null, int $props = 0): array
    {
        return ExtSDLSurface::SDLConvertSurfaceAndColorspace(...array_slice([$surface, $format instanceof \BackedEnum ? $format->value : $format, $palette, $colorspace instanceof \BackedEnum ? $colorspace->value : $colorspace, $props], 0, func_num_args()));
    }

    /**
     * SDL_CreatePalette().
     */
    public static function SDLCreatePalette(int $ncolors): array
    {
        return ExtSDLSurface::SDLCreatePalette($ncolors);
    }

    /**
     * SDL_CreateSurface().
     */
    public static function SDLCreateSurface(int $width, int $height, SDLPixelFormat|int $format): array
    {
        return ExtSDLSurface::SDLCreateSurface($width, $height, $format instanceof \BackedEnum ? $format->value : $format);
    }

    /**
     * SDL_CreateSurfaceFrom().
     */
    public static function SDLCreateSurfaceFrom(int $width, int $height, SDLPixelFormat|int $format, string $pixels, int $pitch): array
    {
        return ExtSDLSurface::SDLCreateSurfaceFrom($width, $height, $format instanceof \BackedEnum ? $format->value : $format, $pixels, $pitch);
    }

    /**
     * SDL_CreateSurfacePalette().
     */
    public static function SDLCreateSurfacePalette(int $surface): array
    {
        return ExtSDLSurface::SDLCreateSurfacePalette($surface);
    }

    /**
     * SDL_DestroyPalette().
     */
    public static function SDLDestroyPalette(int $palette): void
    {
        ExtSDLSurface::SDLDestroyPalette($palette);
    }

    /**
     * SDL_DestroySurface().
     */
    public static function SDLDestroySurface(int $surface): void
    {
        ExtSDLSurface::SDLDestroySurface($surface);
    }

    /**
     * SDL_DuplicateSurface().
     */
    public static function SDLDuplicateSurface(int $surface): array
    {
        return ExtSDLSurface::SDLDuplicateSurface($surface);
    }

    /**
     * SDL_FillSurfaceRect().
     */
    public static function SDLFillSurfaceRect(int $surface, int $color, mixed $rect = null): bool
    {
        return ExtSDLSurface::SDLFillSurfaceRect(...array_slice([$surface, $color, $rect], 0, func_num_args()));
    }

    /**
     * SDL_FillSurfaceRects().
     */
    public static function SDLFillSurfaceRects(int $dst, array $rects, int $color): bool
    {
        return ExtSDLSurface::SDLFillSurfaceRects($dst, $rects, $color);
    }

    /**
     * SDL_FlipSurface().
     */
    public static function SDLFlipSurface(int $surface, SDLFlipMode|int $flip): bool
    {
        return ExtSDLSurface::SDLFlipSurface($surface, $flip instanceof \BackedEnum ? $flip->value : $flip);
    }

    /**
     * SDL_GetMasksForPixelFormat().
     */
    public static function SDLGetMasksForPixelFormat(SDLPixelFormat|int $format): array
    {
        return ExtSDLSurface::SDLGetMasksForPixelFormat($format instanceof \BackedEnum ? $format->value : $format);
    }

    /**
     * SDL_GetPixelFormatForMasks().
     */
    public static function SDLGetPixelFormatForMasks(int $bpp, int $rmask, int $gmask, int $bmask, int $amask): SDLPixelFormat|int
    {
        return ExtSDLSurface::SDLGetPixelFormatForMasks($bpp, $rmask, $gmask, $bmask, $amask);
    }

    /**
     * SDL_GetPixelFormatName().
     */
    public static function SDLGetPixelFormatName(SDLPixelFormat|int $format): string
    {
        return ExtSDLSurface::SDLGetPixelFormatName($format instanceof \BackedEnum ? $format->value : $format);
    }

    /**
     * SDL_GetRGB().
     */
    public static function SDLGetRGB(int $pixel, int $format_ptr, mixed $palette_ptr = null): array
    {
        return ExtSDLSurface::SDLGetRGB(...array_slice([$pixel, $format_ptr, $palette_ptr], 0, func_num_args()));
    }

    /**
     * SDL_GetSurfaceAlphaMod().
     */
    public static function SDLGetSurfaceAlphaMod(int $surface): array
    {
        return ExtSDLSurface::SDLGetSurfaceAlphaMod($surface);
    }

    /**
     * SDL_GetSurfaceBlendMode().
     */
    public static function SDLGetSurfaceBlendMode(int $surface): array
    {
        return ExtSDLSurface::SDLGetSurfaceBlendMode($surface);
    }

    /**
     * SDL_GetSurfaceClipRect().
     */
    public static function SDLGetSurfaceClipRect(int $surface): array
    {
        return ExtSDLSurface::SDLGetSurfaceClipRect($surface);
    }

    /**
     * SDL_GetSurfaceColorKey().
     */
    public static function SDLGetSurfaceColorKey(int $surface): array
    {
        return ExtSDLSurface::SDLGetSurfaceColorKey($surface);
    }

    /**
     * SDL_GetSurfaceColorMod().
     */
    public static function SDLGetSurfaceColorMod(int $surface): array
    {
        return ExtSDLSurface::SDLGetSurfaceColorMod($surface);
    }

    /**
     * SDL_GetSurfaceColorspace().
     */
    public static function SDLGetSurfaceColorspace(int $surface): SDLColorspace|int
    {
        return ExtSDLSurface::SDLGetSurfaceColorspace($surface);
    }

    /**
     * SDL_GetSurfaceImages().
     */
    public static function SDLGetSurfaceImages(int $surface): array
    {
        return ExtSDLSurface::SDLGetSurfaceImages($surface);
    }

    /**
     * SDL_GetSurfacePalette().
     */
    public static function SDLGetSurfacePalette(int $surface): array
    {
        return ExtSDLSurface::SDLGetSurfacePalette($surface);
    }

    /**
     * SDL_GetSurfaceProperties().
     */
    public static function SDLGetSurfaceProperties(int $surface): int
    {
        return ExtSDLSurface::SDLGetSurfaceProperties($surface);
    }

    /**
     * SDL_LoadBMP().
     */
    public static function SDLLoadBMP(string $file): array
    {
        return ExtSDLSurface::SDLLoadBMP($file);
    }

    /**
     * SDL_LoadPNG().
     */
    public static function SDLLoadPNG(string $file): array
    {
        return ExtSDLSurface::SDLLoadPNG($file);
    }

    /**
     * SDL_LoadSurface().
     */
    public static function SDLLoadSurface(string $file): array
    {
        return ExtSDLSurface::SDLLoadSurface($file);
    }

    /**
     * SDL_LockSurface().
     */
    public static function SDLLockSurface(int $surface): bool
    {
        return ExtSDLSurface::SDLLockSurface($surface);
    }

    /**
     * SDL_MapRGB().
     */
    public static function SDLMapRGB(int $format, int $palette, int $r, int $g, int $b): int
    {
        return ExtSDLSurface::SDLMapRGB($format, $palette, $r, $g, $b);
    }

    /**
     * SDL_MapSurfaceRGB().
     */
    public static function SDLMapSurfaceRGB(int $surface, int $r, int $g, int $b): int
    {
        return ExtSDLSurface::SDLMapSurfaceRGB($surface, $r, $g, $b);
    }

    /**
     * SDL_MapSurfaceRGBA().
     */
    public static function SDLMapSurfaceRGBA(int $surface, int $r, int $g, int $b, int $a): int
    {
        return ExtSDLSurface::SDLMapSurfaceRGBA($surface, $r, $g, $b, $a);
    }

    /**
     * SDL_PremultiplyAlpha().
     */
    public static function SDLPremultiplyAlpha(int $width, int $height, SDLPixelFormat|int $src_format, string $src, int $src_pitch, SDLPixelFormat|int $dst_format, int $dst_pitch, bool $linear): string
    {
        return ExtSDLSurface::SDLPremultiplyAlpha($width, $height, $src_format instanceof \BackedEnum ? $src_format->value : $src_format, $src, $src_pitch, $dst_format instanceof \BackedEnum ? $dst_format->value : $dst_format, $dst_pitch, $linear);
    }

    /**
     * SDL_PremultiplySurfaceAlpha().
     */
    public static function SDLPremultiplySurfaceAlpha(int $surface, bool $linear): bool
    {
        return ExtSDLSurface::SDLPremultiplySurfaceAlpha($surface, $linear);
    }

    /**
     * SDL_ReadSurfacePixel().
     */
    public static function SDLReadSurfacePixel(int $surface, int $x, int $y): array
    {
        return ExtSDLSurface::SDLReadSurfacePixel($surface, $x, $y);
    }

    /**
     * SDL_ReadSurfacePixelFloat().
     */
    public static function SDLReadSurfacePixelFloat(int $surface, int $x, int $y): array
    {
        return ExtSDLSurface::SDLReadSurfacePixelFloat($surface, $x, $y);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadSurfacePixels(int $surface): array
    {
        return ExtSDLSurface::SDLReadSurfacePixels($surface);
    }

    /**
     * SDL_RemoveSurfaceAlternateImages().
     */
    public static function SDLRemoveSurfaceAlternateImages(int $surface): void
    {
        ExtSDLSurface::SDLRemoveSurfaceAlternateImages($surface);
    }

    /**
     * SDL_RotateSurface().
     */
    public static function SDLRotateSurface(int $surface, float $angle): array
    {
        return ExtSDLSurface::SDLRotateSurface($surface, $angle);
    }

    /**
     * SDL_SaveBMP().
     */
    public static function SDLSaveBMP(int $surface, string $file): bool
    {
        return ExtSDLSurface::SDLSaveBMP($surface, $file);
    }

    /**
     * SDL_SavePNG().
     */
    public static function SDLSavePNG(int $surface, string $file): bool
    {
        return ExtSDLSurface::SDLSavePNG($surface, $file);
    }

    /**
     * SDL_ScaleSurface().
     */
    public static function SDLScaleSurface(int $surface, int $width, int $height, SDLScaleMode|int $scaleMode): array
    {
        return ExtSDLSurface::SDLScaleSurface($surface, $width, $height, $scaleMode instanceof \BackedEnum ? $scaleMode->value : $scaleMode);
    }

    /**
     * SDL_SetPaletteColors().
     */
    public static function SDLSetPaletteColors(int $palette, array $colors, int $firstcolor, int $ncolors): bool
    {
        return ExtSDLSurface::SDLSetPaletteColors($palette, $colors, $firstcolor, $ncolors);
    }

    /**
     * SDL_SetSurfaceAlphaMod().
     */
    public static function SDLSetSurfaceAlphaMod(int $surface, int $alpha): bool
    {
        return ExtSDLSurface::SDLSetSurfaceAlphaMod($surface, $alpha);
    }

    /**
     * SDL_SetSurfaceBlendMode().
     *
     * @param int $blendMode SDLBlendMode bitmask; OR the enum cases' values together.
     */
    public static function SDLSetSurfaceBlendMode(int $surface, int $blendMode): bool
    {
        return ExtSDLSurface::SDLSetSurfaceBlendMode($surface, $blendMode);
    }

    /**
     * SDL_SetSurfaceClipRect().
     */
    public static function SDLSetSurfaceClipRect(int $surface, mixed $rect = null): bool
    {
        return ExtSDLSurface::SDLSetSurfaceClipRect(...array_slice([$surface, $rect], 0, func_num_args()));
    }

    /**
     * SDL_SetSurfaceColorKey().
     */
    public static function SDLSetSurfaceColorKey(int $surface, bool $enabled, int $key): bool
    {
        return ExtSDLSurface::SDLSetSurfaceColorKey($surface, $enabled, $key);
    }

    /**
     * SDL_SetSurfaceColorMod().
     */
    public static function SDLSetSurfaceColorMod(int $surface, int $r, int $g, int $b): bool
    {
        return ExtSDLSurface::SDLSetSurfaceColorMod($surface, $r, $g, $b);
    }

    /**
     * SDL_SetSurfaceColorspace().
     */
    public static function SDLSetSurfaceColorspace(int $surface, SDLColorspace|int $colorspace): bool
    {
        return ExtSDLSurface::SDLSetSurfaceColorspace($surface, $colorspace instanceof \BackedEnum ? $colorspace->value : $colorspace);
    }

    /**
     * SDL_SetSurfacePalette().
     */
    public static function SDLSetSurfacePalette(int $surface, int $palette): bool
    {
        return ExtSDLSurface::SDLSetSurfacePalette($surface, $palette);
    }

    /**
     * SDL_SetSurfaceRLE().
     */
    public static function SDLSetSurfaceRLE(int $surface, bool $enabled): bool
    {
        return ExtSDLSurface::SDLSetSurfaceRLE($surface, $enabled);
    }

    /**
     * SDL_StretchSurface().
     */
    public static function SDLStretchSurface(int $src, int $dst, mixed $srcrect = null, mixed $dstrect = null, SDLScaleMode|int $scaleMode = null): bool
    {
        return ExtSDLSurface::SDLStretchSurface(...array_slice([$src, $dst, $srcrect, $dstrect, $scaleMode instanceof \BackedEnum ? $scaleMode->value : $scaleMode], 0, func_num_args()));
    }

    /**
     * SDL_SurfaceHasAlternateImages().
     */
    public static function SDLSurfaceHasAlternateImages(int $surface): bool
    {
        return ExtSDLSurface::SDLSurfaceHasAlternateImages($surface);
    }

    /**
     * SDL_SurfaceHasColorKey().
     */
    public static function SDLSurfaceHasColorKey(int $surface): bool
    {
        return ExtSDLSurface::SDLSurfaceHasColorKey($surface);
    }

    /**
     * SDL_SurfaceHasRLE().
     */
    public static function SDLSurfaceHasRLE(int $surface): bool
    {
        return ExtSDLSurface::SDLSurfaceHasRLE($surface);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLSurfaceToBlackAndWhite(int $surface): void
    {
        ExtSDLSurface::SDLSurfaceToBlackAndWhite($surface);
    }

    /**
     * SDL_UnlockSurface().
     */
    public static function SDLUnlockSurface(int $surface): void
    {
        ExtSDLSurface::SDLUnlockSurface($surface);
    }

    /**
     * SDL_WriteSurfacePixel().
     */
    public static function SDLWriteSurfacePixel(int $surface, int $x, int $y, int $r, int $g, int $b, int $a): bool
    {
        return ExtSDLSurface::SDLWriteSurfacePixel($surface, $x, $y, $r, $g, $b, $a);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLWriteSurfacePixelAt(int $surface, int $x, int $y, int $pixel): bool
    {
        return ExtSDLSurface::SDLWriteSurfacePixelAt($surface, $x, $y, $pixel);
    }

    /**
     * SDL_WriteSurfacePixelFloat().
     */
    public static function SDLWriteSurfacePixelFloat(int $surface, int $x, int $y, float $r, float $g, float $b, float $a): bool
    {
        return ExtSDLSurface::SDLWriteSurfacePixelFloat($surface, $x, $y, $r, $g, $b, $a);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLWriteSurfacePixels(int $surface, array $data): bool
    {
        return ExtSDLSurface::SDLWriteSurfacePixels($surface, $data);
    }
}
