<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Timer;

use Sdl3\SDL\Timer\SDLTimer as ExtSDLTimer;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Timer\SDLTimer
 * from ext-sdl3 0.7.0, one method per extension call.
 */
final class SDLTimer
{
    /**
     * SDL_Delay().
     */
    public static function SDLDelay(int $ms): void
    {
        ExtSDLTimer::SDLDelay($ms);
    }

    /**
     * SDL_GetTicks().
     */
    public static function SDLGetTicks(): int
    {
        return ExtSDLTimer::SDLGetTicks();
    }
}
