<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Render;

use Jovian\Bindings\Sdl3\Enums\SDLFlipMode;
use Jovian\Bindings\Sdl3\Enums\SDLPixelFormat;
use Jovian\Bindings\Sdl3\Enums\SDLRendererLogicalPresentation;
use Jovian\Bindings\Sdl3\Enums\SDLScaleMode;
use Jovian\Bindings\Sdl3\Enums\SDLTextureAccess;
use Jovian\Bindings\Sdl3\Enums\SDLTextureAddressMode;
use Sdl3\SDL\Render\SDLRender as ExtSDLRender;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Render\SDLRender
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLRender
{
    /**
     * SDL_AddVulkanRenderSemaphores().
     */
    public static function SDLAddVulkanRenderSemaphores(int $renderer, int $waitStageMask, int $waitSemaphore, int $signalSemaphore): bool
    {
        return ExtSDLRender::SDLAddVulkanRenderSemaphores($renderer, $waitStageMask, $waitSemaphore, $signalSemaphore);
    }

    /**
     * SDL_ConvertEventToRenderCoordinates().
     */
    public static function SDLConvertEventToRenderCoordinates(int $renderer, int $eventPtr): bool
    {
        return ExtSDLRender::SDLConvertEventToRenderCoordinates($renderer, $eventPtr);
    }

    /**
     * SDL_CreateRenderer().
     */
    public static function SDLCreateRenderer(int $window, mixed $name = null): int
    {
        return ExtSDLRender::SDLCreateRenderer(...array_slice([$window, $name], 0, func_num_args()));
    }

    /**
     * SDL_CreateRendererWithProperties().
     */
    public static function SDLCreateRendererWithProperties(int $props): int
    {
        return ExtSDLRender::SDLCreateRendererWithProperties($props);
    }

    /**
     * SDL_CreateSoftwareRenderer().
     */
    public static function SDLCreateSoftwareRenderer(int $surface): int
    {
        return ExtSDLRender::SDLCreateSoftwareRenderer($surface);
    }

    /**
     * SDL_CreateTexture().
     */
    public static function SDLCreateTexture(int $renderer, SDLPixelFormat|int $format, SDLTextureAccess|int $access, int $w, int $h): array
    {
        return ExtSDLRender::SDLCreateTexture($renderer, $format instanceof \BackedEnum ? $format->value : $format, $access instanceof \BackedEnum ? $access->value : $access, $w, $h);
    }

    /**
     * SDL_CreateTextureFromSurface().
     */
    public static function SDLCreateTextureFromSurface(int $renderer, int $surface): array
    {
        return ExtSDLRender::SDLCreateTextureFromSurface($renderer, $surface);
    }

    /**
     * SDL_CreateTextureWithProperties().
     */
    public static function SDLCreateTextureWithProperties(int $renderer, int $props): array
    {
        return ExtSDLRender::SDLCreateTextureWithProperties($renderer, $props);
    }

    /**
     * SDL_DestroyRenderer().
     */
    public static function SDLDestroyRenderer(int $renderer): void
    {
        ExtSDLRender::SDLDestroyRenderer($renderer);
    }

    /**
     * SDL_DestroyTexture().
     */
    public static function SDLDestroyTexture(int $texture): void
    {
        ExtSDLRender::SDLDestroyTexture($texture);
    }

    /**
     * SDL_FlushRenderer().
     */
    public static function SDLFlushRenderer(int $renderer): bool
    {
        return ExtSDLRender::SDLFlushRenderer($renderer);
    }

    /**
     * SDL_GetCurrentRenderOutputSize().
     */
    public static function SDLGetCurrentRenderOutputSize(int $renderer): array
    {
        return ExtSDLRender::SDLGetCurrentRenderOutputSize($renderer);
    }

    /**
     * SDL_GetDefaultTextureScaleMode().
     */
    public static function SDLGetDefaultTextureScaleMode(int $renderer): array
    {
        return ExtSDLRender::SDLGetDefaultTextureScaleMode($renderer);
    }

    /**
     * SDL_GetNumRenderDrivers().
     */
    public static function SDLGetNumRenderDrivers(): int
    {
        return ExtSDLRender::SDLGetNumRenderDrivers();
    }

    /**
     * SDL_GetRenderClipRect().
     */
    public static function SDLGetRenderClipRect(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderClipRect($renderer);
    }

    /**
     * SDL_GetRenderColorScale().
     */
    public static function SDLGetRenderColorScale(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderColorScale($renderer);
    }

    /**
     * SDL_GetRenderDrawBlendMode().
     */
    public static function SDLGetRenderDrawBlendMode(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderDrawBlendMode($renderer);
    }

    /**
     * SDL_GetRenderDrawColor().
     */
    public static function SDLGetRenderDrawColor(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderDrawColor($renderer);
    }

    /**
     * SDL_GetRenderDrawColorFloat().
     */
    public static function SDLGetRenderDrawColorFloat(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderDrawColorFloat($renderer);
    }

    /**
     * SDL_GetRenderDriver().
     */
    public static function SDLGetRenderDriver(int $index): string
    {
        return ExtSDLRender::SDLGetRenderDriver($index);
    }

    /**
     * SDL_GetRenderLogicalPresentation().
     */
    public static function SDLGetRenderLogicalPresentation(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderLogicalPresentation($renderer);
    }

    /**
     * SDL_GetRenderLogicalPresentationRect().
     */
    public static function SDLGetRenderLogicalPresentationRect(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderLogicalPresentationRect($renderer);
    }

    /**
     * SDL_GetRenderMetalCommandEncoder().
     */
    public static function SDLGetRenderMetalCommandEncoder(int $renderer): int
    {
        return ExtSDLRender::SDLGetRenderMetalCommandEncoder($renderer);
    }

    /**
     * SDL_GetRenderMetalLayer().
     */
    public static function SDLGetRenderMetalLayer(int $renderer): int
    {
        return ExtSDLRender::SDLGetRenderMetalLayer($renderer);
    }

    /**
     * SDL_GetRenderOutputSize().
     */
    public static function SDLGetRenderOutputSize(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderOutputSize($renderer);
    }

    /**
     * SDL_GetRenderSafeArea().
     */
    public static function SDLGetRenderSafeArea(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderSafeArea($renderer);
    }

    /**
     * SDL_GetRenderScale().
     */
    public static function SDLGetRenderScale(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderScale($renderer);
    }

    /**
     * SDL_GetRenderTarget().
     */
    public static function SDLGetRenderTarget(int $renderer): int
    {
        return ExtSDLRender::SDLGetRenderTarget($renderer);
    }

    /**
     * SDL_GetRenderTextureAddressMode().
     */
    public static function SDLGetRenderTextureAddressMode(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderTextureAddressMode($renderer);
    }

    /**
     * SDL_GetRenderVSync().
     */
    public static function SDLGetRenderVSync(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderVSync($renderer);
    }

    /**
     * SDL_GetRenderViewport().
     */
    public static function SDLGetRenderViewport(int $renderer): array
    {
        return ExtSDLRender::SDLGetRenderViewport($renderer);
    }

    /**
     * SDL_GetRenderWindow().
     */
    public static function SDLGetRenderWindow(int $renderer): int
    {
        return ExtSDLRender::SDLGetRenderWindow($renderer);
    }

    /**
     * SDL_GetRenderer().
     */
    public static function SDLGetRenderer(int $window): int
    {
        return ExtSDLRender::SDLGetRenderer($window);
    }

    /**
     * SDL_GetRendererFromTexture().
     */
    public static function SDLGetRendererFromTexture(int $texture): int
    {
        return ExtSDLRender::SDLGetRendererFromTexture($texture);
    }

    /**
     * SDL_GetRendererName().
     */
    public static function SDLGetRendererName(int $renderer): string
    {
        return ExtSDLRender::SDLGetRendererName($renderer);
    }

    /**
     * SDL_GetRendererProperties().
     */
    public static function SDLGetRendererProperties(int $renderer): int
    {
        return ExtSDLRender::SDLGetRendererProperties($renderer);
    }

    /**
     * SDL_GetTextureAlphaMod().
     */
    public static function SDLGetTextureAlphaMod(int $texture): array
    {
        return ExtSDLRender::SDLGetTextureAlphaMod($texture);
    }

    /**
     * SDL_GetTextureAlphaModFloat().
     */
    public static function SDLGetTextureAlphaModFloat(int $texture): array
    {
        return ExtSDLRender::SDLGetTextureAlphaModFloat($texture);
    }

    /**
     * SDL_GetTextureBlendMode().
     */
    public static function SDLGetTextureBlendMode(int $texture): array
    {
        return ExtSDLRender::SDLGetTextureBlendMode($texture);
    }

    /**
     * SDL_GetTextureColorMod().
     */
    public static function SDLGetTextureColorMod(int $texture): array
    {
        return ExtSDLRender::SDLGetTextureColorMod($texture);
    }

    /**
     * SDL_GetTextureColorModFloat().
     */
    public static function SDLGetTextureColorModFloat(int $texture): array
    {
        return ExtSDLRender::SDLGetTextureColorModFloat($texture);
    }

    /**
     * SDL_GetTexturePalette().
     */
    public static function SDLGetTexturePalette(int $texture): int
    {
        return ExtSDLRender::SDLGetTexturePalette($texture);
    }

    /**
     * SDL_GetTextureScaleMode().
     */
    public static function SDLGetTextureScaleMode(int $texture): array
    {
        return ExtSDLRender::SDLGetTextureScaleMode($texture);
    }

    /**
     * SDL_GetTextureSize().
     */
    public static function SDLGetTextureSize(int $texture): array
    {
        return ExtSDLRender::SDLGetTextureSize($texture);
    }

    /**
     * SDL_LockTexture().
     */
    public static function SDLLockTexture(int $texture, mixed $rect = null): array
    {
        return ExtSDLRender::SDLLockTexture(...array_slice([$texture, $rect], 0, func_num_args()));
    }

    /**
     * SDL_LockTextureToSurface().
     */
    public static function SDLLockTextureToSurface(int $texture, mixed $rect = null): array
    {
        return ExtSDLRender::SDLLockTextureToSurface(...array_slice([$texture, $rect], 0, func_num_args()));
    }

    /**
     * SDL_RenderClear().
     */
    public static function SDLRenderClear(int $renderer): void
    {
        ExtSDLRender::SDLRenderClear($renderer);
    }

    /**
     * SDL_RenderClipEnabled().
     */
    public static function SDLRenderClipEnabled(int $renderer): bool
    {
        return ExtSDLRender::SDLRenderClipEnabled($renderer);
    }

    /**
     * SDL_RenderCoordinatesFromWindow().
     */
    public static function SDLRenderCoordinatesFromWindow(int $renderer, float $windowX, float $windowY): array
    {
        return ExtSDLRender::SDLRenderCoordinatesFromWindow($renderer, $windowX, $windowY);
    }

    /**
     * SDL_RenderCoordinatesToWindow().
     */
    public static function SDLRenderCoordinatesToWindow(int $renderer, float $x, float $y): array
    {
        return ExtSDLRender::SDLRenderCoordinatesToWindow($renderer, $x, $y);
    }

    /**
     * SDL_RenderDebugText().
     */
    public static function SDLRenderDebugText(int $renderer, float $x, float $y, string $str): bool
    {
        return ExtSDLRender::SDLRenderDebugText($renderer, $x, $y, $str);
    }

    /**
     * SDL_RenderFillRect().
     */
    public static function SDLRenderFillRect(int $renderer, mixed $rect = null): bool
    {
        return ExtSDLRender::SDLRenderFillRect(...array_slice([$renderer, $rect], 0, func_num_args()));
    }

    /**
     * SDL_RenderFillRects().
     */
    public static function SDLRenderFillRects(int $renderer, array $rects, int $count): bool
    {
        return ExtSDLRender::SDLRenderFillRects($renderer, $rects, $count);
    }

    /**
     * SDL_RenderGeometry().
     */
    public static function SDLRenderGeometry(int $renderer, int $texture, array $vertices, int $num_vertices, int $num_indices, mixed $indices = null): bool
    {
        return ExtSDLRender::SDLRenderGeometry(...array_slice([$renderer, $texture, $vertices, $num_vertices, $num_indices, $indices], 0, func_num_args()));
    }

    /**
     * SDL_RenderGeometryRaw().
     */
    public static function SDLRenderGeometryRaw(int $renderer, int $texture, string $xy, int $xyStride, mixed $color = null, int $colorStride = 0, mixed $uv = null, int $uvStride = 0, int $numVertices = 0, mixed $indices = null, int $numIndices = 0, int $sizeIndices = 0): bool
    {
        return ExtSDLRender::SDLRenderGeometryRaw(...array_slice([$renderer, $texture, $xy, $xyStride, $color, $colorStride, $uv, $uvStride, $numVertices, $indices, $numIndices, $sizeIndices], 0, func_num_args()));
    }

    /**
     * SDL_RenderLine().
     */
    public static function SDLRenderLine(int $renderer, float $x1, float $y1, float $x2, float $y2): bool
    {
        return ExtSDLRender::SDLRenderLine($renderer, $x1, $y1, $x2, $y2);
    }

    /**
     * SDL_RenderLines().
     */
    public static function SDLRenderLines(int $renderer, array $points, int $count): bool
    {
        return ExtSDLRender::SDLRenderLines($renderer, $points, $count);
    }

    /**
     * SDL_RenderPoint().
     */
    public static function SDLRenderPoint(int $renderer, float $x, float $y): bool
    {
        return ExtSDLRender::SDLRenderPoint($renderer, $x, $y);
    }

    /**
     * SDL_RenderPoints().
     */
    public static function SDLRenderPoints(int $renderer, array $points, int $count): bool
    {
        return ExtSDLRender::SDLRenderPoints($renderer, $points, $count);
    }

    /**
     * SDL_RenderPresent().
     */
    public static function SDLRenderPresent(int $renderer): bool
    {
        return ExtSDLRender::SDLRenderPresent($renderer);
    }

    /**
     * SDL_RenderReadPixels().
     */
    public static function SDLRenderReadPixels(int $renderer, mixed $rect = null): array
    {
        return ExtSDLRender::SDLRenderReadPixels(...array_slice([$renderer, $rect], 0, func_num_args()));
    }

    /**
     * SDL_RenderRect().
     */
    public static function SDLRenderRect(int $renderer, mixed $rect = null): bool
    {
        return ExtSDLRender::SDLRenderRect(...array_slice([$renderer, $rect], 0, func_num_args()));
    }

    /**
     * SDL_RenderRects().
     */
    public static function SDLRenderRects(int $renderer, array $rects, int $count): bool
    {
        return ExtSDLRender::SDLRenderRects($renderer, $rects, $count);
    }

    /**
     * SDL_RenderTexture().
     */
    public static function SDLRenderTexture(int $renderer, int $texture, mixed $srcrect = null, mixed $dstrect = null): bool
    {
        return ExtSDLRender::SDLRenderTexture(...array_slice([$renderer, $texture, $srcrect, $dstrect], 0, func_num_args()));
    }

    /**
     * SDL_RenderTexture9Grid().
     */
    public static function SDLRenderTexture9Grid(int $renderer, int $texture, float $leftWidth, float $rightWidth, float $topHeight, float $bottomHeight, float $scale, mixed $srcrect = null, mixed $dstrect = null): bool
    {
        return ExtSDLRender::SDLRenderTexture9Grid(...array_slice([$renderer, $texture, $leftWidth, $rightWidth, $topHeight, $bottomHeight, $scale, $srcrect, $dstrect], 0, func_num_args()));
    }

    /**
     * SDL_RenderTexture9GridTiled().
     */
    public static function SDLRenderTexture9GridTiled(int $renderer, int $texture, float $leftWidth, float $rightWidth, float $topHeight, float $bottomHeight, float $scale, float $tileScale, mixed $srcrect = null, mixed $dstrect = null): bool
    {
        return ExtSDLRender::SDLRenderTexture9GridTiled(...array_slice([$renderer, $texture, $leftWidth, $rightWidth, $topHeight, $bottomHeight, $scale, $tileScale, $srcrect, $dstrect], 0, func_num_args()));
    }

    /**
     * SDL_RenderTextureAffine().
     */
    public static function SDLRenderTextureAffine(int $renderer, int $texture, mixed $origin, mixed $right, mixed $down, mixed $srcrect = null): bool
    {
        return ExtSDLRender::SDLRenderTextureAffine(...array_slice([$renderer, $texture, $origin, $right, $down, $srcrect], 0, func_num_args()));
    }

    /**
     * SDL_RenderTextureRotated().
     */
    public static function SDLRenderTextureRotated(int $renderer, int $texture, float $angle, SDLFlipMode|int $flip, mixed $srcrect = null, mixed $dstrect = null, mixed $center = null): bool
    {
        return ExtSDLRender::SDLRenderTextureRotated(...array_slice([$renderer, $texture, $angle, $flip instanceof \BackedEnum ? $flip->value : $flip, $srcrect, $dstrect, $center], 0, func_num_args()));
    }

    /**
     * SDL_RenderTextureTiled().
     */
    public static function SDLRenderTextureTiled(int $renderer, int $texture, float $scale, mixed $srcrect = null, mixed $dstrect = null): bool
    {
        return ExtSDLRender::SDLRenderTextureTiled(...array_slice([$renderer, $texture, $scale, $srcrect, $dstrect], 0, func_num_args()));
    }

    /**
     * SDL_RenderViewportSet().
     */
    public static function SDLRenderViewportSet(int $renderer): bool
    {
        return ExtSDLRender::SDLRenderViewportSet($renderer);
    }

    /**
     * SDL_SetDefaultTextureScaleMode().
     */
    public static function SDLSetDefaultTextureScaleMode(int $renderer, SDLScaleMode|int $scaleMode): bool
    {
        return ExtSDLRender::SDLSetDefaultTextureScaleMode($renderer, $scaleMode instanceof \BackedEnum ? $scaleMode->value : $scaleMode);
    }

    /**
     * SDL_SetRenderClipRect().
     */
    public static function SDLSetRenderClipRect(int $renderer, mixed $rect = null): bool
    {
        return ExtSDLRender::SDLSetRenderClipRect(...array_slice([$renderer, $rect], 0, func_num_args()));
    }

    /**
     * SDL_SetRenderColorScale().
     */
    public static function SDLSetRenderColorScale(int $renderer, float $scale): bool
    {
        return ExtSDLRender::SDLSetRenderColorScale($renderer, $scale);
    }

    /**
     * SDL_SetRenderDrawBlendMode().
     *
     * @param int $blendMode SDLBlendMode bitmask; OR the enum cases' values together.
     */
    public static function SDLSetRenderDrawBlendMode(int $renderer, int $blendMode): bool
    {
        return ExtSDLRender::SDLSetRenderDrawBlendMode($renderer, $blendMode);
    }

    /**
     * SDL_SetRenderDrawColor().
     */
    public static function SDLSetRenderDrawColor(int $renderer, int $r, int $g, int $b, int $a): bool
    {
        return ExtSDLRender::SDLSetRenderDrawColor($renderer, $r, $g, $b, $a);
    }

    /**
     * SDL_SetRenderDrawColorFloat().
     */
    public static function SDLSetRenderDrawColorFloat(int $renderer, float $r, float $g, float $b, float $a): bool
    {
        return ExtSDLRender::SDLSetRenderDrawColorFloat($renderer, $r, $g, $b, $a);
    }

    /**
     * SDL_SetRenderLogicalPresentation().
     */
    public static function SDLSetRenderLogicalPresentation(int $renderer, int $w, int $h, SDLRendererLogicalPresentation|int $mode): bool
    {
        return ExtSDLRender::SDLSetRenderLogicalPresentation($renderer, $w, $h, $mode instanceof \BackedEnum ? $mode->value : $mode);
    }

    /**
     * SDL_SetRenderScale().
     */
    public static function SDLSetRenderScale(int $renderer, float $scaleX, float $scaleY): bool
    {
        return ExtSDLRender::SDLSetRenderScale($renderer, $scaleX, $scaleY);
    }

    /**
     * SDL_SetRenderTarget().
     */
    public static function SDLSetRenderTarget(int $renderer, mixed $texture = null): bool
    {
        return ExtSDLRender::SDLSetRenderTarget(...array_slice([$renderer, $texture], 0, func_num_args()));
    }

    /**
     * SDL_SetRenderTextureAddressMode().
     */
    public static function SDLSetRenderTextureAddressMode(int $renderer, SDLTextureAddressMode|int $uMode, SDLTextureAddressMode|int $vMode): bool
    {
        return ExtSDLRender::SDLSetRenderTextureAddressMode($renderer, $uMode instanceof \BackedEnum ? $uMode->value : $uMode, $vMode instanceof \BackedEnum ? $vMode->value : $vMode);
    }

    /**
     * SDL_SetRenderVSync().
     */
    public static function SDLSetRenderVSync(int $renderer, int $vsync): bool
    {
        return ExtSDLRender::SDLSetRenderVSync($renderer, $vsync);
    }

    /**
     * SDL_SetRenderViewport().
     */
    public static function SDLSetRenderViewport(int $renderer, mixed $rect = null): bool
    {
        return ExtSDLRender::SDLSetRenderViewport(...array_slice([$renderer, $rect], 0, func_num_args()));
    }

    /**
     * SDL_SetTextureAlphaMod().
     */
    public static function SDLSetTextureAlphaMod(int $texture, int $alpha): bool
    {
        return ExtSDLRender::SDLSetTextureAlphaMod($texture, $alpha);
    }

    /**
     * SDL_SetTextureAlphaModFloat().
     */
    public static function SDLSetTextureAlphaModFloat(int $texture, float $alpha): bool
    {
        return ExtSDLRender::SDLSetTextureAlphaModFloat($texture, $alpha);
    }

    /**
     * SDL_SetTextureBlendMode().
     *
     * @param int $blendMode SDLBlendMode bitmask; OR the enum cases' values together.
     */
    public static function SDLSetTextureBlendMode(int $texture, int $blendMode): bool
    {
        return ExtSDLRender::SDLSetTextureBlendMode($texture, $blendMode);
    }

    /**
     * SDL_SetTextureColorMod().
     */
    public static function SDLSetTextureColorMod(int $texture, int $r, int $g, int $b): bool
    {
        return ExtSDLRender::SDLSetTextureColorMod($texture, $r, $g, $b);
    }

    /**
     * SDL_SetTextureColorModFloat().
     */
    public static function SDLSetTextureColorModFloat(int $texture, float $r, float $g, float $b): bool
    {
        return ExtSDLRender::SDLSetTextureColorModFloat($texture, $r, $g, $b);
    }

    /**
     * SDL_SetTexturePalette().
     */
    public static function SDLSetTexturePalette(int $texture, int $palette): bool
    {
        return ExtSDLRender::SDLSetTexturePalette($texture, $palette);
    }

    /**
     * SDL_SetTextureScaleMode().
     */
    public static function SDLSetTextureScaleMode(int $texture, SDLScaleMode|int $scaleMode): bool
    {
        return ExtSDLRender::SDLSetTextureScaleMode($texture, $scaleMode instanceof \BackedEnum ? $scaleMode->value : $scaleMode);
    }

    /**
     * SDL_UnlockTexture().
     */
    public static function SDLUnlockTexture(int $texture): void
    {
        ExtSDLRender::SDLUnlockTexture($texture);
    }

    /**
     * SDL_UpdateNVTexture().
     */
    public static function SDLUpdateNVTexture(int $texture, string $yplane, int $ypitch, string $uvplane, int $uvpitch, mixed $rect = null): bool
    {
        return ExtSDLRender::SDLUpdateNVTexture(...array_slice([$texture, $yplane, $ypitch, $uvplane, $uvpitch, $rect], 0, func_num_args()));
    }

    /**
     * SDL_UpdateTexture().
     */
    public static function SDLUpdateTexture(int $texture, string $pixels, int $pitch, mixed $rect = null): bool
    {
        return ExtSDLRender::SDLUpdateTexture(...array_slice([$texture, $pixels, $pitch, $rect], 0, func_num_args()));
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLUpdateTextureFromSurface(int $texture, int $surface): bool
    {
        return ExtSDLRender::SDLUpdateTextureFromSurface($texture, $surface);
    }

    /**
     * SDL_UpdateYUVTexture().
     */
    public static function SDLUpdateYUVTexture(int $texture, string $yplane, int $ypitch, string $uplane, int $upitch, string $vplane, int $vpitch, mixed $rect = null): bool
    {
        return ExtSDLRender::SDLUpdateYUVTexture(...array_slice([$texture, $yplane, $ypitch, $uplane, $upitch, $vplane, $vpitch, $rect], 0, func_num_args()));
    }
}
