<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Events;

use Sdl3\SDL\Events\SDLCategories as ExtSDLCategories;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Events\SDLCategories
 * from ext-sdl3 0.7.0, one method per extension call.
 */
final class SDLCategories
{
    /**
     * SDL_EventEnabled().
     */
    public static function SDLEventEnabled(int $type): bool
    {
        return ExtSDLCategories::SDLEventEnabled($type);
    }

    /**
     * SDL_GetEventDescription().
     */
    public static function SDLGetEventDescription(int $event_ptr, int $buflen = 0): string
    {
        return ExtSDLCategories::SDLGetEventDescription(...array_slice([$event_ptr, $buflen], 0, func_num_args()));
    }

    /**
     * SDL_GetWindowFromEvent().
     */
    public static function SDLGetWindowFromEvent(int $event_ptr): int
    {
        return ExtSDLCategories::SDLGetWindowFromEvent($event_ptr);
    }

    /**
     * SDL_RegisterEvents().
     */
    public static function SDLRegisterEvents(int $numevents): int
    {
        return ExtSDLCategories::SDLRegisterEvents($numevents);
    }

    /**
     * SDL_SetEventEnabled().
     */
    public static function SDLSetEventEnabled(int $type, bool $enabled): void
    {
        ExtSDLCategories::SDLSetEventEnabled($type, $enabled);
    }
}
