<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Events;

use Sdl3\SDL\Events\SDLClipboardEvents as ExtSDLClipboardEvents;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Events\SDLClipboardEvents
 * from ext-sdl3 0.7.0, one method per extension call.
 */
final class SDLClipboardEvents
{
    /**
     * SDL_ClearClipboardData().
     */
    public static function SDLClearClipboardData(): void
    {
        ExtSDLClipboardEvents::SDLClearClipboardData();
    }

    /**
     * SDL_GetClipboardMimeTypes().
     */
    public static function SDLGetClipboardMimeTypes(): array
    {
        return ExtSDLClipboardEvents::SDLGetClipboardMimeTypes();
    }

    /**
     * SDL_GetClipboardText().
     */
    public static function SDLGetClipboardText(): string
    {
        return ExtSDLClipboardEvents::SDLGetClipboardText();
    }

    /**
     * SDL_GetPrimarySelectionText().
     */
    public static function SDLGetPrimarySelectionText(): string
    {
        return ExtSDLClipboardEvents::SDLGetPrimarySelectionText();
    }

    /**
     * SDL_HasClipboardData().
     */
    public static function SDLHasClipboardData(string $mime_type): bool
    {
        return ExtSDLClipboardEvents::SDLHasClipboardData($mime_type);
    }

    /**
     * SDL_HasClipboardText().
     */
    public static function SDLHasClipboardText(): bool
    {
        return ExtSDLClipboardEvents::SDLHasClipboardText();
    }

    /**
     * SDL_HasPrimarySelectionText().
     */
    public static function SDLHasPrimarySelectionText(): bool
    {
        return ExtSDLClipboardEvents::SDLHasPrimarySelectionText();
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadClipboardEvent(int $ptr): array
    {
        return ExtSDLClipboardEvents::SDLReadClipboardEvent($ptr);
    }

    /**
     * SDL_SetClipboardText().
     */
    public static function SDLSetClipboardText(string $text): bool
    {
        return ExtSDLClipboardEvents::SDLSetClipboardText($text);
    }

    /**
     * SDL_SetPrimarySelectionText().
     */
    public static function SDLSetPrimarySelectionText(string $text): bool
    {
        return ExtSDLClipboardEvents::SDLSetPrimarySelectionText($text);
    }
}
