<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Events;

use Jovian\Bindings\Sdl3\Enums\SDLDisplayOrientation;
use Sdl3\SDL\Events\SDLDisplayEvents as ExtSDLDisplayEvents;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Events\SDLDisplayEvents
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLDisplayEvents
{
    /**
     * SDL_GetClosestFullscreenDisplayMode().
     */
    public static function SDLGetClosestFullscreenDisplayMode(int $display_id, int $w, int $h, float $refresh_rate = 0.0, bool $include_high_density_modes = false): array
    {
        return ExtSDLDisplayEvents::SDLGetClosestFullscreenDisplayMode(...array_slice([$display_id, $w, $h, $refresh_rate, $include_high_density_modes], 0, func_num_args()));
    }

    /**
     * SDL_GetCurrentDisplayMode().
     */
    public static function SDLGetCurrentDisplayMode(int $display_id): array
    {
        return ExtSDLDisplayEvents::SDLGetCurrentDisplayMode($display_id);
    }

    /**
     * SDL_GetCurrentDisplayOrientation().
     */
    public static function SDLGetCurrentDisplayOrientation(int $display_id): SDLDisplayOrientation|int
    {
        return ExtSDLDisplayEvents::SDLGetCurrentDisplayOrientation($display_id);
    }

    /**
     * SDL_GetDesktopDisplayMode().
     */
    public static function SDLGetDesktopDisplayMode(int $display_id): array
    {
        return ExtSDLDisplayEvents::SDLGetDesktopDisplayMode($display_id);
    }

    /**
     * SDL_GetDisplayBounds().
     */
    public static function SDLGetDisplayBounds(int $display_id): array
    {
        return ExtSDLDisplayEvents::SDLGetDisplayBounds($display_id);
    }

    /**
     * SDL_GetDisplayContentScale().
     */
    public static function SDLGetDisplayContentScale(int $display_id): float
    {
        return ExtSDLDisplayEvents::SDLGetDisplayContentScale($display_id);
    }

    /**
     * SDL_GetDisplayForWindow().
     */
    public static function SDLGetDisplayForWindow(int $window): int
    {
        return ExtSDLDisplayEvents::SDLGetDisplayForWindow($window);
    }

    /**
     * SDL_GetDisplayName().
     */
    public static function SDLGetDisplayName(int $display_id): string
    {
        return ExtSDLDisplayEvents::SDLGetDisplayName($display_id);
    }

    /**
     * SDL_GetDisplays().
     */
    public static function SDLGetDisplays(): array
    {
        return ExtSDLDisplayEvents::SDLGetDisplays();
    }

    /**
     * SDL_GetFullscreenDisplayModes().
     */
    public static function SDLGetFullscreenDisplayModes(int $display_id): array
    {
        return ExtSDLDisplayEvents::SDLGetFullscreenDisplayModes($display_id);
    }

    /**
     * SDL_GetNaturalDisplayOrientation().
     */
    public static function SDLGetNaturalDisplayOrientation(int $display_id): SDLDisplayOrientation|int
    {
        return ExtSDLDisplayEvents::SDLGetNaturalDisplayOrientation($display_id);
    }

    /**
     * SDL_GetPrimaryDisplay().
     */
    public static function SDLGetPrimaryDisplay(): int
    {
        return ExtSDLDisplayEvents::SDLGetPrimaryDisplay();
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadDisplayEvent(int $ptr): array
    {
        return ExtSDLDisplayEvents::SDLReadDisplayEvent($ptr);
    }
}
