<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Events;

use Sdl3\SDL\Events\SDLDropEvents as ExtSDLDropEvents;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Events\SDLDropEvents
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLDropEvents
{
    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadDropEvent(int $ptr): array
    {
        return ExtSDLDropEvents::SDLReadDropEvent($ptr);
    }
}
