<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Events;

use Sdl3\SDL\Events\SDLEventWatch as ExtSDLEventWatch;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Events\SDLEventWatch
 * from ext-sdl3 0.7.0, one method per extension call.
 */
final class SDLEventWatch
{
    /**
     * SDL_AddEventWatch().
     */
    public static function SDLAddEventWatch(mixed $callback): int
    {
        return ExtSDLEventWatch::SDLAddEventWatch($callback);
    }

    /**
     * SDL_FilterEvents().
     */
    public static function SDLFilterEvents(mixed $callback): void
    {
        ExtSDLEventWatch::SDLFilterEvents($callback);
    }

    /**
     * SDL_GetEventFilter().
     */
    public static function SDLGetEventFilter(): bool
    {
        return ExtSDLEventWatch::SDLGetEventFilter();
    }

    /**
     * SDL_RemoveEventWatch().
     */
    public static function SDLRemoveEventWatch(int $watch_id): bool
    {
        return ExtSDLEventWatch::SDLRemoveEventWatch($watch_id);
    }

    /**
     * SDL_SetEventFilter().
     */
    public static function SDLSetEventFilter(mixed $callback = null): void
    {
        ExtSDLEventWatch::SDLSetEventFilter(...array_slice([$callback], 0, func_num_args()));
    }
}
