<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Events;

use Jovian\Bindings\Sdl3\Enums\SDLEventAction;
use Sdl3\SDL\Events\SDLEvents as ExtSDLEvents;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Events\SDLEvents
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLEvents
{
    /**
     * SDL_FlushEvent().
     */
    public static function SDLFlushEvent(int $type): void
    {
        ExtSDLEvents::SDLFlushEvent($type);
    }

    /**
     * SDL_FlushEvents().
     */
    public static function SDLFlushEvents(int $min_type, int $max_type): void
    {
        ExtSDLEvents::SDLFlushEvents($min_type, $max_type);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLFreeEvent(int $ptr): void
    {
        ExtSDLEvents::SDLFreeEvent($ptr);
    }

    /**
     * SDL_GetKeyboardState().
     */
    public static function SDLGetKeyboardState(): array
    {
        return ExtSDLEvents::SDLGetKeyboardState();
    }

    /**
     * SDL_HasEvent().
     */
    public static function SDLHasEvent(int $type): bool
    {
        return ExtSDLEvents::SDLHasEvent($type);
    }

    /**
     * SDL_HasEvents().
     */
    public static function SDLHasEvents(int $min_type, int $max_type): bool
    {
        return ExtSDLEvents::SDLHasEvents($min_type, $max_type);
    }

    /**
     * SDL_PeepEvents().
     */
    public static function SDLPeepEvents(SDLEventAction|int $action, int $min_type, int $max_type, int $numevents = 0): array
    {
        return ExtSDLEvents::SDLPeepEvents(...array_slice([$action instanceof \BackedEnum ? $action->value : $action, $min_type, $max_type, $numevents], 0, func_num_args()));
    }

    /**
     * SDL_PollEvent().
     */
    public static function SDLPollEvent(): ?array
    {
        return ExtSDLEvents::SDLPollEvent();
    }

    /**
     * SDL_PumpEvents().
     */
    public static function SDLPumpEvents(): void
    {
        ExtSDLEvents::SDLPumpEvents();
    }

    /**
     * SDL_PushEvent().
     */
    public static function SDLPushEvent(int $event_ptr): bool
    {
        return ExtSDLEvents::SDLPushEvent($event_ptr);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadEvent(int $ptr, string $key): array
    {
        return ExtSDLEvents::SDLReadEvent($ptr, $key);
    }

    /**
     * SDL_WaitEvent().
     */
    public static function SDLWaitEvent(): ?array
    {
        return ExtSDLEvents::SDLWaitEvent();
    }

    /**
     * SDL_WaitEventTimeout().
     */
    public static function SDLWaitEventTimeout(int $timeout_ms): ?array
    {
        return ExtSDLEvents::SDLWaitEventTimeout($timeout_ms);
    }
}
