<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Events;

use Jovian\Bindings\Sdl3\Enums\SDLScancode;
use Sdl3\SDL\Events\SDLKeyboard as ExtSDLKeyboard;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Events\SDLKeyboard
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLKeyboard
{
    /**
     * SDL_ClearComposition().
     */
    public static function SDLClearComposition(int $window): bool
    {
        return ExtSDLKeyboard::SDLClearComposition($window);
    }

    /**
     * SDL_GetKeyFromName().
     */
    public static function SDLGetKeyFromName(string $name): int
    {
        return ExtSDLKeyboard::SDLGetKeyFromName($name);
    }

    /**
     * SDL_GetKeyFromScancode().
     *
     * @param int $modstate SDLKeymod bitmask; OR the enum cases' values together.
     */
    public static function SDLGetKeyFromScancode(SDLScancode|int $scancode, int $modstate = 0, bool $key_event = false): int
    {
        return ExtSDLKeyboard::SDLGetKeyFromScancode(...array_slice([$scancode instanceof \BackedEnum ? $scancode->value : $scancode, $modstate, $key_event], 0, func_num_args()));
    }

    /**
     * SDL_GetKeyName().
     */
    public static function SDLGetKeyName(int $key): string
    {
        return ExtSDLKeyboard::SDLGetKeyName($key);
    }

    /**
     * SDL_GetKeyboardFocus().
     */
    public static function SDLGetKeyboardFocus(): int
    {
        return ExtSDLKeyboard::SDLGetKeyboardFocus();
    }

    /**
     * SDL_GetKeyboardNameForID().
     */
    public static function SDLGetKeyboardNameForID(int $instance_id): string
    {
        return ExtSDLKeyboard::SDLGetKeyboardNameForID($instance_id);
    }

    /**
     * SDL_GetKeyboardState().
     */
    public static function SDLGetKeyboardState(): array
    {
        return ExtSDLKeyboard::SDLGetKeyboardState();
    }

    /**
     * SDL_GetKeyboards().
     */
    public static function SDLGetKeyboards(): array
    {
        return ExtSDLKeyboard::SDLGetKeyboards();
    }

    /**
     * SDL_GetModState().
     */
    public static function SDLGetModState(): int
    {
        return ExtSDLKeyboard::SDLGetModState();
    }

    /**
     * SDL_GetScancodeFromKey().
     */
    public static function SDLGetScancodeFromKey(int $key): array
    {
        return ExtSDLKeyboard::SDLGetScancodeFromKey($key);
    }

    /**
     * SDL_GetScancodeFromName().
     */
    public static function SDLGetScancodeFromName(string $name): SDLScancode|int
    {
        return ExtSDLKeyboard::SDLGetScancodeFromName($name);
    }

    /**
     * SDL_GetScancodeName().
     */
    public static function SDLGetScancodeName(SDLScancode|int $scancode): string
    {
        return ExtSDLKeyboard::SDLGetScancodeName($scancode instanceof \BackedEnum ? $scancode->value : $scancode);
    }

    /**
     * SDL_GetTextInputArea().
     */
    public static function SDLGetTextInputArea(int $window): ?array
    {
        return ExtSDLKeyboard::SDLGetTextInputArea($window);
    }

    /**
     * SDL_HasKeyboard().
     */
    public static function SDLHasKeyboard(): bool
    {
        return ExtSDLKeyboard::SDLHasKeyboard();
    }

    /**
     * SDL_HasScreenKeyboardSupport().
     */
    public static function SDLHasScreenKeyboardSupport(): bool
    {
        return ExtSDLKeyboard::SDLHasScreenKeyboardSupport();
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadKeyboardDeviceEvent(int $ptr): array
    {
        return ExtSDLKeyboard::SDLReadKeyboardDeviceEvent($ptr);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadKeyboardEvent(int $ptr): array
    {
        return ExtSDLKeyboard::SDLReadKeyboardEvent($ptr);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadTextEditingCandidatesEvent(int $ptr): array
    {
        return ExtSDLKeyboard::SDLReadTextEditingCandidatesEvent($ptr);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadTextEditingEvent(int $ptr): array
    {
        return ExtSDLKeyboard::SDLReadTextEditingEvent($ptr);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadTextInputEvent(int $ptr): array
    {
        return ExtSDLKeyboard::SDLReadTextInputEvent($ptr);
    }

    /**
     * SDL_ScreenKeyboardShown().
     */
    public static function SDLScreenKeyboardShown(int $window): bool
    {
        return ExtSDLKeyboard::SDLScreenKeyboardShown($window);
    }

    /**
     * SDL_SetModState().
     *
     * @param int $modstate SDLKeymod bitmask; OR the enum cases' values together.
     */
    public static function SDLSetModState(int $modstate): void
    {
        ExtSDLKeyboard::SDLSetModState($modstate);
    }

    /**
     * SDL_SetScancodeName().
     */
    public static function SDLSetScancodeName(SDLScancode|int $scancode, string $name): bool
    {
        return ExtSDLKeyboard::SDLSetScancodeName($scancode instanceof \BackedEnum ? $scancode->value : $scancode, $name);
    }

    /**
     * SDL_SetTextInputArea().
     */
    public static function SDLSetTextInputArea(int $window, mixed $rect = null, int $cursor = 0): bool
    {
        return ExtSDLKeyboard::SDLSetTextInputArea(...array_slice([$window, $rect, $cursor], 0, func_num_args()));
    }

    /**
     * SDL_StartTextInput().
     */
    public static function SDLStartTextInput(int $window): bool
    {
        return ExtSDLKeyboard::SDLStartTextInput($window);
    }

    /**
     * SDL_StartTextInputWithProperties().
     */
    public static function SDLStartTextInputWithProperties(int $window, int $props): bool
    {
        return ExtSDLKeyboard::SDLStartTextInputWithProperties($window, $props);
    }

    /**
     * SDL_StopTextInput().
     */
    public static function SDLStopTextInput(int $window): bool
    {
        return ExtSDLKeyboard::SDLStopTextInput($window);
    }

    /**
     * SDL_TextInputActive().
     */
    public static function SDLTextInputActive(int $window): bool
    {
        return ExtSDLKeyboard::SDLTextInputActive($window);
    }
}
