<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Events;

use Jovian\Bindings\Sdl3\Enums\SDLSystemCursor;
use Sdl3\SDL\Events\SDLMouse as ExtSDLMouse;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Events\SDLMouse
 * from ext-sdl3 0.7.0, one method per extension call.
 */
final class SDLMouse
{
    /**
     * SDL_CaptureMouse().
     */
    public static function SDLCaptureMouse(bool $enabled): bool
    {
        return ExtSDLMouse::SDLCaptureMouse($enabled);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLCreateAnimatedCursor(array $frames, int $hot_x, int $hot_y): int
    {
        return ExtSDLMouse::SDLCreateAnimatedCursor($frames, $hot_x, $hot_y);
    }

    /**
     * SDL_CreateColorCursor().
     */
    public static function SDLCreateColorCursor(int $surface, int $hot_x, int $hot_y): int
    {
        return ExtSDLMouse::SDLCreateColorCursor($surface, $hot_x, $hot_y);
    }

    /**
     * SDL_CreateCursor().
     */
    public static function SDLCreateCursor(string $data, string $mask, int $w, int $h, int $hot_x, int $hot_y): int
    {
        return ExtSDLMouse::SDLCreateCursor($data, $mask, $w, $h, $hot_x, $hot_y);
    }

    /**
     * SDL_CreateSystemCursor().
     */
    public static function SDLCreateSystemCursor(SDLSystemCursor|int $id): int
    {
        return ExtSDLMouse::SDLCreateSystemCursor($id instanceof \BackedEnum ? $id->value : $id);
    }

    /**
     * SDL_CursorVisible().
     */
    public static function SDLCursorVisible(): bool
    {
        return ExtSDLMouse::SDLCursorVisible();
    }

    /**
     * SDL_DestroyCursor().
     */
    public static function SDLDestroyCursor(int $cursor): void
    {
        ExtSDLMouse::SDLDestroyCursor($cursor);
    }

    /**
     * SDL_GetCursor().
     */
    public static function SDLGetCursor(): int
    {
        return ExtSDLMouse::SDLGetCursor();
    }

    /**
     * SDL_GetDefaultCursor().
     */
    public static function SDLGetDefaultCursor(): int
    {
        return ExtSDLMouse::SDLGetDefaultCursor();
    }

    /**
     * SDL_GetGlobalMouseState().
     */
    public static function SDLGetGlobalMouseState(): array
    {
        return ExtSDLMouse::SDLGetGlobalMouseState();
    }

    /**
     * SDL_GetMice().
     */
    public static function SDLGetMice(): array
    {
        return ExtSDLMouse::SDLGetMice();
    }

    /**
     * SDL_GetMouseFocus().
     */
    public static function SDLGetMouseFocus(): int
    {
        return ExtSDLMouse::SDLGetMouseFocus();
    }

    /**
     * SDL_GetMouseNameForID().
     */
    public static function SDLGetMouseNameForID(int $instance_id): string
    {
        return ExtSDLMouse::SDLGetMouseNameForID($instance_id);
    }

    /**
     * SDL_GetMouseState().
     */
    public static function SDLGetMouseState(): array
    {
        return ExtSDLMouse::SDLGetMouseState();
    }

    /**
     * SDL_GetRelativeMouseState().
     */
    public static function SDLGetRelativeMouseState(): array
    {
        return ExtSDLMouse::SDLGetRelativeMouseState();
    }

    /**
     * SDL_GetWindowRelativeMouseMode().
     */
    public static function SDLGetWindowRelativeMouseMode(int $window): bool
    {
        return ExtSDLMouse::SDLGetWindowRelativeMouseMode($window);
    }

    /**
     * SDL_HasMouse().
     */
    public static function SDLHasMouse(): bool
    {
        return ExtSDLMouse::SDLHasMouse();
    }

    /**
     * SDL_HideCursor().
     */
    public static function SDLHideCursor(): bool
    {
        return ExtSDLMouse::SDLHideCursor();
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadMouseButtonEvent(int $ptr): array
    {
        return ExtSDLMouse::SDLReadMouseButtonEvent($ptr);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadMouseDeviceEvent(int $ptr): array
    {
        return ExtSDLMouse::SDLReadMouseDeviceEvent($ptr);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadMouseMotionEvent(int $ptr): array
    {
        return ExtSDLMouse::SDLReadMouseMotionEvent($ptr);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadMouseWheelEvent(int $ptr): array
    {
        return ExtSDLMouse::SDLReadMouseWheelEvent($ptr);
    }

    /**
     * SDL_SetCursor().
     */
    public static function SDLSetCursor(mixed $cursor = null): bool
    {
        return ExtSDLMouse::SDLSetCursor(...array_slice([$cursor], 0, func_num_args()));
    }

    /**
     * SDL_SetWindowRelativeMouseMode().
     */
    public static function SDLSetWindowRelativeMouseMode(int $window, bool $enabled): bool
    {
        return ExtSDLMouse::SDLSetWindowRelativeMouseMode($window, $enabled);
    }

    /**
     * SDL_ShowCursor().
     */
    public static function SDLShowCursor(): bool
    {
        return ExtSDLMouse::SDLShowCursor();
    }

    /**
     * SDL_WarpMouseGlobal().
     */
    public static function SDLWarpMouseGlobal(float $x, float $y): bool
    {
        return ExtSDLMouse::SDLWarpMouseGlobal($x, $y);
    }

    /**
     * SDL_WarpMouseInWindow().
     */
    public static function SDLWarpMouseInWindow(int $window, float $x, float $y = 0.0): void
    {
        ExtSDLMouse::SDLWarpMouseInWindow(...array_slice([$window, $x, $y], 0, func_num_args()));
    }
}
