<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Events;

use Sdl3\SDL\Events\SDLQuit as ExtSDLQuit;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Events\SDLQuit
 * from ext-sdl3 0.7.0, one method per extension call.
 */
final class SDLQuit
{
    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadQuitEvent(int $ptr): array
    {
        return ExtSDLQuit::SDLReadQuitEvent($ptr);
    }
}
