<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Events;

use Sdl3\SDL\Events\SDLWindowEvents as ExtSDLWindowEvents;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Events\SDLWindowEvents
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLWindowEvents
{
    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLReadWindowEvent(int $ptr): array
    {
        return ExtSDLWindowEvents::SDLReadWindowEvent($ptr);
    }
}
