<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Audio;

use Jovian\Bindings\Sdl3\Enums\SDLAudioFormat;
use Sdl3\SDL\Audio\SDLAudio as ExtSDLAudio;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Audio\SDLAudio
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLAudio
{
    /**
     * SDL_AudioDevicePaused().
     */
    public static function SDLAudioDevicePaused(int $devid): bool
    {
        return ExtSDLAudio::SDLAudioDevicePaused($devid);
    }

    /**
     * SDL_AudioStreamDevicePaused().
     */
    public static function SDLAudioStreamDevicePaused(int $stream): bool
    {
        return ExtSDLAudio::SDLAudioStreamDevicePaused($stream);
    }

    /**
     * SDL_BindAudioStream().
     */
    public static function SDLBindAudioStream(int $devid, int $stream): bool
    {
        return ExtSDLAudio::SDLBindAudioStream($devid, $stream);
    }

    /**
     * SDL_BindAudioStreams().
     */
    public static function SDLBindAudioStreams(int $devid, array $streams): bool
    {
        return ExtSDLAudio::SDLBindAudioStreams($devid, $streams);
    }

    /**
     * SDL_ClearAudioStream().
     */
    public static function SDLClearAudioStream(int $stream): bool
    {
        return ExtSDLAudio::SDLClearAudioStream($stream);
    }

    /**
     * SDL_CloseAudioDevice().
     */
    public static function SDLCloseAudioDevice(int $devid): void
    {
        ExtSDLAudio::SDLCloseAudioDevice($devid);
    }

    /**
     * SDL_ConvertAudioSamples().
     */
    public static function SDLConvertAudioSamples(mixed $src_spec, string $src_data, int $src_len, mixed $dst_spec): array
    {
        return ExtSDLAudio::SDLConvertAudioSamples($src_spec, $src_data, $src_len, $dst_spec);
    }

    /**
     * SDL_CreateAudioStream().
     */
    public static function SDLCreateAudioStream(mixed $src_spec, mixed $dst_spec): int
    {
        return ExtSDLAudio::SDLCreateAudioStream($src_spec, $dst_spec);
    }

    /**
     * SDL_DestroyAudioStream().
     */
    public static function SDLDestroyAudioStream(int $stream): void
    {
        ExtSDLAudio::SDLDestroyAudioStream($stream);
    }

    /**
     * SDL_FlushAudioStream().
     */
    public static function SDLFlushAudioStream(int $stream): bool
    {
        return ExtSDLAudio::SDLFlushAudioStream($stream);
    }

    /**
     * SDL_GetAudioDeviceChannelMap().
     */
    public static function SDLGetAudioDeviceChannelMap(int $devid): array
    {
        return ExtSDLAudio::SDLGetAudioDeviceChannelMap($devid);
    }

    /**
     * SDL_GetAudioDeviceFormat().
     */
    public static function SDLGetAudioDeviceFormat(int $devid): array
    {
        return ExtSDLAudio::SDLGetAudioDeviceFormat($devid);
    }

    /**
     * SDL_GetAudioDeviceGain().
     */
    public static function SDLGetAudioDeviceGain(int $devid): float
    {
        return ExtSDLAudio::SDLGetAudioDeviceGain($devid);
    }

    /**
     * SDL_GetAudioDeviceName().
     */
    public static function SDLGetAudioDeviceName(int $devid): string
    {
        return ExtSDLAudio::SDLGetAudioDeviceName($devid);
    }

    /**
     * SDL_GetAudioDriver().
     */
    public static function SDLGetAudioDriver(int $index): string
    {
        return ExtSDLAudio::SDLGetAudioDriver($index);
    }

    /**
     * SDL_GetAudioFormatName().
     */
    public static function SDLGetAudioFormatName(SDLAudioFormat|int $format): string
    {
        return ExtSDLAudio::SDLGetAudioFormatName($format instanceof \BackedEnum ? $format->value : $format);
    }

    /**
     * SDL_GetAudioPlaybackDevices().
     */
    public static function SDLGetAudioPlaybackDevices(): array
    {
        return ExtSDLAudio::SDLGetAudioPlaybackDevices();
    }

    /**
     * SDL_GetAudioRecordingDevices().
     */
    public static function SDLGetAudioRecordingDevices(): array
    {
        return ExtSDLAudio::SDLGetAudioRecordingDevices();
    }

    /**
     * SDL_GetAudioStreamAvailable().
     */
    public static function SDLGetAudioStreamAvailable(int $stream): int
    {
        return ExtSDLAudio::SDLGetAudioStreamAvailable($stream);
    }

    /**
     * SDL_GetAudioStreamData().
     */
    public static function SDLGetAudioStreamData(int $stream, int $len): string
    {
        return ExtSDLAudio::SDLGetAudioStreamData($stream, $len);
    }

    /**
     * SDL_GetAudioStreamDevice().
     */
    public static function SDLGetAudioStreamDevice(int $stream): int
    {
        return ExtSDLAudio::SDLGetAudioStreamDevice($stream);
    }

    /**
     * SDL_GetAudioStreamFormat().
     */
    public static function SDLGetAudioStreamFormat(int $stream): array
    {
        return ExtSDLAudio::SDLGetAudioStreamFormat($stream);
    }

    /**
     * SDL_GetAudioStreamFrequencyRatio().
     */
    public static function SDLGetAudioStreamFrequencyRatio(int $stream): float
    {
        return ExtSDLAudio::SDLGetAudioStreamFrequencyRatio($stream);
    }

    /**
     * SDL_GetAudioStreamGain().
     */
    public static function SDLGetAudioStreamGain(int $stream): float
    {
        return ExtSDLAudio::SDLGetAudioStreamGain($stream);
    }

    /**
     * SDL_GetAudioStreamInputChannelMap().
     */
    public static function SDLGetAudioStreamInputChannelMap(int $stream): array
    {
        return ExtSDLAudio::SDLGetAudioStreamInputChannelMap($stream);
    }

    /**
     * SDL_GetAudioStreamOutputChannelMap().
     */
    public static function SDLGetAudioStreamOutputChannelMap(int $stream): array
    {
        return ExtSDLAudio::SDLGetAudioStreamOutputChannelMap($stream);
    }

    /**
     * SDL_GetAudioStreamProperties().
     */
    public static function SDLGetAudioStreamProperties(int $stream): int
    {
        return ExtSDLAudio::SDLGetAudioStreamProperties($stream);
    }

    /**
     * SDL_GetAudioStreamQueued().
     */
    public static function SDLGetAudioStreamQueued(int $stream): int
    {
        return ExtSDLAudio::SDLGetAudioStreamQueued($stream);
    }

    /**
     * SDL_GetCurrentAudioDriver().
     */
    public static function SDLGetCurrentAudioDriver(): string
    {
        return ExtSDLAudio::SDLGetCurrentAudioDriver();
    }

    /**
     * SDL_GetNumAudioDrivers().
     */
    public static function SDLGetNumAudioDrivers(): int
    {
        return ExtSDLAudio::SDLGetNumAudioDrivers();
    }

    /**
     * SDL_GetSilenceValueForFormat().
     */
    public static function SDLGetSilenceValueForFormat(SDLAudioFormat|int $format): int
    {
        return ExtSDLAudio::SDLGetSilenceValueForFormat($format instanceof \BackedEnum ? $format->value : $format);
    }

    /**
     * SDL_IsAudioDevicePhysical().
     */
    public static function SDLIsAudioDevicePhysical(int $devid): bool
    {
        return ExtSDLAudio::SDLIsAudioDevicePhysical($devid);
    }

    /**
     * SDL_IsAudioDevicePlayback().
     */
    public static function SDLIsAudioDevicePlayback(int $devid): bool
    {
        return ExtSDLAudio::SDLIsAudioDevicePlayback($devid);
    }

    /**
     * SDL_LoadWAV().
     */
    public static function SDLLoadWAV(string $path): array
    {
        return ExtSDLAudio::SDLLoadWAV($path);
    }

    /**
     * SDL_LockAudioStream().
     */
    public static function SDLLockAudioStream(int $stream): bool
    {
        return ExtSDLAudio::SDLLockAudioStream($stream);
    }

    /**
     * SDL_MixAudio().
     */
    public static function SDLMixAudio(string $dst, string $src, SDLAudioFormat|int $format, int $len, float $volume): string
    {
        return ExtSDLAudio::SDLMixAudio($dst, $src, $format instanceof \BackedEnum ? $format->value : $format, $len, $volume);
    }

    /**
     * SDL_OpenAudioDevice().
     */
    public static function SDLOpenAudioDevice(int $devid, mixed $spec = null): int
    {
        return ExtSDLAudio::SDLOpenAudioDevice(...array_slice([$devid, $spec], 0, func_num_args()));
    }

    /**
     * SDL_OpenAudioDeviceStream().
     */
    public static function SDLOpenAudioDeviceStream(int $devid, mixed $spec = null, mixed $callback = null): int
    {
        return ExtSDLAudio::SDLOpenAudioDeviceStream(...array_slice([$devid, $spec, $callback], 0, func_num_args()));
    }

    /**
     * SDL_PauseAudioDevice().
     */
    public static function SDLPauseAudioDevice(int $devid): bool
    {
        return ExtSDLAudio::SDLPauseAudioDevice($devid);
    }

    /**
     * SDL_PauseAudioStreamDevice().
     */
    public static function SDLPauseAudioStreamDevice(int $stream): bool
    {
        return ExtSDLAudio::SDLPauseAudioStreamDevice($stream);
    }

    /**
     * SDL_PutAudioStreamData().
     */
    public static function SDLPutAudioStreamData(int $stream, string $data): bool
    {
        return ExtSDLAudio::SDLPutAudioStreamData($stream, $data);
    }

    /**
     * SDL_PutAudioStreamDataNoCopy().
     */
    public static function SDLPutAudioStreamDataNoCopy(int $stream, string $data, mixed $callback = null): bool
    {
        return ExtSDLAudio::SDLPutAudioStreamDataNoCopy(...array_slice([$stream, $data, $callback], 0, func_num_args()));
    }

    /**
     * SDL_PutAudioStreamPlanarData().
     */
    public static function SDLPutAudioStreamPlanarData(int $stream, array $channel_buffers, int $num_channels, int $num_samples): bool
    {
        return ExtSDLAudio::SDLPutAudioStreamPlanarData($stream, $channel_buffers, $num_channels, $num_samples);
    }

    /**
     * SDL_ResumeAudioDevice().
     */
    public static function SDLResumeAudioDevice(int $devid): bool
    {
        return ExtSDLAudio::SDLResumeAudioDevice($devid);
    }

    /**
     * SDL_ResumeAudioStreamDevice().
     */
    public static function SDLResumeAudioStreamDevice(int $stream): bool
    {
        return ExtSDLAudio::SDLResumeAudioStreamDevice($stream);
    }

    /**
     * SDL_SetAudioDeviceGain().
     */
    public static function SDLSetAudioDeviceGain(int $devid, float $gain): bool
    {
        return ExtSDLAudio::SDLSetAudioDeviceGain($devid, $gain);
    }

    /**
     * SDL_SetAudioPostmixCallback().
     */
    public static function SDLSetAudioPostmixCallback(int $devid, mixed $callback = null): bool
    {
        return ExtSDLAudio::SDLSetAudioPostmixCallback(...array_slice([$devid, $callback], 0, func_num_args()));
    }

    /**
     * SDL_SetAudioStreamFormat().
     */
    public static function SDLSetAudioStreamFormat(int $stream, mixed $src_spec, mixed $dst_spec): bool
    {
        return ExtSDLAudio::SDLSetAudioStreamFormat($stream, $src_spec, $dst_spec);
    }

    /**
     * SDL_SetAudioStreamFrequencyRatio().
     */
    public static function SDLSetAudioStreamFrequencyRatio(int $stream, float $ratio): bool
    {
        return ExtSDLAudio::SDLSetAudioStreamFrequencyRatio($stream, $ratio);
    }

    /**
     * SDL_SetAudioStreamGain().
     */
    public static function SDLSetAudioStreamGain(int $stream, float $gain): bool
    {
        return ExtSDLAudio::SDLSetAudioStreamGain($stream, $gain);
    }

    /**
     * SDL_SetAudioStreamGetCallback().
     */
    public static function SDLSetAudioStreamGetCallback(int $stream, mixed $callback = null): bool
    {
        return ExtSDLAudio::SDLSetAudioStreamGetCallback(...array_slice([$stream, $callback], 0, func_num_args()));
    }

    /**
     * SDL_SetAudioStreamInputChannelMap().
     */
    public static function SDLSetAudioStreamInputChannelMap(int $stream, array $chmap): bool
    {
        return ExtSDLAudio::SDLSetAudioStreamInputChannelMap($stream, $chmap);
    }

    /**
     * SDL_SetAudioStreamOutputChannelMap().
     */
    public static function SDLSetAudioStreamOutputChannelMap(int $stream, array $chmap): bool
    {
        return ExtSDLAudio::SDLSetAudioStreamOutputChannelMap($stream, $chmap);
    }

    /**
     * SDL_SetAudioStreamPutCallback().
     */
    public static function SDLSetAudioStreamPutCallback(int $stream, mixed $callback = null): bool
    {
        return ExtSDLAudio::SDLSetAudioStreamPutCallback(...array_slice([$stream, $callback], 0, func_num_args()));
    }

    /**
     * SDL_UnbindAudioStream().
     */
    public static function SDLUnbindAudioStream(int $stream): void
    {
        ExtSDLAudio::SDLUnbindAudioStream($stream);
    }

    /**
     * SDL_UnbindAudioStreams().
     */
    public static function SDLUnbindAudioStreams(array $streams): void
    {
        ExtSDLAudio::SDLUnbindAudioStreams($streams);
    }

    /**
     * SDL_UnlockAudioStream().
     */
    public static function SDLUnlockAudioStream(int $stream): bool
    {
        return ExtSDLAudio::SDLUnlockAudioStream($stream);
    }
}
