<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Video;

use Jovian\Bindings\Sdl3\Enums\SDLGLAttr;
use Sdl3\SDL\Video\SDLGL as ExtSDLGL;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Video\SDLGL
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLGL
{
    /**
     * SDL_EGL_GetCurrentConfig().
     */
    public static function SDLEGLGetCurrentConfig(): int
    {
        return ExtSDLGL::SDLEGLGetCurrentConfig();
    }

    /**
     * SDL_EGL_GetCurrentDisplay().
     */
    public static function SDLEGLGetCurrentDisplay(): int
    {
        return ExtSDLGL::SDLEGLGetCurrentDisplay();
    }

    /**
     * SDL_EGL_GetProcAddress().
     */
    public static function SDLEGLGetProcAddress(string $proc): int
    {
        return ExtSDLGL::SDLEGLGetProcAddress($proc);
    }

    /**
     * SDL_EGL_GetWindowSurface().
     */
    public static function SDLEGLGetWindowSurface(int $window): int
    {
        return ExtSDLGL::SDLEGLGetWindowSurface($window);
    }

    /**
     * SDL_EGL_SetAttributeCallbacks().
     */
    public static function SDLEGLSetAttributeCallbacks(mixed $platformCallback = null, mixed $surfaceCallback = null, mixed $contextCallback = null): void
    {
        ExtSDLGL::SDLEGLSetAttributeCallbacks(...array_slice([$platformCallback, $surfaceCallback, $contextCallback], 0, func_num_args()));
    }

    /**
     * SDL_GL_CreateContext().
     */
    public static function SDLGLCreateContext(int $window): int
    {
        return ExtSDLGL::SDLGLCreateContext($window);
    }

    /**
     * SDL_GL_DestroyContext().
     */
    public static function SDLGLDestroyContext(int $context): bool
    {
        return ExtSDLGL::SDLGLDestroyContext($context);
    }

    /**
     * SDL_GL_ExtensionSupported().
     */
    public static function SDLGLExtensionSupported(string $extension): bool
    {
        return ExtSDLGL::SDLGLExtensionSupported($extension);
    }

    /**
     * SDL_GL_GetAttribute().
     */
    public static function SDLGLGetAttribute(SDLGLAttr|int $attr): array
    {
        return ExtSDLGL::SDLGLGetAttribute($attr instanceof \BackedEnum ? $attr->value : $attr);
    }

    /**
     * SDL_GL_GetCurrentContext().
     */
    public static function SDLGLGetCurrentContext(): int
    {
        return ExtSDLGL::SDLGLGetCurrentContext();
    }

    /**
     * SDL_GL_GetCurrentWindow().
     */
    public static function SDLGLGetCurrentWindow(): int
    {
        return ExtSDLGL::SDLGLGetCurrentWindow();
    }

    /**
     * SDL_GL_GetProcAddress().
     */
    public static function SDLGLGetProcAddress(string $proc): int
    {
        return ExtSDLGL::SDLGLGetProcAddress($proc);
    }

    /**
     * SDL_GL_GetSwapInterval().
     */
    public static function SDLGLGetSwapInterval(): array
    {
        return ExtSDLGL::SDLGLGetSwapInterval();
    }

    /**
     * SDL_GL_LoadLibrary().
     */
    public static function SDLGLLoadLibrary(mixed $path = null): bool
    {
        return ExtSDLGL::SDLGLLoadLibrary(...array_slice([$path], 0, func_num_args()));
    }

    /**
     * SDL_GL_MakeCurrent().
     */
    public static function SDLGLMakeCurrent(int $window, int $context): bool
    {
        return ExtSDLGL::SDLGLMakeCurrent($window, $context);
    }

    /**
     * SDL_GL_ResetAttributes().
     */
    public static function SDLGLResetAttributes(): void
    {
        ExtSDLGL::SDLGLResetAttributes();
    }

    /**
     * SDL_GL_SetAttribute().
     */
    public static function SDLGLSetAttribute(SDLGLAttr|int $attr, int $value): bool
    {
        return ExtSDLGL::SDLGLSetAttribute($attr instanceof \BackedEnum ? $attr->value : $attr, $value);
    }

    /**
     * SDL_GL_SetSwapInterval().
     */
    public static function SDLGLSetSwapInterval(int $interval): bool
    {
        return ExtSDLGL::SDLGLSetSwapInterval($interval);
    }

    /**
     * SDL_GL_SwapWindow().
     */
    public static function SDLGLSwapWindow(int $window): bool
    {
        return ExtSDLGL::SDLGLSwapWindow($window);
    }

    /**
     * SDL_GL_UnloadLibrary().
     */
    public static function SDLGLUnloadLibrary(): void
    {
        ExtSDLGL::SDLGLUnloadLibrary();
    }
}
