<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Video;

use Sdl3\SDL\Video\SDLMetal as ExtSDLMetal;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Video\SDLMetal
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLMetal
{
    /**
     * SDL_Metal_CreateView().
     */
    public static function SDLMetalCreateView(int $window): int
    {
        return ExtSDLMetal::SDLMetalCreateView($window);
    }

    /**
     * SDL_Metal_DestroyView().
     */
    public static function SDLMetalDestroyView(int $view): void
    {
        ExtSDLMetal::SDLMetalDestroyView($view);
    }

    /**
     * SDL_Metal_GetLayer().
     */
    public static function SDLMetalGetLayer(int $view): int
    {
        return ExtSDLMetal::SDLMetalGetLayer($view);
    }
}
