<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Video;

use Sdl3\SDL\Video\SDLVulkan as ExtSDLVulkan;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Video\SDLVulkan
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLVulkan
{
    /**
     * SDL_Vulkan_CreateSurface().
     */
    public static function SDLVulkanCreateSurface(int $window, int $instance, int $allocator): int
    {
        return ExtSDLVulkan::SDLVulkanCreateSurface($window, $instance, $allocator);
    }

    /**
     * SDL_Vulkan_DestroySurface().
     */
    public static function SDLVulkanDestroySurface(int $instance, int $surface, int $allocator): void
    {
        ExtSDLVulkan::SDLVulkanDestroySurface($instance, $surface, $allocator);
    }

    /**
     * SDL_Vulkan_GetInstanceExtensions().
     */
    public static function SDLVulkanGetInstanceExtensions(): array
    {
        return ExtSDLVulkan::SDLVulkanGetInstanceExtensions();
    }

    /**
     * SDL_Vulkan_GetPresentationSupport().
     */
    public static function SDLVulkanGetPresentationSupport(int $instance, int $physical_device, int $queue_family_index): bool
    {
        return ExtSDLVulkan::SDLVulkanGetPresentationSupport($instance, $physical_device, $queue_family_index);
    }

    /**
     * SDL_Vulkan_GetVkGetInstanceProcAddr().
     */
    public static function SDLVulkanGetVkGetInstanceProcAddr(): int
    {
        return ExtSDLVulkan::SDLVulkanGetVkGetInstanceProcAddr();
    }

    /**
     * SDL_Vulkan_LoadLibrary().
     */
    public static function SDLVulkanLoadLibrary(mixed $path = null): bool
    {
        return ExtSDLVulkan::SDLVulkanLoadLibrary(...array_slice([$path], 0, func_num_args()));
    }

    /**
     * SDL_Vulkan_UnloadLibrary().
     */
    public static function SDLVulkanUnloadLibrary(): void
    {
        ExtSDLVulkan::SDLVulkanUnloadLibrary();
    }
}
