<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Video;

use Jovian\Bindings\Sdl3\Enums\SDLFlashOperation;
use Jovian\Bindings\Sdl3\Enums\SDLPixelFormat;
use Jovian\Bindings\Sdl3\Enums\SDLProgressState;
use Jovian\Bindings\Sdl3\Enums\SDLSystemTheme;
use Sdl3\SDL\Video\SDLVideo as ExtSDLVideo;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Video\SDLVideo
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLVideo
{
    /**
     * SDL_CreatePopupWindow().
     *
     * @param int $flags SDLWindowFlags bitmask; OR the enum cases' values together.
     */
    public static function SDLCreatePopupWindow(int $parent, int $offset_x, int $offset_y, int $w, int $h, int $flags): int
    {
        return ExtSDLVideo::SDLCreatePopupWindow($parent, $offset_x, $offset_y, $w, $h, $flags);
    }

    /**
     * SDL_CreateWindow().
     *
     * @param int $flags SDLWindowFlags bitmask; OR the enum cases' values together.
     */
    public static function SDLCreateWindow(string $title, int $width, int $height, int $flags): int
    {
        return ExtSDLVideo::SDLCreateWindow($title, $width, $height, $flags);
    }

    /**
     * SDL_CreateWindowAndRenderer().
     *
     * @param int $flags SDLWindowFlags bitmask; OR the enum cases' values together.
     */
    public static function SDLCreateWindowAndRenderer(string $title, int $w, int $h, int $flags): array
    {
        return ExtSDLVideo::SDLCreateWindowAndRenderer($title, $w, $h, $flags);
    }

    /**
     * SDL_CreateWindowWithProperties().
     */
    public static function SDLCreateWindowWithProperties(int $props): int
    {
        return ExtSDLVideo::SDLCreateWindowWithProperties($props);
    }

    /**
     * SDL_DestroyWindow().
     */
    public static function SDLDestroyWindow(int $window): void
    {
        ExtSDLVideo::SDLDestroyWindow($window);
    }

    /**
     * SDL_DestroyWindowSurface().
     */
    public static function SDLDestroyWindowSurface(int $window): bool
    {
        return ExtSDLVideo::SDLDestroyWindowSurface($window);
    }

    /**
     * SDL_DisableScreenSaver().
     */
    public static function SDLDisableScreenSaver(): bool
    {
        return ExtSDLVideo::SDLDisableScreenSaver();
    }

    /**
     * SDL_EnableScreenSaver().
     */
    public static function SDLEnableScreenSaver(): bool
    {
        return ExtSDLVideo::SDLEnableScreenSaver();
    }

    /**
     * SDL_FlashWindow().
     */
    public static function SDLFlashWindow(int $window, SDLFlashOperation|int $operation): bool
    {
        return ExtSDLVideo::SDLFlashWindow($window, $operation instanceof \BackedEnum ? $operation->value : $operation);
    }

    /**
     * SDL_GetCurrentVideoDriver().
     */
    public static function SDLGetCurrentVideoDriver(): string
    {
        return ExtSDLVideo::SDLGetCurrentVideoDriver();
    }

    /**
     * SDL_GetDisplayForPoint().
     */
    public static function SDLGetDisplayForPoint(int $x, int $y): int
    {
        return ExtSDLVideo::SDLGetDisplayForPoint($x, $y);
    }

    /**
     * SDL_GetDisplayForRect().
     */
    public static function SDLGetDisplayForRect(array $rect): int
    {
        return ExtSDLVideo::SDLGetDisplayForRect($rect);
    }

    /**
     * SDL_GetDisplayProperties().
     */
    public static function SDLGetDisplayProperties(int $display_id): int
    {
        return ExtSDLVideo::SDLGetDisplayProperties($display_id);
    }

    /**
     * SDL_GetDisplayUsableBounds().
     */
    public static function SDLGetDisplayUsableBounds(int $display_id): array
    {
        return ExtSDLVideo::SDLGetDisplayUsableBounds($display_id);
    }

    /**
     * SDL_GetGrabbedWindow().
     */
    public static function SDLGetGrabbedWindow(): int
    {
        return ExtSDLVideo::SDLGetGrabbedWindow();
    }

    /**
     * SDL_GetNumVideoDrivers().
     */
    public static function SDLGetNumVideoDrivers(): int
    {
        return ExtSDLVideo::SDLGetNumVideoDrivers();
    }

    /**
     * SDL_GetSystemTheme().
     */
    public static function SDLGetSystemTheme(): SDLSystemTheme|int
    {
        return ExtSDLVideo::SDLGetSystemTheme();
    }

    /**
     * SDL_GetVideoDriver().
     */
    public static function SDLGetVideoDriver(int $index): string
    {
        return ExtSDLVideo::SDLGetVideoDriver($index);
    }

    /**
     * SDL_GetWindowAspectRatio().
     */
    public static function SDLGetWindowAspectRatio(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowAspectRatio($window);
    }

    /**
     * SDL_GetWindowBordersSize().
     */
    public static function SDLGetWindowBordersSize(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowBordersSize($window);
    }

    /**
     * SDL_GetWindowDisplayScale().
     */
    public static function SDLGetWindowDisplayScale(int $window): float
    {
        return ExtSDLVideo::SDLGetWindowDisplayScale($window);
    }

    /**
     * SDL_GetWindowFlags().
     */
    public static function SDLGetWindowFlags(int $window): int
    {
        return ExtSDLVideo::SDLGetWindowFlags($window);
    }

    /**
     * SDL_GetWindowFromID().
     */
    public static function SDLGetWindowFromID(int $id): int
    {
        return ExtSDLVideo::SDLGetWindowFromID($id);
    }

    /**
     * SDL_GetWindowFullscreenMode().
     */
    public static function SDLGetWindowFullscreenMode(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowFullscreenMode($window);
    }

    /**
     * SDL_GetWindowICCProfile().
     */
    public static function SDLGetWindowICCProfile(int $window): string
    {
        return ExtSDLVideo::SDLGetWindowICCProfile($window);
    }

    /**
     * SDL_GetWindowID().
     */
    public static function SDLGetWindowID(int $window): int
    {
        return ExtSDLVideo::SDLGetWindowID($window);
    }

    /**
     * SDL_GetWindowKeyboardGrab().
     */
    public static function SDLGetWindowKeyboardGrab(int $window): bool
    {
        return ExtSDLVideo::SDLGetWindowKeyboardGrab($window);
    }

    /**
     * SDL_GetWindowMaximumSize().
     */
    public static function SDLGetWindowMaximumSize(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowMaximumSize($window);
    }

    /**
     * SDL_GetWindowMinimumSize().
     */
    public static function SDLGetWindowMinimumSize(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowMinimumSize($window);
    }

    /**
     * SDL_GetWindowMouseGrab().
     */
    public static function SDLGetWindowMouseGrab(int $window): bool
    {
        return ExtSDLVideo::SDLGetWindowMouseGrab($window);
    }

    /**
     * SDL_GetWindowMouseRect().
     */
    public static function SDLGetWindowMouseRect(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowMouseRect($window);
    }

    /**
     * SDL_GetWindowOpacity().
     */
    public static function SDLGetWindowOpacity(int $window): float
    {
        return ExtSDLVideo::SDLGetWindowOpacity($window);
    }

    /**
     * SDL_GetWindowParent().
     */
    public static function SDLGetWindowParent(int $window): int
    {
        return ExtSDLVideo::SDLGetWindowParent($window);
    }

    /**
     * SDL_GetWindowPixelDensity().
     */
    public static function SDLGetWindowPixelDensity(int $window): float
    {
        return ExtSDLVideo::SDLGetWindowPixelDensity($window);
    }

    /**
     * SDL_GetWindowPixelFormat().
     */
    public static function SDLGetWindowPixelFormat(int $window): SDLPixelFormat|int
    {
        return ExtSDLVideo::SDLGetWindowPixelFormat($window);
    }

    /**
     * SDL_GetWindowPosition().
     */
    public static function SDLGetWindowPosition(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowPosition($window);
    }

    /**
     * SDL_GetWindowProgressState().
     */
    public static function SDLGetWindowProgressState(int $window): SDLProgressState|int
    {
        return ExtSDLVideo::SDLGetWindowProgressState($window);
    }

    /**
     * SDL_GetWindowProgressValue().
     */
    public static function SDLGetWindowProgressValue(int $window): float
    {
        return ExtSDLVideo::SDLGetWindowProgressValue($window);
    }

    /**
     * SDL_GetWindowProperties().
     */
    public static function SDLGetWindowProperties(int $window): int
    {
        return ExtSDLVideo::SDLGetWindowProperties($window);
    }

    /**
     * SDL_GetWindowSafeArea().
     */
    public static function SDLGetWindowSafeArea(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowSafeArea($window);
    }

    /**
     * SDL_GetWindowSize().
     */
    public static function SDLGetWindowSize(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowSize($window);
    }

    /**
     * SDL_GetWindowSizeInPixels().
     */
    public static function SDLGetWindowSizeInPixels(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowSizeInPixels($window);
    }

    /**
     * SDL_GetWindowSurface().
     */
    public static function SDLGetWindowSurface(int $window): int
    {
        return ExtSDLVideo::SDLGetWindowSurface($window);
    }

    /**
     * SDL_GetWindowSurfaceVSync().
     */
    public static function SDLGetWindowSurfaceVSync(int $window): array
    {
        return ExtSDLVideo::SDLGetWindowSurfaceVSync($window);
    }

    /**
     * SDL_GetWindowTitle().
     */
    public static function SDLGetWindowTitle(int $window): string
    {
        return ExtSDLVideo::SDLGetWindowTitle($window);
    }

    /**
     * SDL_GetWindows().
     */
    public static function SDLGetWindows(): array
    {
        return ExtSDLVideo::SDLGetWindows();
    }

    /**
     * SDL_HideWindow().
     */
    public static function SDLHideWindow(int $window): bool
    {
        return ExtSDLVideo::SDLHideWindow($window);
    }

    /**
     * SDL_MaximizeWindow().
     */
    public static function SDLMaximizeWindow(int $window): bool
    {
        return ExtSDLVideo::SDLMaximizeWindow($window);
    }

    /**
     * SDL_MinimizeWindow().
     */
    public static function SDLMinimizeWindow(int $window): bool
    {
        return ExtSDLVideo::SDLMinimizeWindow($window);
    }

    /**
     * SDL_RaiseWindow().
     */
    public static function SDLRaiseWindow(int $window): bool
    {
        return ExtSDLVideo::SDLRaiseWindow($window);
    }

    /**
     * SDL_RestoreWindow().
     */
    public static function SDLRestoreWindow(int $window): bool
    {
        return ExtSDLVideo::SDLRestoreWindow($window);
    }

    /**
     * SDL_ScreenSaverEnabled().
     */
    public static function SDLScreenSaverEnabled(): bool
    {
        return ExtSDLVideo::SDLScreenSaverEnabled();
    }

    /**
     * SDL_SetWindowAlwaysOnTop().
     */
    public static function SDLSetWindowAlwaysOnTop(int $window, bool $on_top): bool
    {
        return ExtSDLVideo::SDLSetWindowAlwaysOnTop($window, $on_top);
    }

    /**
     * SDL_SetWindowAspectRatio().
     */
    public static function SDLSetWindowAspectRatio(int $window, float $min_aspect, float $max_aspect): bool
    {
        return ExtSDLVideo::SDLSetWindowAspectRatio($window, $min_aspect, $max_aspect);
    }

    /**
     * SDL_SetWindowBordered().
     */
    public static function SDLSetWindowBordered(int $window, bool $bordered): bool
    {
        return ExtSDLVideo::SDLSetWindowBordered($window, $bordered);
    }

    /**
     * SDL_SetWindowFillDocument().
     */
    public static function SDLSetWindowFillDocument(int $window, bool $fill): bool
    {
        return ExtSDLVideo::SDLSetWindowFillDocument($window, $fill);
    }

    /**
     * SDL_SetWindowFocusable().
     */
    public static function SDLSetWindowFocusable(int $window, bool $focusable): bool
    {
        return ExtSDLVideo::SDLSetWindowFocusable($window, $focusable);
    }

    /**
     * SDL_SetWindowFullscreen().
     */
    public static function SDLSetWindowFullscreen(int $window, bool $fullscreen): bool
    {
        return ExtSDLVideo::SDLSetWindowFullscreen($window, $fullscreen);
    }

    /**
     * SDL_SetWindowFullscreenMode().
     */
    public static function SDLSetWindowFullscreenMode(int $window, array $mode): bool
    {
        return ExtSDLVideo::SDLSetWindowFullscreenMode($window, $mode);
    }

    /**
     * SDL_SetWindowHitTest().
     */
    public static function SDLSetWindowHitTest(int $window, mixed $callback = null): bool
    {
        return ExtSDLVideo::SDLSetWindowHitTest(...array_slice([$window, $callback], 0, func_num_args()));
    }

    /**
     * SDL_SetWindowIcon().
     */
    public static function SDLSetWindowIcon(int $window, int $surface): bool
    {
        return ExtSDLVideo::SDLSetWindowIcon($window, $surface);
    }

    /**
     * SDL_SetWindowKeyboardGrab().
     */
    public static function SDLSetWindowKeyboardGrab(int $window, bool $grabbed): bool
    {
        return ExtSDLVideo::SDLSetWindowKeyboardGrab($window, $grabbed);
    }

    /**
     * SDL_SetWindowMaximumSize().
     */
    public static function SDLSetWindowMaximumSize(int $window, int $max_w, int $max_h): bool
    {
        return ExtSDLVideo::SDLSetWindowMaximumSize($window, $max_w, $max_h);
    }

    /**
     * SDL_SetWindowMinimumSize().
     */
    public static function SDLSetWindowMinimumSize(int $window, int $min_w, int $min_h): bool
    {
        return ExtSDLVideo::SDLSetWindowMinimumSize($window, $min_w, $min_h);
    }

    /**
     * SDL_SetWindowModal().
     */
    public static function SDLSetWindowModal(int $window, bool $modal): bool
    {
        return ExtSDLVideo::SDLSetWindowModal($window, $modal);
    }

    /**
     * SDL_SetWindowMouseGrab().
     */
    public static function SDLSetWindowMouseGrab(int $window, bool $grabbed): bool
    {
        return ExtSDLVideo::SDLSetWindowMouseGrab($window, $grabbed);
    }

    /**
     * SDL_SetWindowMouseRect().
     */
    public static function SDLSetWindowMouseRect(int $window, mixed $rect = null): bool
    {
        return ExtSDLVideo::SDLSetWindowMouseRect(...array_slice([$window, $rect], 0, func_num_args()));
    }

    /**
     * SDL_SetWindowOpacity().
     */
    public static function SDLSetWindowOpacity(int $window, float $opacity): bool
    {
        return ExtSDLVideo::SDLSetWindowOpacity($window, $opacity);
    }

    /**
     * SDL_SetWindowParent().
     */
    public static function SDLSetWindowParent(int $window, mixed $parent = null): bool
    {
        return ExtSDLVideo::SDLSetWindowParent(...array_slice([$window, $parent], 0, func_num_args()));
    }

    /**
     * SDL_SetWindowPosition().
     */
    public static function SDLSetWindowPosition(int $window, int $x, int $y): bool
    {
        return ExtSDLVideo::SDLSetWindowPosition($window, $x, $y);
    }

    /**
     * SDL_SetWindowProgressState().
     */
    public static function SDLSetWindowProgressState(int $window, SDLProgressState|int $state): bool
    {
        return ExtSDLVideo::SDLSetWindowProgressState($window, $state instanceof \BackedEnum ? $state->value : $state);
    }

    /**
     * SDL_SetWindowProgressValue().
     */
    public static function SDLSetWindowProgressValue(int $window, float $value): bool
    {
        return ExtSDLVideo::SDLSetWindowProgressValue($window, $value);
    }

    /**
     * SDL_SetWindowResizable().
     */
    public static function SDLSetWindowResizable(int $window, bool $resizable): bool
    {
        return ExtSDLVideo::SDLSetWindowResizable($window, $resizable);
    }

    /**
     * SDL_SetWindowShape().
     */
    public static function SDLSetWindowShape(int $window, mixed $shape = null): bool
    {
        return ExtSDLVideo::SDLSetWindowShape(...array_slice([$window, $shape], 0, func_num_args()));
    }

    /**
     * SDL_SetWindowSize().
     */
    public static function SDLSetWindowSize(int $window, int $w, int $h): bool
    {
        return ExtSDLVideo::SDLSetWindowSize($window, $w, $h);
    }

    /**
     * SDL_SetWindowSurfaceVSync().
     */
    public static function SDLSetWindowSurfaceVSync(int $window, int $vsync): bool
    {
        return ExtSDLVideo::SDLSetWindowSurfaceVSync($window, $vsync);
    }

    /**
     * SDL_SetWindowTitle().
     */
    public static function SDLSetWindowTitle(int $window, string $title): bool
    {
        return ExtSDLVideo::SDLSetWindowTitle($window, $title);
    }

    /**
     * SDL_ShowWindow().
     */
    public static function SDLShowWindow(int $window): bool
    {
        return ExtSDLVideo::SDLShowWindow($window);
    }

    /**
     * SDL_ShowWindowSystemMenu().
     */
    public static function SDLShowWindowSystemMenu(int $window, int $x, int $y): bool
    {
        return ExtSDLVideo::SDLShowWindowSystemMenu($window, $x, $y);
    }

    /**
     * SDL_SyncWindow().
     */
    public static function SDLSyncWindow(int $window): bool
    {
        return ExtSDLVideo::SDLSyncWindow($window);
    }

    /**
     * SDL_UpdateWindowSurface().
     */
    public static function SDLUpdateWindowSurface(int $window): bool
    {
        return ExtSDLVideo::SDLUpdateWindowSurface($window);
    }

    /**
     * SDL_UpdateWindowSurfaceRects().
     */
    public static function SDLUpdateWindowSurfaceRects(int $window, array $rects): bool
    {
        return ExtSDLVideo::SDLUpdateWindowSurfaceRects($window, $rects);
    }

    /**
     * SDL_WindowHasSurface().
     */
    public static function SDLWindowHasSurface(int $window): bool
    {
        return ExtSDLVideo::SDLWindowHasSurface($window);
    }
}
