<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3;

use Jovian\Bindings\Sdl3\Enums\SDLPixelFormat;
use Jovian\Bindings\Sdl3\Enums\SDLSandbox;
use Sdl3\SDL\SDL as ExtSDL;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\SDL
 * from ext-sdl3 0.7.0, one method per extension call.
 */
final class SDL
{
    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function SDLExitProcess(int $exitcode): void
    {
        ExtSDL::SDLExitProcess($exitcode);
    }

    /**
     * SDL_GetAppMetadataProperty().
     */
    public static function SDLGetAppMetadataProperty(string $name): string
    {
        return ExtSDL::SDLGetAppMetadataProperty($name);
    }

    /**
     * SDL_GetPixelFormatDetails().
     */
    public static function SDLGetPixelFormatDetails(SDLPixelFormat|int $format): array
    {
        return ExtSDL::SDLGetPixelFormatDetails($format instanceof \BackedEnum ? $format->value : $format);
    }

    /**
     * SDL_GetPlatform().
     */
    public static function SDLGetPlatform(): string
    {
        return ExtSDL::SDLGetPlatform();
    }

    /**
     * SDL_GetRGBA().
     */
    public static function SDLGetRGBA(int $pixel, int $format_ptr, mixed $palette_ptr = null): array
    {
        return ExtSDL::SDLGetRGBA(...array_slice([$pixel, $format_ptr, $palette_ptr], 0, func_num_args()));
    }

    /**
     * SDL_GetRevision().
     */
    public static function SDLGetRevision(): string
    {
        return ExtSDL::SDLGetRevision();
    }

    /**
     * SDL_GetSandbox().
     */
    public static function SDLGetSandbox(): SDLSandbox|int
    {
        return ExtSDL::SDLGetSandbox();
    }

    /**
     * SDL_GetVersion().
     */
    public static function SDLGetVersion(): int
    {
        return ExtSDL::SDLGetVersion();
    }

    /**
     * SDL_Init().
     *
     * @param int $flags SDLInitFlags bitmask; OR the enum cases' values together.
     */
    public static function SDLInit(int $flags): bool
    {
        return ExtSDL::SDLInit($flags);
    }

    /**
     * SDL_InitSubSystem().
     *
     * @param int $flags SDLInitFlags bitmask; OR the enum cases' values together.
     */
    public static function SDLInitSubSystem(int $flags): bool
    {
        return ExtSDL::SDLInitSubSystem($flags);
    }

    /**
     * SDL_IsMainThread().
     */
    public static function SDLIsMainThread(): bool
    {
        return ExtSDL::SDLIsMainThread();
    }

    /**
     * SDL_IsTV().
     */
    public static function SDLIsTV(): bool
    {
        return ExtSDL::SDLIsTV();
    }

    /**
     * SDL_IsTablet().
     */
    public static function SDLIsTablet(): bool
    {
        return ExtSDL::SDLIsTablet();
    }

    /**
     * SDL_MapRGBA().
     */
    public static function SDLMapRGBA(int $format_ptr, mixed $palette_ptr, int $r, int $g, int $b, int $a = 0): int
    {
        return ExtSDL::SDLMapRGBA(...array_slice([$format_ptr, $palette_ptr, $r, $g, $b, $a], 0, func_num_args()));
    }

    /**
     * SDL_Quit().
     */
    public static function SDLQuit(): void
    {
        ExtSDL::SDLQuit();
    }

    /**
     * SDL_QuitSubSystem().
     *
     * @param int $flags SDLInitFlags bitmask; OR the enum cases' values together.
     */
    public static function SDLQuitSubSystem(int $flags): void
    {
        ExtSDL::SDLQuitSubSystem($flags);
    }

    /**
     * SDL_rand().
     */
    public static function SDLRand(int $n): int
    {
        return ExtSDL::SDLRand($n);
    }

    /**
     * SDL_randf().
     */
    public static function SDLRandf(): float
    {
        return ExtSDL::SDLRandf();
    }

    /**
     * SDL_SetAppMetadata().
     */
    public static function SDLSetAppMetadata(string $appname, string $appversion, string $appidentifier): bool
    {
        return ExtSDL::SDLSetAppMetadata($appname, $appversion, $appidentifier);
    }

    /**
     * SDL_SetAppMetadataProperty().
     */
    public static function SDLSetAppMetadataProperty(string $name, string $value): bool
    {
        return ExtSDL::SDLSetAppMetadataProperty($name, $value);
    }

    /**
     * SDL_SetMainReady().
     */
    public static function SDLSetMainReady(): void
    {
        ExtSDL::SDLSetMainReady();
    }

    /**
     * SDL_WasInit().
     *
     * @param int $flags SDLInitFlags bitmask; OR the enum cases' values together.
     */
    public static function SDLWasInit(int $flags): int
    {
        return ExtSDL::SDLWasInit($flags);
    }
}
