<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3;

use Sdl3\SDL\SDLError as ExtSDLError;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\SDLError
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLError
{
    /**
     * SDL_ClearError().
     */
    public static function SDLClearError(): bool
    {
        return ExtSDLError::SDLClearError();
    }

    /**
     * SDL_GetError().
     */
    public static function SDLGetError(): string
    {
        return ExtSDLError::SDLGetError();
    }

    /**
     * SDL_OutOfMemory().
     */
    public static function SDLOutOfMemory(): bool
    {
        return ExtSDLError::SDLOutOfMemory();
    }

    /**
     * SDL_SetError().
     */
    public static function SDLSetError(string $message): bool
    {
        return ExtSDLError::SDLSetError($message);
    }
}
