<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3;

use Sdl3\SDL\SDLLog as ExtSDLLog;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\SDLLog
 * from ext-sdl3 0.8.0, one method per extension call.
 *
 * The extension declares this class with no public methods at 0.8.0.
 * It is projected empty rather than omitted, so the parity gate can
 * see that the class exists and that nothing was silently skipped.
 */
final class SDLLog
{
}
