<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3;

use Jovian\Bindings\Sdl3\Enums\SDLPropertyType;
use Sdl3\SDL\SDLProperties as ExtSDLProperties;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\SDLProperties
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLProperties
{
    /**
     * SDL_ClearProperty().
     */
    public static function SDLClearProperty(int $props, string $name): bool
    {
        return ExtSDLProperties::SDLClearProperty($props, $name);
    }

    /**
     * SDL_CopyProperties().
     */
    public static function SDLCopyProperties(int $src, int $dst): bool
    {
        return ExtSDLProperties::SDLCopyProperties($src, $dst);
    }

    /**
     * SDL_CreateProperties().
     */
    public static function SDLCreateProperties(): int
    {
        return ExtSDLProperties::SDLCreateProperties();
    }

    /**
     * SDL_DestroyProperties().
     */
    public static function SDLDestroyProperties(int $props): void
    {
        ExtSDLProperties::SDLDestroyProperties($props);
    }

    /**
     * SDL_EnumerateProperties().
     */
    public static function SDLEnumerateProperties(int $props, mixed $callback): bool
    {
        return ExtSDLProperties::SDLEnumerateProperties($props, $callback);
    }

    /**
     * SDL_GetBooleanProperty().
     */
    public static function SDLGetBooleanProperty(int $props, string $name, bool $defaultValue): bool
    {
        return ExtSDLProperties::SDLGetBooleanProperty($props, $name, $defaultValue);
    }

    /**
     * SDL_GetFloatProperty().
     */
    public static function SDLGetFloatProperty(int $props, string $name, float $defaultValue): float
    {
        return ExtSDLProperties::SDLGetFloatProperty($props, $name, $defaultValue);
    }

    /**
     * SDL_GetGlobalProperties().
     */
    public static function SDLGetGlobalProperties(): int
    {
        return ExtSDLProperties::SDLGetGlobalProperties();
    }

    /**
     * SDL_GetNumberProperty().
     */
    public static function SDLGetNumberProperty(int $props, string $name, int $defaultValue): int
    {
        return ExtSDLProperties::SDLGetNumberProperty($props, $name, $defaultValue);
    }

    /**
     * SDL_GetPointerProperty().
     */
    public static function SDLGetPointerProperty(int $props, string $name, mixed $defaultValue = null): int
    {
        return ExtSDLProperties::SDLGetPointerProperty(...array_slice([$props, $name, $defaultValue], 0, func_num_args()));
    }

    /**
     * SDL_GetPropertyType().
     */
    public static function SDLGetPropertyType(int $props, string $name): SDLPropertyType|int
    {
        return ExtSDLProperties::SDLGetPropertyType($props, $name);
    }

    /**
     * SDL_GetStringProperty().
     */
    public static function SDLGetStringProperty(int $props, string $name, mixed $defaultValue = null): string
    {
        return ExtSDLProperties::SDLGetStringProperty(...array_slice([$props, $name, $defaultValue], 0, func_num_args()));
    }

    /**
     * SDL_HasProperty().
     */
    public static function SDLHasProperty(int $props, string $name): bool
    {
        return ExtSDLProperties::SDLHasProperty($props, $name);
    }

    /**
     * SDL_LockProperties().
     */
    public static function SDLLockProperties(int $props): bool
    {
        return ExtSDLProperties::SDLLockProperties($props);
    }

    /**
     * SDL_SetBooleanProperty().
     */
    public static function SDLSetBooleanProperty(int $props, string $name, bool $value): bool
    {
        return ExtSDLProperties::SDLSetBooleanProperty($props, $name, $value);
    }

    /**
     * SDL_SetFloatProperty().
     */
    public static function SDLSetFloatProperty(int $props, string $name, float $value): bool
    {
        return ExtSDLProperties::SDLSetFloatProperty($props, $name, $value);
    }

    /**
     * SDL_SetNumberProperty().
     */
    public static function SDLSetNumberProperty(int $props, string $name, int $value): bool
    {
        return ExtSDLProperties::SDLSetNumberProperty($props, $name, $value);
    }

    /**
     * SDL_SetPointerProperty().
     */
    public static function SDLSetPointerProperty(int $props, string $name, mixed $value = null): bool
    {
        return ExtSDLProperties::SDLSetPointerProperty(...array_slice([$props, $name, $value], 0, func_num_args()));
    }

    /**
     * SDL_SetStringProperty().
     */
    public static function SDLSetStringProperty(int $props, string $name, mixed $value = null): bool
    {
        return ExtSDLProperties::SDLSetStringProperty(...array_slice([$props, $name, $value], 0, func_num_args()));
    }

    /**
     * SDL_UnlockProperties().
     */
    public static function SDLUnlockProperties(int $props): void
    {
        ExtSDLProperties::SDLUnlockProperties($props);
    }
}
