<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3;

use Sdl3\SDL\SDLUtils as ExtSDLUtils;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\SDLUtils
 * from ext-sdl3 0.7.0, one method per extension call.
 *
 * The extension declares this class with no public methods at 0.7.0.
 * It is projected empty rather than omitted, so the parity gate can
 * see that the class exists and that nothing was silently skipped.
 */
final class SDLUtils
{
}
