<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Gpu;

use Jovian\Bindings\Sdl3\Enums\SDLGPUIndexElementSize;
use Jovian\Bindings\Sdl3\Enums\SDLGPUPresentMode;
use Jovian\Bindings\Sdl3\Enums\SDLGPUSampleCount;
use Jovian\Bindings\Sdl3\Enums\SDLGPUSwapchainComposition;
use Jovian\Bindings\Sdl3\Enums\SDLGPUTextureFormat;
use Jovian\Bindings\Sdl3\Enums\SDLGPUTextureType;
use Jovian\Bindings\Sdl3\Enums\SDLPixelFormat;
use Sdl3\SDL\Gpu\SDLGPU as ExtSDLGPU;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Gpu\SDLGPU
 * from ext-sdl3 0.7.0, one method per extension call.
 */
final class SDLGPU
{
    /**
     * SDL_AcquireGPUCommandBuffer().
     */
    public static function SDLAcquireGPUCommandBuffer(int $device): int
    {
        return ExtSDLGPU::SDLAcquireGPUCommandBuffer($device);
    }

    /**
     * SDL_AcquireGPUSwapchainTexture().
     */
    public static function SDLAcquireGPUSwapchainTexture(int $command_buffer, int $window): array
    {
        return ExtSDLGPU::SDLAcquireGPUSwapchainTexture($command_buffer, $window);
    }

    /**
     * SDL_BeginGPUComputePass().
     */
    public static function SDLBeginGPUComputePass(int $command_buffer, mixed $storage_texture_bindings = null, mixed $storage_buffer_bindings = null): int
    {
        return ExtSDLGPU::SDLBeginGPUComputePass(...array_slice([$command_buffer, $storage_texture_bindings, $storage_buffer_bindings], 0, func_num_args()));
    }

    /**
     * SDL_BeginGPUCopyPass().
     */
    public static function SDLBeginGPUCopyPass(int $command_buffer): int
    {
        return ExtSDLGPU::SDLBeginGPUCopyPass($command_buffer);
    }

    /**
     * SDL_BeginGPURenderPass().
     */
    public static function SDLBeginGPURenderPass(int $command_buffer, mixed $color_target_infos, mixed $depth_stencil_target_info = null): int
    {
        return ExtSDLGPU::SDLBeginGPURenderPass(...array_slice([$command_buffer, $color_target_infos, $depth_stencil_target_info], 0, func_num_args()));
    }

    /**
     * SDL_BindGPUComputePipeline().
     */
    public static function SDLBindGPUComputePipeline(int $compute_pass, int $compute_pipeline): void
    {
        ExtSDLGPU::SDLBindGPUComputePipeline($compute_pass, $compute_pipeline);
    }

    /**
     * SDL_BindGPUComputeSamplers().
     */
    public static function SDLBindGPUComputeSamplers(int $compute_pass, int $first_slot, mixed $bindings): void
    {
        ExtSDLGPU::SDLBindGPUComputeSamplers($compute_pass, $first_slot, $bindings);
    }

    /**
     * SDL_BindGPUComputeStorageBuffers().
     */
    public static function SDLBindGPUComputeStorageBuffers(int $compute_pass, int $first_slot, mixed $storage_buffers): void
    {
        ExtSDLGPU::SDLBindGPUComputeStorageBuffers($compute_pass, $first_slot, $storage_buffers);
    }

    /**
     * SDL_BindGPUComputeStorageTextures().
     */
    public static function SDLBindGPUComputeStorageTextures(int $compute_pass, int $first_slot, mixed $storage_textures): void
    {
        ExtSDLGPU::SDLBindGPUComputeStorageTextures($compute_pass, $first_slot, $storage_textures);
    }

    /**
     * SDL_BindGPUFragmentSamplers().
     */
    public static function SDLBindGPUFragmentSamplers(int $render_pass, int $first_slot, mixed $bindings): void
    {
        ExtSDLGPU::SDLBindGPUFragmentSamplers($render_pass, $first_slot, $bindings);
    }

    /**
     * SDL_BindGPUFragmentStorageBuffers().
     */
    public static function SDLBindGPUFragmentStorageBuffers(int $render_pass, int $first_slot, mixed $storage_buffers): void
    {
        ExtSDLGPU::SDLBindGPUFragmentStorageBuffers($render_pass, $first_slot, $storage_buffers);
    }

    /**
     * SDL_BindGPUFragmentStorageTextures().
     */
    public static function SDLBindGPUFragmentStorageTextures(int $render_pass, int $first_slot, mixed $storage_textures): void
    {
        ExtSDLGPU::SDLBindGPUFragmentStorageTextures($render_pass, $first_slot, $storage_textures);
    }

    /**
     * SDL_BindGPUGraphicsPipeline().
     */
    public static function SDLBindGPUGraphicsPipeline(int $render_pass, int $graphics_pipeline): void
    {
        ExtSDLGPU::SDLBindGPUGraphicsPipeline($render_pass, $graphics_pipeline);
    }

    /**
     * SDL_BindGPUIndexBuffer().
     */
    public static function SDLBindGPUIndexBuffer(int $render_pass, mixed $binding, SDLGPUIndexElementSize|int $index_element_size): void
    {
        ExtSDLGPU::SDLBindGPUIndexBuffer($render_pass, $binding, $index_element_size instanceof \BackedEnum ? $index_element_size->value : $index_element_size);
    }

    /**
     * SDL_BindGPUVertexBuffers().
     */
    public static function SDLBindGPUVertexBuffers(int $render_pass, int $first_slot, mixed $bindings): void
    {
        ExtSDLGPU::SDLBindGPUVertexBuffers($render_pass, $first_slot, $bindings);
    }

    /**
     * SDL_BindGPUVertexSamplers().
     */
    public static function SDLBindGPUVertexSamplers(int $render_pass, int $first_slot, mixed $bindings): void
    {
        ExtSDLGPU::SDLBindGPUVertexSamplers($render_pass, $first_slot, $bindings);
    }

    /**
     * SDL_BindGPUVertexStorageBuffers().
     */
    public static function SDLBindGPUVertexStorageBuffers(int $render_pass, int $first_slot, mixed $storage_buffers): void
    {
        ExtSDLGPU::SDLBindGPUVertexStorageBuffers($render_pass, $first_slot, $storage_buffers);
    }

    /**
     * SDL_BindGPUVertexStorageTextures().
     */
    public static function SDLBindGPUVertexStorageTextures(int $render_pass, int $first_slot, mixed $storage_textures): void
    {
        ExtSDLGPU::SDLBindGPUVertexStorageTextures($render_pass, $first_slot, $storage_textures);
    }

    /**
     * SDL_BlitGPUTexture().
     */
    public static function SDLBlitGPUTexture(int $command_buffer, mixed $info): void
    {
        ExtSDLGPU::SDLBlitGPUTexture($command_buffer, $info);
    }

    /**
     * SDL_CalculateGPUTextureFormatSize().
     */
    public static function SDLCalculateGPUTextureFormatSize(SDLGPUTextureFormat|int $format, int $width, int $height, int $depth_or_layer_count): int
    {
        return ExtSDLGPU::SDLCalculateGPUTextureFormatSize($format instanceof \BackedEnum ? $format->value : $format, $width, $height, $depth_or_layer_count);
    }

    /**
     * SDL_CancelGPUCommandBuffer().
     */
    public static function SDLCancelGPUCommandBuffer(int $command_buffer): bool
    {
        return ExtSDLGPU::SDLCancelGPUCommandBuffer($command_buffer);
    }

    /**
     * SDL_ClaimWindowForGPUDevice().
     */
    public static function SDLClaimWindowForGPUDevice(int $device, int $window): bool
    {
        return ExtSDLGPU::SDLClaimWindowForGPUDevice($device, $window);
    }

    /**
     * SDL_CopyGPUBufferToBuffer().
     */
    public static function SDLCopyGPUBufferToBuffer(int $copy_pass, mixed $source, mixed $destination, int $size, bool $cycle = false): void
    {
        ExtSDLGPU::SDLCopyGPUBufferToBuffer(...array_slice([$copy_pass, $source, $destination, $size, $cycle], 0, func_num_args()));
    }

    /**
     * SDL_CopyGPUTextureToTexture().
     */
    public static function SDLCopyGPUTextureToTexture(int $copy_pass, mixed $source, mixed $destination, int $w, int $h, int $d, bool $cycle = false): void
    {
        ExtSDLGPU::SDLCopyGPUTextureToTexture(...array_slice([$copy_pass, $source, $destination, $w, $h, $d, $cycle], 0, func_num_args()));
    }

    /**
     * SDL_CreateGPUBuffer().
     */
    public static function SDLCreateGPUBuffer(int $device, mixed $createinfo): int
    {
        return ExtSDLGPU::SDLCreateGPUBuffer($device, $createinfo);
    }

    /**
     * SDL_CreateGPUComputePipeline().
     */
    public static function SDLCreateGPUComputePipeline(int $device, mixed $createinfo): int
    {
        return ExtSDLGPU::SDLCreateGPUComputePipeline($device, $createinfo);
    }

    /**
     * SDL_CreateGPUDevice().
     *
     * @param int $format_flags SDLGPUShaderFormat bitmask; OR the enum cases' values together.
     */
    public static function SDLCreateGPUDevice(int $format_flags, bool $debug_mode, mixed $name = null): int
    {
        return ExtSDLGPU::SDLCreateGPUDevice(...array_slice([$format_flags, $debug_mode, $name], 0, func_num_args()));
    }

    /**
     * SDL_CreateGPUDeviceWithProperties().
     */
    public static function SDLCreateGPUDeviceWithProperties(int $props): int
    {
        return ExtSDLGPU::SDLCreateGPUDeviceWithProperties($props);
    }

    /**
     * SDL_CreateGPUGraphicsPipeline().
     */
    public static function SDLCreateGPUGraphicsPipeline(int $device, mixed $createinfo): int
    {
        return ExtSDLGPU::SDLCreateGPUGraphicsPipeline($device, $createinfo);
    }

    /**
     * SDL_CreateGPURenderState().
     */
    public static function SDLCreateGPURenderState(int $renderer, mixed $createinfo): int
    {
        return ExtSDLGPU::SDLCreateGPURenderState($renderer, $createinfo);
    }

    /**
     * SDL_CreateGPURenderer().
     */
    public static function SDLCreateGPURenderer(int $device, int $window): int
    {
        return ExtSDLGPU::SDLCreateGPURenderer($device, $window);
    }

    /**
     * SDL_CreateGPUSampler().
     */
    public static function SDLCreateGPUSampler(int $device, mixed $createinfo): int
    {
        return ExtSDLGPU::SDLCreateGPUSampler($device, $createinfo);
    }

    /**
     * SDL_CreateGPUShader().
     */
    public static function SDLCreateGPUShader(int $device, mixed $createinfo): int
    {
        return ExtSDLGPU::SDLCreateGPUShader($device, $createinfo);
    }

    /**
     * SDL_CreateGPUTexture().
     */
    public static function SDLCreateGPUTexture(int $device, mixed $createinfo): int
    {
        return ExtSDLGPU::SDLCreateGPUTexture($device, $createinfo);
    }

    /**
     * SDL_CreateGPUTransferBuffer().
     */
    public static function SDLCreateGPUTransferBuffer(int $device, mixed $createinfo): int
    {
        return ExtSDLGPU::SDLCreateGPUTransferBuffer($device, $createinfo);
    }

    /**
     * SDL_DestroyGPUDevice().
     */
    public static function SDLDestroyGPUDevice(int $device): void
    {
        ExtSDLGPU::SDLDestroyGPUDevice($device);
    }

    /**
     * SDL_DestroyGPURenderState().
     */
    public static function SDLDestroyGPURenderState(int $state): void
    {
        ExtSDLGPU::SDLDestroyGPURenderState($state);
    }

    /**
     * SDL_DispatchGPUCompute().
     */
    public static function SDLDispatchGPUCompute(int $compute_pass, int $groupcount_x, int $groupcount_y, int $groupcount_z): void
    {
        ExtSDLGPU::SDLDispatchGPUCompute($compute_pass, $groupcount_x, $groupcount_y, $groupcount_z);
    }

    /**
     * SDL_DispatchGPUComputeIndirect().
     */
    public static function SDLDispatchGPUComputeIndirect(int $compute_pass, int $buffer, int $offset): void
    {
        ExtSDLGPU::SDLDispatchGPUComputeIndirect($compute_pass, $buffer, $offset);
    }

    /**
     * SDL_DownloadFromGPUBuffer().
     */
    public static function SDLDownloadFromGPUBuffer(int $copy_pass, mixed $source, mixed $destination): void
    {
        ExtSDLGPU::SDLDownloadFromGPUBuffer($copy_pass, $source, $destination);
    }

    /**
     * SDL_DownloadFromGPUTexture().
     */
    public static function SDLDownloadFromGPUTexture(int $copy_pass, mixed $source, mixed $destination): void
    {
        ExtSDLGPU::SDLDownloadFromGPUTexture($copy_pass, $source, $destination);
    }

    /**
     * SDL_DrawGPUIndexedPrimitives().
     */
    public static function SDLDrawGPUIndexedPrimitives(int $render_pass, int $num_indices, int $num_instances, int $first_index, int $vertex_offset, int $first_instance): void
    {
        ExtSDLGPU::SDLDrawGPUIndexedPrimitives($render_pass, $num_indices, $num_instances, $first_index, $vertex_offset, $first_instance);
    }

    /**
     * SDL_DrawGPUIndexedPrimitivesIndirect().
     */
    public static function SDLDrawGPUIndexedPrimitivesIndirect(int $render_pass, int $buffer, int $offset, int $draw_count): void
    {
        ExtSDLGPU::SDLDrawGPUIndexedPrimitivesIndirect($render_pass, $buffer, $offset, $draw_count);
    }

    /**
     * SDL_DrawGPUPrimitives().
     */
    public static function SDLDrawGPUPrimitives(int $render_pass, int $num_vertices, int $num_instances, int $first_vertex, int $first_instance): void
    {
        ExtSDLGPU::SDLDrawGPUPrimitives($render_pass, $num_vertices, $num_instances, $first_vertex, $first_instance);
    }

    /**
     * SDL_DrawGPUPrimitivesIndirect().
     */
    public static function SDLDrawGPUPrimitivesIndirect(int $render_pass, int $buffer, int $offset, int $draw_count): void
    {
        ExtSDLGPU::SDLDrawGPUPrimitivesIndirect($render_pass, $buffer, $offset, $draw_count);
    }

    /**
     * SDL_EndGPUComputePass().
     */
    public static function SDLEndGPUComputePass(int $compute_pass): void
    {
        ExtSDLGPU::SDLEndGPUComputePass($compute_pass);
    }

    /**
     * SDL_EndGPUCopyPass().
     */
    public static function SDLEndGPUCopyPass(int $copy_pass): void
    {
        ExtSDLGPU::SDLEndGPUCopyPass($copy_pass);
    }

    /**
     * SDL_EndGPURenderPass().
     */
    public static function SDLEndGPURenderPass(int $render_pass): void
    {
        ExtSDLGPU::SDLEndGPURenderPass($render_pass);
    }

    /**
     * SDL_GDKResumeGPU().
     */
    public static function SDLGDKResumeGPU(int $device): void
    {
        ExtSDLGPU::SDLGDKResumeGPU($device);
    }

    /**
     * SDL_GDKSuspendGPU().
     */
    public static function SDLGDKSuspendGPU(int $device): void
    {
        ExtSDLGPU::SDLGDKSuspendGPU($device);
    }

    /**
     * SDL_GPUSupportsProperties().
     */
    public static function SDLGPUSupportsProperties(int $props): bool
    {
        return ExtSDLGPU::SDLGPUSupportsProperties($props);
    }

    /**
     * SDL_GPUSupportsShaderFormats().
     *
     * @param int $format_flags SDLGPUShaderFormat bitmask; OR the enum cases' values together.
     */
    public static function SDLGPUSupportsShaderFormats(int $format_flags, mixed $name = null): bool
    {
        return ExtSDLGPU::SDLGPUSupportsShaderFormats(...array_slice([$format_flags, $name], 0, func_num_args()));
    }

    /**
     * SDL_GPUTextureFormatTexelBlockSize().
     */
    public static function SDLGPUTextureFormatTexelBlockSize(SDLGPUTextureFormat|int $format): int
    {
        return ExtSDLGPU::SDLGPUTextureFormatTexelBlockSize($format instanceof \BackedEnum ? $format->value : $format);
    }

    /**
     * SDL_GPUTextureSupportsFormat().
     *
     * @param int $usage SDLGPUTextureUsageFlags bitmask; OR the enum cases' values together.
     */
    public static function SDLGPUTextureSupportsFormat(int $device, SDLGPUTextureFormat|int $format, SDLGPUTextureType|int $type, int $usage): bool
    {
        return ExtSDLGPU::SDLGPUTextureSupportsFormat($device, $format instanceof \BackedEnum ? $format->value : $format, $type instanceof \BackedEnum ? $type->value : $type, $usage);
    }

    /**
     * SDL_GPUTextureSupportsSampleCount().
     */
    public static function SDLGPUTextureSupportsSampleCount(int $device, SDLGPUTextureFormat|int $format, SDLGPUSampleCount|int $sample_count): bool
    {
        return ExtSDLGPU::SDLGPUTextureSupportsSampleCount($device, $format instanceof \BackedEnum ? $format->value : $format, $sample_count instanceof \BackedEnum ? $sample_count->value : $sample_count);
    }

    /**
     * SDL_GenerateMipmapsForGPUTexture().
     */
    public static function SDLGenerateMipmapsForGPUTexture(int $command_buffer, int $texture): void
    {
        ExtSDLGPU::SDLGenerateMipmapsForGPUTexture($command_buffer, $texture);
    }

    /**
     * SDL_GetGPUDeviceDriver().
     */
    public static function SDLGetGPUDeviceDriver(int $device): string
    {
        return ExtSDLGPU::SDLGetGPUDeviceDriver($device);
    }

    /**
     * SDL_GetGPUDeviceProperties().
     */
    public static function SDLGetGPUDeviceProperties(int $device): int
    {
        return ExtSDLGPU::SDLGetGPUDeviceProperties($device);
    }

    /**
     * SDL_GetGPUDriver().
     */
    public static function SDLGetGPUDriver(int $index): string
    {
        return ExtSDLGPU::SDLGetGPUDriver($index);
    }

    /**
     * SDL_GetGPURendererDevice().
     */
    public static function SDLGetGPURendererDevice(int $renderer): int
    {
        return ExtSDLGPU::SDLGetGPURendererDevice($renderer);
    }

    /**
     * SDL_GetGPUShaderFormats().
     */
    public static function SDLGetGPUShaderFormats(int $device): int
    {
        return ExtSDLGPU::SDLGetGPUShaderFormats($device);
    }

    /**
     * SDL_GetGPUSwapchainTextureFormat().
     */
    public static function SDLGetGPUSwapchainTextureFormat(int $device, int $window): SDLGPUTextureFormat|int
    {
        return ExtSDLGPU::SDLGetGPUSwapchainTextureFormat($device, $window);
    }

    /**
     * SDL_GetGPUTextureFormatFromPixelFormat().
     */
    public static function SDLGetGPUTextureFormatFromPixelFormat(SDLPixelFormat|int $format): SDLGPUTextureFormat|int
    {
        return ExtSDLGPU::SDLGetGPUTextureFormatFromPixelFormat($format instanceof \BackedEnum ? $format->value : $format);
    }

    /**
     * SDL_GetNumGPUDrivers().
     */
    public static function SDLGetNumGPUDrivers(): int
    {
        return ExtSDLGPU::SDLGetNumGPUDrivers();
    }

    /**
     * SDL_GetPixelFormatFromGPUTextureFormat().
     */
    public static function SDLGetPixelFormatFromGPUTextureFormat(SDLGPUTextureFormat|int $format): SDLPixelFormat|int
    {
        return ExtSDLGPU::SDLGetPixelFormatFromGPUTextureFormat($format instanceof \BackedEnum ? $format->value : $format);
    }

    /**
     * SDL_InsertGPUDebugLabel().
     */
    public static function SDLInsertGPUDebugLabel(int $command_buffer, string $text): void
    {
        ExtSDLGPU::SDLInsertGPUDebugLabel($command_buffer, $text);
    }

    /**
     * SDL_MapGPUTransferBuffer().
     */
    public static function SDLMapGPUTransferBuffer(int $device, int $transfer_buffer, bool $cycle = false): int
    {
        return ExtSDLGPU::SDLMapGPUTransferBuffer(...array_slice([$device, $transfer_buffer, $cycle], 0, func_num_args()));
    }

    /**
     * SDL_PopGPUDebugGroup().
     */
    public static function SDLPopGPUDebugGroup(int $command_buffer): void
    {
        ExtSDLGPU::SDLPopGPUDebugGroup($command_buffer);
    }

    /**
     * SDL_PushGPUComputeUniformData().
     */
    public static function SDLPushGPUComputeUniformData(int $command_buffer, int $slot_index, string $data): void
    {
        ExtSDLGPU::SDLPushGPUComputeUniformData($command_buffer, $slot_index, $data);
    }

    /**
     * SDL_PushGPUDebugGroup().
     */
    public static function SDLPushGPUDebugGroup(int $command_buffer, string $name): void
    {
        ExtSDLGPU::SDLPushGPUDebugGroup($command_buffer, $name);
    }

    /**
     * SDL_PushGPUFragmentUniformData().
     */
    public static function SDLPushGPUFragmentUniformData(int $command_buffer, int $slot_index, string $data): void
    {
        ExtSDLGPU::SDLPushGPUFragmentUniformData($command_buffer, $slot_index, $data);
    }

    /**
     * SDL_PushGPUVertexUniformData().
     */
    public static function SDLPushGPUVertexUniformData(int $command_buffer, int $slot_index, string $data): void
    {
        ExtSDLGPU::SDLPushGPUVertexUniformData($command_buffer, $slot_index, $data);
    }

    /**
     * SDL_QueryGPUFence().
     */
    public static function SDLQueryGPUFence(int $device, int $fence): bool
    {
        return ExtSDLGPU::SDLQueryGPUFence($device, $fence);
    }

    /**
     * SDL_ReleaseGPUBuffer().
     */
    public static function SDLReleaseGPUBuffer(int $device, int $buffer): void
    {
        ExtSDLGPU::SDLReleaseGPUBuffer($device, $buffer);
    }

    /**
     * SDL_ReleaseGPUComputePipeline().
     */
    public static function SDLReleaseGPUComputePipeline(int $device, int $compute_pipeline): void
    {
        ExtSDLGPU::SDLReleaseGPUComputePipeline($device, $compute_pipeline);
    }

    /**
     * SDL_ReleaseGPUFence().
     */
    public static function SDLReleaseGPUFence(int $device, int $fence): void
    {
        ExtSDLGPU::SDLReleaseGPUFence($device, $fence);
    }

    /**
     * SDL_ReleaseGPUGraphicsPipeline().
     */
    public static function SDLReleaseGPUGraphicsPipeline(int $device, int $graphics_pipeline): void
    {
        ExtSDLGPU::SDLReleaseGPUGraphicsPipeline($device, $graphics_pipeline);
    }

    /**
     * SDL_ReleaseGPUSampler().
     */
    public static function SDLReleaseGPUSampler(int $device, int $sampler): void
    {
        ExtSDLGPU::SDLReleaseGPUSampler($device, $sampler);
    }

    /**
     * SDL_ReleaseGPUShader().
     */
    public static function SDLReleaseGPUShader(int $device, int $shader): void
    {
        ExtSDLGPU::SDLReleaseGPUShader($device, $shader);
    }

    /**
     * SDL_ReleaseGPUTexture().
     */
    public static function SDLReleaseGPUTexture(int $device, int $texture): void
    {
        ExtSDLGPU::SDLReleaseGPUTexture($device, $texture);
    }

    /**
     * SDL_ReleaseGPUTransferBuffer().
     */
    public static function SDLReleaseGPUTransferBuffer(int $device, int $transfer_buffer): void
    {
        ExtSDLGPU::SDLReleaseGPUTransferBuffer($device, $transfer_buffer);
    }

    /**
     * SDL_ReleaseWindowFromGPUDevice().
     */
    public static function SDLReleaseWindowFromGPUDevice(int $device, int $window): void
    {
        ExtSDLGPU::SDLReleaseWindowFromGPUDevice($device, $window);
    }

    /**
     * SDL_SetGPUAllowedFramesInFlight().
     */
    public static function SDLSetGPUAllowedFramesInFlight(int $device, int $allowed_frames_in_flight): bool
    {
        return ExtSDLGPU::SDLSetGPUAllowedFramesInFlight($device, $allowed_frames_in_flight);
    }

    /**
     * SDL_SetGPUBlendConstants().
     */
    public static function SDLSetGPUBlendConstants(int $render_pass, mixed $blend_constants): void
    {
        ExtSDLGPU::SDLSetGPUBlendConstants($render_pass, $blend_constants);
    }

    /**
     * SDL_SetGPUBufferName().
     */
    public static function SDLSetGPUBufferName(int $device, int $buffer, string $text): void
    {
        ExtSDLGPU::SDLSetGPUBufferName($device, $buffer, $text);
    }

    /**
     * SDL_SetGPURenderState().
     */
    public static function SDLSetGPURenderState(int $renderer, int $state = 0): bool
    {
        return ExtSDLGPU::SDLSetGPURenderState(...array_slice([$renderer, $state], 0, func_num_args()));
    }

    /**
     * SDL_SetGPURenderStateFragmentUniforms().
     */
    public static function SDLSetGPURenderStateFragmentUniforms(int $state, int $slot_index, string $data): bool
    {
        return ExtSDLGPU::SDLSetGPURenderStateFragmentUniforms($state, $slot_index, $data);
    }

    /**
     * SDL_SetGPUScissor().
     */
    public static function SDLSetGPUScissor(int $render_pass, mixed $scissor): void
    {
        ExtSDLGPU::SDLSetGPUScissor($render_pass, $scissor);
    }

    /**
     * SDL_SetGPUStencilReference().
     */
    public static function SDLSetGPUStencilReference(int $render_pass, int $reference): void
    {
        ExtSDLGPU::SDLSetGPUStencilReference($render_pass, $reference);
    }

    /**
     * SDL_SetGPUSwapchainParameters().
     */
    public static function SDLSetGPUSwapchainParameters(int $device, int $window, SDLGPUSwapchainComposition|int $swapchain_composition, SDLGPUPresentMode|int $present_mode): bool
    {
        return ExtSDLGPU::SDLSetGPUSwapchainParameters($device, $window, $swapchain_composition instanceof \BackedEnum ? $swapchain_composition->value : $swapchain_composition, $present_mode instanceof \BackedEnum ? $present_mode->value : $present_mode);
    }

    /**
     * SDL_SetGPUTextureName().
     */
    public static function SDLSetGPUTextureName(int $device, int $texture, string $text): void
    {
        ExtSDLGPU::SDLSetGPUTextureName($device, $texture, $text);
    }

    /**
     * SDL_SetGPUViewport().
     */
    public static function SDLSetGPUViewport(int $render_pass, mixed $viewport): void
    {
        ExtSDLGPU::SDLSetGPUViewport($render_pass, $viewport);
    }

    /**
     * SDL_SubmitGPUCommandBuffer().
     */
    public static function SDLSubmitGPUCommandBuffer(int $command_buffer): bool
    {
        return ExtSDLGPU::SDLSubmitGPUCommandBuffer($command_buffer);
    }

    /**
     * SDL_SubmitGPUCommandBufferAndAcquireFence().
     */
    public static function SDLSubmitGPUCommandBufferAndAcquireFence(int $command_buffer): int
    {
        return ExtSDLGPU::SDLSubmitGPUCommandBufferAndAcquireFence($command_buffer);
    }

    /**
     * SDL_UnmapGPUTransferBuffer().
     */
    public static function SDLUnmapGPUTransferBuffer(int $device, int $transfer_buffer): void
    {
        ExtSDLGPU::SDLUnmapGPUTransferBuffer($device, $transfer_buffer);
    }

    /**
     * SDL_UploadToGPUBuffer().
     */
    public static function SDLUploadToGPUBuffer(int $copy_pass, mixed $source, mixed $destination, bool $cycle = false): void
    {
        ExtSDLGPU::SDLUploadToGPUBuffer(...array_slice([$copy_pass, $source, $destination, $cycle], 0, func_num_args()));
    }

    /**
     * SDL_UploadToGPUTexture().
     */
    public static function SDLUploadToGPUTexture(int $copy_pass, mixed $source, mixed $destination, bool $cycle = false): void
    {
        ExtSDLGPU::SDLUploadToGPUTexture(...array_slice([$copy_pass, $source, $destination, $cycle], 0, func_num_args()));
    }

    /**
     * SDL_WaitAndAcquireGPUSwapchainTexture().
     */
    public static function SDLWaitAndAcquireGPUSwapchainTexture(int $command_buffer, int $window): array
    {
        return ExtSDLGPU::SDLWaitAndAcquireGPUSwapchainTexture($command_buffer, $window);
    }

    /**
     * SDL_WaitForGPUFences().
     */
    public static function SDLWaitForGPUFences(int $device, bool $wait_all, mixed $fences): bool
    {
        return ExtSDLGPU::SDLWaitForGPUFences($device, $wait_all, $fences);
    }

    /**
     * SDL_WaitForGPUIdle().
     */
    public static function SDLWaitForGPUIdle(int $device): bool
    {
        return ExtSDLGPU::SDLWaitForGPUIdle($device);
    }

    /**
     * SDL_WaitForGPUSwapchain().
     */
    public static function SDLWaitForGPUSwapchain(int $device, int $window): bool
    {
        return ExtSDLGPU::SDLWaitForGPUSwapchain($device, $window);
    }

    /**
     * SDL_WindowSupportsGPUPresentMode().
     */
    public static function SDLWindowSupportsGPUPresentMode(int $device, int $window, SDLGPUPresentMode|int $present_mode): bool
    {
        return ExtSDLGPU::SDLWindowSupportsGPUPresentMode($device, $window, $present_mode instanceof \BackedEnum ? $present_mode->value : $present_mode);
    }

    /**
     * SDL_WindowSupportsGPUSwapchainComposition().
     */
    public static function SDLWindowSupportsGPUSwapchainComposition(int $device, int $window, SDLGPUSwapchainComposition|int $swapchain_composition): bool
    {
        return ExtSDLGPU::SDLWindowSupportsGPUSwapchainComposition($device, $window, $swapchain_composition instanceof \BackedEnum ? $swapchain_composition->value : $swapchain_composition);
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function readFromGPUTransferBuffer(int $device, int $transfer_buffer, int $length, int $offset = 0): string
    {
        return ExtSDLGPU::readFromGPUTransferBuffer(...array_slice([$device, $transfer_buffer, $length, $offset], 0, func_num_args()));
    }

    /**
     * Extension glue: no SDL3 function of this name.
     */
    public static function writeToGPUTransferBuffer(int $device, int $transfer_buffer, string $data, bool $cycle = false, int $offset = 0): bool
    {
        return ExtSDLGPU::writeToGPUTransferBuffer(...array_slice([$device, $transfer_buffer, $data, $cycle, $offset], 0, func_num_args()));
    }
}
