<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Input;

use Jovian\Bindings\Sdl3\Enums\SDLGamepadAxis;
use Jovian\Bindings\Sdl3\Enums\SDLGamepadButton;
use Jovian\Bindings\Sdl3\Enums\SDLGamepadButtonLabel;
use Jovian\Bindings\Sdl3\Enums\SDLGamepadType;
use Jovian\Bindings\Sdl3\Enums\SDLJoystickConnectionState;
use Jovian\Bindings\Sdl3\Enums\SDLSensorType;
use Sdl3\SDL\Input\SDLGamepad as ExtSDLGamepad;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Input\SDLGamepad
 * from ext-sdl3 0.8.0, one method per extension call.
 */
final class SDLGamepad
{
    /**
     * SDL_AddGamepadMapping().
     */
    public static function SDLAddGamepadMapping(string $mapping): int
    {
        return ExtSDLGamepad::SDLAddGamepadMapping($mapping);
    }

    /**
     * SDL_AddGamepadMappingsFromFile().
     */
    public static function SDLAddGamepadMappingsFromFile(string $file): int
    {
        return ExtSDLGamepad::SDLAddGamepadMappingsFromFile($file);
    }

    /**
     * SDL_CloseGamepad().
     */
    public static function SDLCloseGamepad(int $gamepad): void
    {
        ExtSDLGamepad::SDLCloseGamepad($gamepad);
    }

    /**
     * SDL_GamepadConnected().
     */
    public static function SDLGamepadConnected(int $gamepad): bool
    {
        return ExtSDLGamepad::SDLGamepadConnected($gamepad);
    }

    /**
     * SDL_GamepadEventsEnabled().
     */
    public static function SDLGamepadEventsEnabled(): bool
    {
        return ExtSDLGamepad::SDLGamepadEventsEnabled();
    }

    /**
     * SDL_GamepadHasAxis().
     */
    public static function SDLGamepadHasAxis(int $gamepad, SDLGamepadAxis|int $axis): bool
    {
        return ExtSDLGamepad::SDLGamepadHasAxis($gamepad, $axis instanceof \BackedEnum ? $axis->value : $axis);
    }

    /**
     * SDL_GamepadHasButton().
     */
    public static function SDLGamepadHasButton(int $gamepad, SDLGamepadButton|int $button): bool
    {
        return ExtSDLGamepad::SDLGamepadHasButton($gamepad, $button instanceof \BackedEnum ? $button->value : $button);
    }

    /**
     * SDL_GamepadHasSensor().
     */
    public static function SDLGamepadHasSensor(int $gamepad, SDLSensorType|int $type): bool
    {
        return ExtSDLGamepad::SDLGamepadHasSensor($gamepad, $type instanceof \BackedEnum ? $type->value : $type);
    }

    /**
     * SDL_GamepadSensorEnabled().
     */
    public static function SDLGamepadSensorEnabled(int $gamepad, SDLSensorType|int $type): bool
    {
        return ExtSDLGamepad::SDLGamepadSensorEnabled($gamepad, $type instanceof \BackedEnum ? $type->value : $type);
    }

    /**
     * SDL_GetGamepadAppleSFSymbolsNameForAxis().
     */
    public static function SDLGetGamepadAppleSFSymbolsNameForAxis(int $gamepad, SDLGamepadAxis|int $axis): string
    {
        return ExtSDLGamepad::SDLGetGamepadAppleSFSymbolsNameForAxis($gamepad, $axis instanceof \BackedEnum ? $axis->value : $axis);
    }

    /**
     * SDL_GetGamepadAppleSFSymbolsNameForButton().
     */
    public static function SDLGetGamepadAppleSFSymbolsNameForButton(int $gamepad, SDLGamepadButton|int $button): string
    {
        return ExtSDLGamepad::SDLGetGamepadAppleSFSymbolsNameForButton($gamepad, $button instanceof \BackedEnum ? $button->value : $button);
    }

    /**
     * SDL_GetGamepadAxis().
     */
    public static function SDLGetGamepadAxis(int $gamepad, SDLGamepadAxis|int $axis): int
    {
        return ExtSDLGamepad::SDLGetGamepadAxis($gamepad, $axis instanceof \BackedEnum ? $axis->value : $axis);
    }

    /**
     * SDL_GetGamepadAxisFromString().
     */
    public static function SDLGetGamepadAxisFromString(string $str): SDLGamepadAxis|int
    {
        return ExtSDLGamepad::SDLGetGamepadAxisFromString($str);
    }

    /**
     * SDL_GetGamepadBindings().
     */
    public static function SDLGetGamepadBindings(int $gamepad): array
    {
        return ExtSDLGamepad::SDLGetGamepadBindings($gamepad);
    }

    /**
     * SDL_GetGamepadButton().
     */
    public static function SDLGetGamepadButton(int $gamepad, SDLGamepadButton|int $button): bool
    {
        return ExtSDLGamepad::SDLGetGamepadButton($gamepad, $button instanceof \BackedEnum ? $button->value : $button);
    }

    /**
     * SDL_GetGamepadButtonFromString().
     */
    public static function SDLGetGamepadButtonFromString(string $str): SDLGamepadButton|int
    {
        return ExtSDLGamepad::SDLGetGamepadButtonFromString($str);
    }

    /**
     * SDL_GetGamepadButtonLabel().
     */
    public static function SDLGetGamepadButtonLabel(int $gamepad, SDLGamepadButton|int $button): SDLGamepadButtonLabel|int
    {
        return ExtSDLGamepad::SDLGetGamepadButtonLabel($gamepad, $button instanceof \BackedEnum ? $button->value : $button);
    }

    /**
     * SDL_GetGamepadButtonLabelForType().
     */
    public static function SDLGetGamepadButtonLabelForType(SDLGamepadType|int $type, SDLGamepadButton|int $button): SDLGamepadButtonLabel|int
    {
        return ExtSDLGamepad::SDLGetGamepadButtonLabelForType($type instanceof \BackedEnum ? $type->value : $type, $button instanceof \BackedEnum ? $button->value : $button);
    }

    /**
     * SDL_GetGamepadConnectionState().
     */
    public static function SDLGetGamepadConnectionState(int $gamepad): SDLJoystickConnectionState|int
    {
        return ExtSDLGamepad::SDLGetGamepadConnectionState($gamepad);
    }

    /**
     * SDL_GetGamepadFirmwareVersion().
     */
    public static function SDLGetGamepadFirmwareVersion(int $gamepad): int
    {
        return ExtSDLGamepad::SDLGetGamepadFirmwareVersion($gamepad);
    }

    /**
     * SDL_GetGamepadFromID().
     */
    public static function SDLGetGamepadFromID(int $instance_id): int
    {
        return ExtSDLGamepad::SDLGetGamepadFromID($instance_id);
    }

    /**
     * SDL_GetGamepadFromPlayerIndex().
     */
    public static function SDLGetGamepadFromPlayerIndex(int $player_index): int
    {
        return ExtSDLGamepad::SDLGetGamepadFromPlayerIndex($player_index);
    }

    /**
     * SDL_GetGamepadGUIDForID().
     */
    public static function SDLGetGamepadGUIDForID(int $instance_id): string
    {
        return ExtSDLGamepad::SDLGetGamepadGUIDForID($instance_id);
    }

    /**
     * SDL_GetGamepadID().
     */
    public static function SDLGetGamepadID(int $gamepad): int
    {
        return ExtSDLGamepad::SDLGetGamepadID($gamepad);
    }

    /**
     * SDL_GetGamepadJoystick().
     */
    public static function SDLGetGamepadJoystick(int $gamepad): int
    {
        return ExtSDLGamepad::SDLGetGamepadJoystick($gamepad);
    }

    /**
     * SDL_GetGamepadMapping().
     */
    public static function SDLGetGamepadMapping(int $gamepad): string
    {
        return ExtSDLGamepad::SDLGetGamepadMapping($gamepad);
    }

    /**
     * SDL_GetGamepadMappingForGUID().
     */
    public static function SDLGetGamepadMappingForGUID(string $guid): string
    {
        return ExtSDLGamepad::SDLGetGamepadMappingForGUID($guid);
    }

    /**
     * SDL_GetGamepadMappingForID().
     */
    public static function SDLGetGamepadMappingForID(int $instance_id): string
    {
        return ExtSDLGamepad::SDLGetGamepadMappingForID($instance_id);
    }

    /**
     * SDL_GetGamepadMappings().
     */
    public static function SDLGetGamepadMappings(): array
    {
        return ExtSDLGamepad::SDLGetGamepadMappings();
    }

    /**
     * SDL_GetGamepadName().
     */
    public static function SDLGetGamepadName(int $gamepad): string
    {
        return ExtSDLGamepad::SDLGetGamepadName($gamepad);
    }

    /**
     * SDL_GetGamepadNameForID().
     */
    public static function SDLGetGamepadNameForID(int $instance_id): string
    {
        return ExtSDLGamepad::SDLGetGamepadNameForID($instance_id);
    }

    /**
     * SDL_GetGamepadPath().
     */
    public static function SDLGetGamepadPath(int $gamepad): string
    {
        return ExtSDLGamepad::SDLGetGamepadPath($gamepad);
    }

    /**
     * SDL_GetGamepadPathForID().
     */
    public static function SDLGetGamepadPathForID(int $instance_id): string
    {
        return ExtSDLGamepad::SDLGetGamepadPathForID($instance_id);
    }

    /**
     * SDL_GetGamepadPlayerIndex().
     */
    public static function SDLGetGamepadPlayerIndex(int $gamepad): int
    {
        return ExtSDLGamepad::SDLGetGamepadPlayerIndex($gamepad);
    }

    /**
     * SDL_GetGamepadPlayerIndexForID().
     */
    public static function SDLGetGamepadPlayerIndexForID(int $instance_id): int
    {
        return ExtSDLGamepad::SDLGetGamepadPlayerIndexForID($instance_id);
    }

    /**
     * SDL_GetGamepadPowerInfo().
     */
    public static function SDLGetGamepadPowerInfo(int $gamepad): array
    {
        return ExtSDLGamepad::SDLGetGamepadPowerInfo($gamepad);
    }

    /**
     * SDL_GetGamepadProduct().
     */
    public static function SDLGetGamepadProduct(int $gamepad): int
    {
        return ExtSDLGamepad::SDLGetGamepadProduct($gamepad);
    }

    /**
     * SDL_GetGamepadProductForID().
     */
    public static function SDLGetGamepadProductForID(int $instance_id): int
    {
        return ExtSDLGamepad::SDLGetGamepadProductForID($instance_id);
    }

    /**
     * SDL_GetGamepadProductVersion().
     */
    public static function SDLGetGamepadProductVersion(int $gamepad): int
    {
        return ExtSDLGamepad::SDLGetGamepadProductVersion($gamepad);
    }

    /**
     * SDL_GetGamepadProductVersionForID().
     */
    public static function SDLGetGamepadProductVersionForID(int $instance_id): int
    {
        return ExtSDLGamepad::SDLGetGamepadProductVersionForID($instance_id);
    }

    /**
     * SDL_GetGamepadProperties().
     */
    public static function SDLGetGamepadProperties(int $gamepad): int
    {
        return ExtSDLGamepad::SDLGetGamepadProperties($gamepad);
    }

    /**
     * SDL_GetGamepadSensorData().
     */
    public static function SDLGetGamepadSensorData(int $gamepad, SDLSensorType|int $type, int $num_values): array
    {
        return ExtSDLGamepad::SDLGetGamepadSensorData($gamepad, $type instanceof \BackedEnum ? $type->value : $type, $num_values);
    }

    /**
     * SDL_GetGamepadSensorDataRate().
     */
    public static function SDLGetGamepadSensorDataRate(int $gamepad, SDLSensorType|int $type): float
    {
        return ExtSDLGamepad::SDLGetGamepadSensorDataRate($gamepad, $type instanceof \BackedEnum ? $type->value : $type);
    }

    /**
     * SDL_GetGamepadSerial().
     */
    public static function SDLGetGamepadSerial(int $gamepad): string
    {
        return ExtSDLGamepad::SDLGetGamepadSerial($gamepad);
    }

    /**
     * SDL_GetGamepadSteamHandle().
     */
    public static function SDLGetGamepadSteamHandle(int $gamepad): int
    {
        return ExtSDLGamepad::SDLGetGamepadSteamHandle($gamepad);
    }

    /**
     * SDL_GetGamepadStringForAxis().
     */
    public static function SDLGetGamepadStringForAxis(SDLGamepadAxis|int $axis): string
    {
        return ExtSDLGamepad::SDLGetGamepadStringForAxis($axis instanceof \BackedEnum ? $axis->value : $axis);
    }

    /**
     * SDL_GetGamepadStringForButton().
     */
    public static function SDLGetGamepadStringForButton(SDLGamepadButton|int $button): string
    {
        return ExtSDLGamepad::SDLGetGamepadStringForButton($button instanceof \BackedEnum ? $button->value : $button);
    }

    /**
     * SDL_GetGamepadStringForType().
     */
    public static function SDLGetGamepadStringForType(SDLGamepadType|int $type): string
    {
        return ExtSDLGamepad::SDLGetGamepadStringForType($type instanceof \BackedEnum ? $type->value : $type);
    }

    /**
     * SDL_GetGamepadTouchpadFinger().
     */
    public static function SDLGetGamepadTouchpadFinger(int $gamepad, int $touchpad, int $finger): array
    {
        return ExtSDLGamepad::SDLGetGamepadTouchpadFinger($gamepad, $touchpad, $finger);
    }

    /**
     * SDL_GetGamepadType().
     */
    public static function SDLGetGamepadType(int $gamepad): SDLGamepadType|int
    {
        return ExtSDLGamepad::SDLGetGamepadType($gamepad);
    }

    /**
     * SDL_GetGamepadTypeForID().
     */
    public static function SDLGetGamepadTypeForID(int $instance_id): SDLGamepadType|int
    {
        return ExtSDLGamepad::SDLGetGamepadTypeForID($instance_id);
    }

    /**
     * SDL_GetGamepadTypeFromString().
     */
    public static function SDLGetGamepadTypeFromString(string $str): SDLGamepadType|int
    {
        return ExtSDLGamepad::SDLGetGamepadTypeFromString($str);
    }

    /**
     * SDL_GetGamepadVendor().
     */
    public static function SDLGetGamepadVendor(int $gamepad): int
    {
        return ExtSDLGamepad::SDLGetGamepadVendor($gamepad);
    }

    /**
     * SDL_GetGamepadVendorForID().
     */
    public static function SDLGetGamepadVendorForID(int $instance_id): int
    {
        return ExtSDLGamepad::SDLGetGamepadVendorForID($instance_id);
    }

    /**
     * SDL_GetGamepads().
     */
    public static function SDLGetGamepads(): array
    {
        return ExtSDLGamepad::SDLGetGamepads();
    }

    /**
     * SDL_GetNumGamepadTouchpadFingers().
     */
    public static function SDLGetNumGamepadTouchpadFingers(int $gamepad, int $touchpad): int
    {
        return ExtSDLGamepad::SDLGetNumGamepadTouchpadFingers($gamepad, $touchpad);
    }

    /**
     * SDL_GetNumGamepadTouchpads().
     */
    public static function SDLGetNumGamepadTouchpads(int $gamepad): int
    {
        return ExtSDLGamepad::SDLGetNumGamepadTouchpads($gamepad);
    }

    /**
     * SDL_GetRealGamepadType().
     */
    public static function SDLGetRealGamepadType(int $gamepad): SDLGamepadType|int
    {
        return ExtSDLGamepad::SDLGetRealGamepadType($gamepad);
    }

    /**
     * SDL_GetRealGamepadTypeForID().
     */
    public static function SDLGetRealGamepadTypeForID(int $instance_id): SDLGamepadType|int
    {
        return ExtSDLGamepad::SDLGetRealGamepadTypeForID($instance_id);
    }

    /**
     * SDL_HasGamepad().
     */
    public static function SDLHasGamepad(): bool
    {
        return ExtSDLGamepad::SDLHasGamepad();
    }

    /**
     * SDL_IsGamepad().
     */
    public static function SDLIsGamepad(int $instance_id): bool
    {
        return ExtSDLGamepad::SDLIsGamepad($instance_id);
    }

    /**
     * SDL_OpenGamepad().
     */
    public static function SDLOpenGamepad(int $instance_id): int
    {
        return ExtSDLGamepad::SDLOpenGamepad($instance_id);
    }

    /**
     * SDL_ReloadGamepadMappings().
     */
    public static function SDLReloadGamepadMappings(): bool
    {
        return ExtSDLGamepad::SDLReloadGamepadMappings();
    }

    /**
     * SDL_RumbleGamepad().
     */
    public static function SDLRumbleGamepad(int $gamepad, int $low_frequency_rumble, int $high_frequency_rumble, int $duration_ms): bool
    {
        return ExtSDLGamepad::SDLRumbleGamepad($gamepad, $low_frequency_rumble, $high_frequency_rumble, $duration_ms);
    }

    /**
     * SDL_RumbleGamepadTriggers().
     */
    public static function SDLRumbleGamepadTriggers(int $gamepad, int $left_rumble, int $right_rumble, int $duration_ms): bool
    {
        return ExtSDLGamepad::SDLRumbleGamepadTriggers($gamepad, $left_rumble, $right_rumble, $duration_ms);
    }

    /**
     * SDL_SendGamepadEffect().
     */
    public static function SDLSendGamepadEffect(int $gamepad, string $data): bool
    {
        return ExtSDLGamepad::SDLSendGamepadEffect($gamepad, $data);
    }

    /**
     * SDL_SetGamepadEventsEnabled().
     */
    public static function SDLSetGamepadEventsEnabled(bool $enabled): void
    {
        ExtSDLGamepad::SDLSetGamepadEventsEnabled($enabled);
    }

    /**
     * SDL_SetGamepadLED().
     */
    public static function SDLSetGamepadLED(int $gamepad, int $red, int $green, int $blue): bool
    {
        return ExtSDLGamepad::SDLSetGamepadLED($gamepad, $red, $green, $blue);
    }

    /**
     * SDL_SetGamepadMapping().
     */
    public static function SDLSetGamepadMapping(int $instance_id, mixed $mapping = null): bool
    {
        return ExtSDLGamepad::SDLSetGamepadMapping(...array_slice([$instance_id, $mapping], 0, func_num_args()));
    }

    /**
     * SDL_SetGamepadPlayerIndex().
     */
    public static function SDLSetGamepadPlayerIndex(int $gamepad, int $player_index): bool
    {
        return ExtSDLGamepad::SDLSetGamepadPlayerIndex($gamepad, $player_index);
    }

    /**
     * SDL_SetGamepadSensorEnabled().
     */
    public static function SDLSetGamepadSensorEnabled(int $gamepad, SDLSensorType|int $type, bool $enabled): bool
    {
        return ExtSDLGamepad::SDLSetGamepadSensorEnabled($gamepad, $type instanceof \BackedEnum ? $type->value : $type, $enabled);
    }

    /**
     * SDL_UpdateGamepads().
     */
    public static function SDLUpdateGamepads(): void
    {
        ExtSDLGamepad::SDLUpdateGamepads();
    }
}
