<?php

declare(strict_types=1);

namespace Jovian\Bindings\Sdl3\Input;

use Jovian\Bindings\Sdl3\Enums\SDLJoystickConnectionState;
use Jovian\Bindings\Sdl3\Enums\SDLJoystickType;
use Jovian\Bindings\Sdl3\Enums\SDLSensorType;
use Sdl3\SDL\Input\SDLJoystick as ExtSDLJoystick;

/**
 * GENERATED by scripts/generate.php. Do not hand-edit.
 *
 * Projects Sdl3\SDL\Input\SDLJoystick
 * from ext-sdl3 0.7.0, one method per extension call.
 */
final class SDLJoystick
{
    /**
     * SDL_AttachVirtualJoystick().
     */
    public static function SDLAttachVirtualJoystick(array $desc): int
    {
        return ExtSDLJoystick::SDLAttachVirtualJoystick($desc);
    }

    /**
     * SDL_CloseJoystick().
     */
    public static function SDLCloseJoystick(int $joystick): void
    {
        ExtSDLJoystick::SDLCloseJoystick($joystick);
    }

    /**
     * SDL_DetachVirtualJoystick().
     */
    public static function SDLDetachVirtualJoystick(int $instance_id): bool
    {
        return ExtSDLJoystick::SDLDetachVirtualJoystick($instance_id);
    }

    /**
     * SDL_GetJoystickAxis().
     */
    public static function SDLGetJoystickAxis(int $joystick, int $axis): int
    {
        return ExtSDLJoystick::SDLGetJoystickAxis($joystick, $axis);
    }

    /**
     * SDL_GetJoystickAxisInitialState().
     */
    public static function SDLGetJoystickAxisInitialState(int $joystick, int $axis): array
    {
        return ExtSDLJoystick::SDLGetJoystickAxisInitialState($joystick, $axis);
    }

    /**
     * SDL_GetJoystickBall().
     */
    public static function SDLGetJoystickBall(int $joystick, int $ball): array
    {
        return ExtSDLJoystick::SDLGetJoystickBall($joystick, $ball);
    }

    /**
     * SDL_GetJoystickButton().
     */
    public static function SDLGetJoystickButton(int $joystick, int $button): bool
    {
        return ExtSDLJoystick::SDLGetJoystickButton($joystick, $button);
    }

    /**
     * SDL_GetJoystickConnectionState().
     */
    public static function SDLGetJoystickConnectionState(int $joystick): SDLJoystickConnectionState|int
    {
        return ExtSDLJoystick::SDLGetJoystickConnectionState($joystick);
    }

    /**
     * SDL_GetJoystickFirmwareVersion().
     */
    public static function SDLGetJoystickFirmwareVersion(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetJoystickFirmwareVersion($joystick);
    }

    /**
     * SDL_GetJoystickFromID().
     */
    public static function SDLGetJoystickFromID(int $instance_id): int
    {
        return ExtSDLJoystick::SDLGetJoystickFromID($instance_id);
    }

    /**
     * SDL_GetJoystickFromPlayerIndex().
     */
    public static function SDLGetJoystickFromPlayerIndex(int $player_index): int
    {
        return ExtSDLJoystick::SDLGetJoystickFromPlayerIndex($player_index);
    }

    /**
     * SDL_GetJoystickGUID().
     */
    public static function SDLGetJoystickGUID(int $joystick): string
    {
        return ExtSDLJoystick::SDLGetJoystickGUID($joystick);
    }

    /**
     * SDL_GetJoystickGUIDForID().
     */
    public static function SDLGetJoystickGUIDForID(int $instance_id): string
    {
        return ExtSDLJoystick::SDLGetJoystickGUIDForID($instance_id);
    }

    /**
     * SDL_GetJoystickGUIDInfo().
     */
    public static function SDLGetJoystickGUIDInfo(string $guid): array
    {
        return ExtSDLJoystick::SDLGetJoystickGUIDInfo($guid);
    }

    /**
     * SDL_GetJoystickHat().
     */
    public static function SDLGetJoystickHat(int $joystick, int $hat): int
    {
        return ExtSDLJoystick::SDLGetJoystickHat($joystick, $hat);
    }

    /**
     * SDL_GetJoystickID().
     */
    public static function SDLGetJoystickID(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetJoystickID($joystick);
    }

    /**
     * SDL_GetJoystickName().
     */
    public static function SDLGetJoystickName(int $joystick): string
    {
        return ExtSDLJoystick::SDLGetJoystickName($joystick);
    }

    /**
     * SDL_GetJoystickNameForID().
     */
    public static function SDLGetJoystickNameForID(int $instance_id): string
    {
        return ExtSDLJoystick::SDLGetJoystickNameForID($instance_id);
    }

    /**
     * SDL_GetJoystickPath().
     */
    public static function SDLGetJoystickPath(int $joystick): string
    {
        return ExtSDLJoystick::SDLGetJoystickPath($joystick);
    }

    /**
     * SDL_GetJoystickPathForID().
     */
    public static function SDLGetJoystickPathForID(int $instance_id): string
    {
        return ExtSDLJoystick::SDLGetJoystickPathForID($instance_id);
    }

    /**
     * SDL_GetJoystickPlayerIndex().
     */
    public static function SDLGetJoystickPlayerIndex(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetJoystickPlayerIndex($joystick);
    }

    /**
     * SDL_GetJoystickPlayerIndexForID().
     */
    public static function SDLGetJoystickPlayerIndexForID(int $instance_id): int
    {
        return ExtSDLJoystick::SDLGetJoystickPlayerIndexForID($instance_id);
    }

    /**
     * SDL_GetJoystickPowerInfo().
     */
    public static function SDLGetJoystickPowerInfo(int $joystick): array
    {
        return ExtSDLJoystick::SDLGetJoystickPowerInfo($joystick);
    }

    /**
     * SDL_GetJoystickProduct().
     */
    public static function SDLGetJoystickProduct(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetJoystickProduct($joystick);
    }

    /**
     * SDL_GetJoystickProductForID().
     */
    public static function SDLGetJoystickProductForID(int $instance_id): int
    {
        return ExtSDLJoystick::SDLGetJoystickProductForID($instance_id);
    }

    /**
     * SDL_GetJoystickProductVersion().
     */
    public static function SDLGetJoystickProductVersion(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetJoystickProductVersion($joystick);
    }

    /**
     * SDL_GetJoystickProductVersionForID().
     */
    public static function SDLGetJoystickProductVersionForID(int $instance_id): int
    {
        return ExtSDLJoystick::SDLGetJoystickProductVersionForID($instance_id);
    }

    /**
     * SDL_GetJoystickProperties().
     */
    public static function SDLGetJoystickProperties(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetJoystickProperties($joystick);
    }

    /**
     * SDL_GetJoystickSerial().
     */
    public static function SDLGetJoystickSerial(int $joystick): string
    {
        return ExtSDLJoystick::SDLGetJoystickSerial($joystick);
    }

    /**
     * SDL_GetJoystickType().
     */
    public static function SDLGetJoystickType(int $joystick): SDLJoystickType|int
    {
        return ExtSDLJoystick::SDLGetJoystickType($joystick);
    }

    /**
     * SDL_GetJoystickTypeForID().
     */
    public static function SDLGetJoystickTypeForID(int $instance_id): SDLJoystickType|int
    {
        return ExtSDLJoystick::SDLGetJoystickTypeForID($instance_id);
    }

    /**
     * SDL_GetJoystickVendor().
     */
    public static function SDLGetJoystickVendor(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetJoystickVendor($joystick);
    }

    /**
     * SDL_GetJoystickVendorForID().
     */
    public static function SDLGetJoystickVendorForID(int $instance_id): int
    {
        return ExtSDLJoystick::SDLGetJoystickVendorForID($instance_id);
    }

    /**
     * SDL_GetJoysticks().
     */
    public static function SDLGetJoysticks(): array
    {
        return ExtSDLJoystick::SDLGetJoysticks();
    }

    /**
     * SDL_GetNumJoystickAxes().
     */
    public static function SDLGetNumJoystickAxes(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetNumJoystickAxes($joystick);
    }

    /**
     * SDL_GetNumJoystickBalls().
     */
    public static function SDLGetNumJoystickBalls(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetNumJoystickBalls($joystick);
    }

    /**
     * SDL_GetNumJoystickButtons().
     */
    public static function SDLGetNumJoystickButtons(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetNumJoystickButtons($joystick);
    }

    /**
     * SDL_GetNumJoystickHats().
     */
    public static function SDLGetNumJoystickHats(int $joystick): int
    {
        return ExtSDLJoystick::SDLGetNumJoystickHats($joystick);
    }

    /**
     * SDL_HasJoystick().
     */
    public static function SDLHasJoystick(): bool
    {
        return ExtSDLJoystick::SDLHasJoystick();
    }

    /**
     * SDL_IsJoystickVirtual().
     */
    public static function SDLIsJoystickVirtual(int $instance_id): bool
    {
        return ExtSDLJoystick::SDLIsJoystickVirtual($instance_id);
    }

    /**
     * SDL_JoystickConnected().
     */
    public static function SDLJoystickConnected(int $joystick): bool
    {
        return ExtSDLJoystick::SDLJoystickConnected($joystick);
    }

    /**
     * SDL_JoystickEventsEnabled().
     */
    public static function SDLJoystickEventsEnabled(): bool
    {
        return ExtSDLJoystick::SDLJoystickEventsEnabled();
    }

    /**
     * SDL_LockJoysticks().
     */
    public static function SDLLockJoysticks(): void
    {
        ExtSDLJoystick::SDLLockJoysticks();
    }

    /**
     * SDL_OpenJoystick().
     */
    public static function SDLOpenJoystick(int $instance_id): int
    {
        return ExtSDLJoystick::SDLOpenJoystick($instance_id);
    }

    /**
     * SDL_RumbleJoystick().
     */
    public static function SDLRumbleJoystick(int $joystick, int $low_frequency_rumble, int $high_frequency_rumble, int $duration_ms): bool
    {
        return ExtSDLJoystick::SDLRumbleJoystick($joystick, $low_frequency_rumble, $high_frequency_rumble, $duration_ms);
    }

    /**
     * SDL_RumbleJoystickTriggers().
     */
    public static function SDLRumbleJoystickTriggers(int $joystick, int $left_rumble, int $right_rumble, int $duration_ms): bool
    {
        return ExtSDLJoystick::SDLRumbleJoystickTriggers($joystick, $left_rumble, $right_rumble, $duration_ms);
    }

    /**
     * SDL_SendJoystickEffect().
     */
    public static function SDLSendJoystickEffect(int $joystick, string $data): bool
    {
        return ExtSDLJoystick::SDLSendJoystickEffect($joystick, $data);
    }

    /**
     * SDL_SendJoystickVirtualSensorData().
     */
    public static function SDLSendJoystickVirtualSensorData(int $joystick, SDLSensorType|int $type, int $sensor_timestamp, array $data): bool
    {
        return ExtSDLJoystick::SDLSendJoystickVirtualSensorData($joystick, $type instanceof \BackedEnum ? $type->value : $type, $sensor_timestamp, $data);
    }

    /**
     * SDL_SetJoystickEventsEnabled().
     */
    public static function SDLSetJoystickEventsEnabled(bool $enabled): void
    {
        ExtSDLJoystick::SDLSetJoystickEventsEnabled($enabled);
    }

    /**
     * SDL_SetJoystickLED().
     */
    public static function SDLSetJoystickLED(int $joystick, int $red, int $green, int $blue): bool
    {
        return ExtSDLJoystick::SDLSetJoystickLED($joystick, $red, $green, $blue);
    }

    /**
     * SDL_SetJoystickPlayerIndex().
     */
    public static function SDLSetJoystickPlayerIndex(int $joystick, int $player_index): bool
    {
        return ExtSDLJoystick::SDLSetJoystickPlayerIndex($joystick, $player_index);
    }

    /**
     * SDL_SetJoystickVirtualAxis().
     */
    public static function SDLSetJoystickVirtualAxis(int $joystick, int $axis, int $value): bool
    {
        return ExtSDLJoystick::SDLSetJoystickVirtualAxis($joystick, $axis, $value);
    }

    /**
     * SDL_SetJoystickVirtualBall().
     */
    public static function SDLSetJoystickVirtualBall(int $joystick, int $ball, int $xrel, int $yrel): bool
    {
        return ExtSDLJoystick::SDLSetJoystickVirtualBall($joystick, $ball, $xrel, $yrel);
    }

    /**
     * SDL_SetJoystickVirtualButton().
     */
    public static function SDLSetJoystickVirtualButton(int $joystick, int $button, bool $down): bool
    {
        return ExtSDLJoystick::SDLSetJoystickVirtualButton($joystick, $button, $down);
    }

    /**
     * SDL_SetJoystickVirtualHat().
     */
    public static function SDLSetJoystickVirtualHat(int $joystick, int $hat, int $value): bool
    {
        return ExtSDLJoystick::SDLSetJoystickVirtualHat($joystick, $hat, $value);
    }

    /**
     * SDL_SetJoystickVirtualTouchpad().
     */
    public static function SDLSetJoystickVirtualTouchpad(int $joystick, int $touchpad, int $finger, bool $down, float $x, float $y, float $pressure): bool
    {
        return ExtSDLJoystick::SDLSetJoystickVirtualTouchpad($joystick, $touchpad, $finger, $down, $x, $y, $pressure);
    }

    /**
     * SDL_UnlockJoysticks().
     */
    public static function SDLUnlockJoysticks(): void
    {
        ExtSDLJoystick::SDLUnlockJoysticks();
    }

    /**
     * SDL_UpdateJoysticks().
     */
    public static function SDLUpdateJoysticks(): void
    {
        ExtSDLJoystick::SDLUpdateJoysticks();
    }
}
